export default {
  ADD: 'PE_TRANSACTIONS_ADD',
  REMOVE: 'PE_TRANSACTIONS_REMOVE',
  EDIT_FIELD: 'PE_TRANSACTIONS_EDIT_FIELD',
  ADD_SECTOR: 'PE_TRANSACTION_SECTORS_ADD',
  REMOVE_SECTOR: 'PE_TRANSACTION_SECTORS_REMOVE',
  EDIT_FIELD_SECTOR: 'PE_TRANSACTION_SECTORS_EDIT_FIELD'
}
