restoreFrom: empty

postgresql:
  livenessProbe:
    initialDelaySeconds: 600

  image:
    repository: akvo/akvo-rsr-demo-postgres
    tag: 20200413.153931.5f37d97
  postgresqlUsername: postgres
  master:
    extraVolumeMounts:
      - name: "secret-config"
        mountPath: "/akvo-lumen-service-account-credentials.json"
        subPath: "service-account-training-envs.json"
    extraVolumes:
      - name: "secret-config"
        secret:
          secretName: "rsr-common"
  extraEnv:
    - name: ELEPHANTSQL_API_KEY
      valueFrom:
        secretKeyRef:
          name: "rsr-common"
          key: elephantsql-api-key
    - name: REPORTSERVER_USER_PASSWORD
      valueFrom:
        secretKeyRef:
          name: rsr-reportserver-training
          key: rs_db_password
    - name: REPORTSERVER_DB_USER
      valueFrom:
        secretKeyRef:
          name: rsr-reportserver-training
          key: rs_db_user
    - name: REPORTSERVER_DB_NAME
      valueFrom:
        secretKeyRef:
          name: rsr-reportserver-training
          key: rs_db_name
    - name: ENCRYPTED_RSR_PASSWORD
      valueFrom:
        secretKeyRef:
          name: rsr-reportserver-training
          key: rs_rsr_db_encrypted_password
  initdbScriptsConfigMap: "{{ include \"rsrchart.fullname\" . }}-seed-db"