restoreFrom: empty

postgresql:
  livenessProbe:
    initialDelaySeconds: 600

  image:
    repository: akvo/akvo-rsr-demo-postgres
    tag: 20190604.104919.c35d39d
  postgresqlUsername: postgres
  extraEnv:
    - name: ELEPHANTSQL_API_KEY
      valueFrom:
        secretKeyRef:
          name: "rsr-common"
          key: elephantsql-api-key
    - name: REPORTSERVER_USER_PASSWORD
      valueFrom:
        secretKeyRef:
          name: rsr-reportserver-training
          key: rs_db_password
    - name: REPORTSERVER_DB_USER
      valueFrom:
        secretKeyRef:
          name: rsr-reportserver-training
          key: rs_db_user
    - name: REPORTSERVER_DB_NAME
      valueFrom:
        secretKeyRef:
          name: rsr-reportserver-training
          key: rs_db_name
    - name: ENCRYPTED_RSR_PASSWORD
      valueFrom:
        secretKeyRef:
          name: rsr-reportserver-training
          key: rs_rsr_db_encrypted_password
  initdbScriptsConfigMap: "{{ include \"rsrchart.fullname\" . }}-seed-db"