
ASSET_BUNDLES = {
    'akvo_style': {
        'type': 'css',
        'path': 'akvo/css/',
        'compress': True,
        'files': [
            'reset.css',
            'grid.css',
            'typography.css',
            'base.css',
            'main_nav.css',
            'utils.css',
            'project_directory.css', 
            'column.css',
            'project.css',
            'tabs.css',
            'buttons.css',
            'machinery.css',
            'donate.css',
            'org.css',
            'index.css',
            'jquery-ui-1.8.5.custom.css',
            ],
    },
    'akvo_script': {
        'type': 'js',
        'path': 'akvo/js/',
        'compress': True,
        'files': [
            'galleria.1.1.95.js',
        ],
    },
    'akvo_ie6_style': {
        'type': 'css',
        'path': 'akvo/css/',
        'compress': True,
        'files': ['ie6.css',],
    },
    'akvo_machinery_js': {
        'type': 'js',
        'path': 'akvo/js/',
        'compress': True,
        'files': ['x_machinery.js', 'x_modernizr.js','x_utilities.js'],
    },
    'dws_style': {
        'type': 'css',
        'path': 'dws/css/',
        'compress': False,
        'files': [
            'reset.css',
            'grid.css',
            'utils.css',
            'typography.css',
            'base.css',
            'main_nav.css',
            'buttons.css',
            'index.css',
            'project_main.css',
            'project_directory.css',
            'project_updates.css',
            'thumbs_scroller.css',
            'tabs.css',
            'jquery-ui-1.8.4.custom.css',
            ],
    },
    'dws_style14': { # compatibility mode for previous 14 column grid
        'type': 'css',
        'path': 'dws/css/',
        'compress': False,
        'files': [
            'reset.css',
            'grid14.css',
            'utils.css',
            'typography.css',
            'base.css',
            'main_nav.css',
            'buttons.css',
            'index.css',
            'project_main.css',
            'project_directory.css',
            'project_updates.css',
            'thumbs_scroller.css',
            'tabs.css',
            'jquery-ui-1.8.4.custom.css',
            ],
    },
    'dws_ie6_style': {
        'type': 'css',
        'path': 'dws/css/',
        'compress': False,
        'files': ['ie6.css',],
    },    
    'widget_cobranded_banner': {
        'type': 'css',
        'path': 'widgets/cobranded_banner/css/',
        'compress': True,
        'files': ['x_reset.css','x_typography.css', 'x_grid.css', 'x_forms.css','../../../base/css/src/widget_global_horizontal.css','x_widget_cobranded_banner.css',],
    },
    'widget_cobranded_leader': {
        'type': 'css',
        'path': 'widgets/cobranded_leader/css/',
        'compress': True,
        'files': ['x_reset.css','x_typography.css', 'x_grid.css', 'x_forms.css','../../../base/css/src/widget_global_horizontal.css','x_widget_cobranded_leader.css',],
    },
    'widget_cobranded_narrow': {
        'type': 'css',
        'path': 'widgets/cobranded_narrow/css/',
        'compress': True,
        'files': ['x_reset.css','x_typography.css', 'x_grid.css', 'x_forms.css','../../../base/css/src/widget_global.css','x_widget_cobranded_narrow.css',],
    },
    'widget_cobranded_short': {
        'type': 'css',
        'path': 'widgets/cobranded_short/css/',
        'compress': True,
        'files': ['x_reset.css','x_typography.css', 'x_grid.css', 'x_forms.css','../../../base/css/src/widget_global.css','x_widget_cobranded_short.css',],
    },
    'widget_project': {
        'type': 'css',
        'path': 'widgets/project/css/',
        'compress': True,
        'files': ['x_reset.css','x_typography.css', 'x_grid.css', 'x_forms.css','x_widget_project.css','../../../base/css/src/widget_global.css',],
    },
    'widget_project_contribute': {
        'type': 'css',
        'path': 'widgets/project_contribute/css/',
        'compress': True,
        'files': ['x_reset.css','x_typography.css', 'x_grid.css', 'x_forms.css','x_widget_project_contribute.css','../../../base/css/src/widget_global.css',],
    },
    'widget_project_list': {
        'type': 'css',
        'path': 'widgets/project_list/css/',
        'compress': True,
        'files': ['x_reset.css','x_typography.css', 'x_grid.css', 'x_forms.css','x_widget_project_list.css','../../../base/css/src/widget_global.css',],
    },
    'widget_project_narrow': {
        'type': 'css',
        'path': 'widgets/project_narrow/css/',
        'compress': True,
        'files': ['x_reset.css','x_typography.css', 'x_grid.css', 'x_forms.css','x_widget_project_narrow.css','../../../base/css/src/widget_global.css',],
    },
    'widget_project_small': {
        'type': 'css',
        'path': 'widgets/project_small/css/',
        'compress': True,
        'files': ['x_reset.css','x_typography.css', 'x_grid.css', 'x_forms.css','x_widget_project_small.css','../../../base/css/src/widget_global.css',],
    },
    'widget_project_updates': {
        'type': 'css',
        'path': 'widgets/project_updates/css/',
        'compress': True,
        'files': ['x_reset.css','x_typography.css', 'x_grid.css', 'x_forms.css','x_widget_project_updates.css','../../../base/css/src/widget_global.css',],
    },
}