#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
ISO 3166 country names and their corresponding 3166-1-alpha-2 codes
"""
from django.utils.translation import ugettext as _

ISO_3166_COUNTRIES = (
    ("af", _(u"Afghanistan")),
    ("ax", _(u"Åland Islands")),
    ("al", _(u"Albania")),
    ("dz", _(u"Algeria")),
    ("as", _(u"American Samoa")),
    ("ad", _(u"Andorra")),
    ("ao", _(u"Angola")),
    ("ai", _(u"Anguilla")),
    ("aq", _(u"Antarctica")),
    ("ag", _(u"Antigua and Barbuda")),
    ("ar", _(u"Argentina")),
    ("am", _(u"Armenia")),
    ("aw", _(u"Aruba")),
    ("au", _(u"Australia")),
    ("at", _(u"Austria")),
    ("az", _(u"Azerbaijan")),
    ("bs", _(u"Bahamas")),
    ("bh", _(u"Bahrain")),
    ("bd", _(u"Bangladesh")),
    ("bb", _(u"Barbados")),
    ("by", _(u"Belarus")),
    ("be", _(u"Belgium")),
    ("bz", _(u"Belize")),
    ("bj", _(u"Benin")),
    ("bm", _(u"Bermuda")),
    ("bt", _(u"Bhutan")),
    ("bo", _(u"Bolivia, Plurinational State of")),
    ("bq", _(u"Bonaire, Sint Eustatius and Saba")),
    ("ba", _(u"Bosnia and Herzegovina")),
    ("bw", _(u"Botswana")),
    ("bv", _(u"Bouvet Island")),
    ("br", _(u"Brazil")),
    ("io", _(u"British Indian Ocean Territory")),
    ("bn", _(u"Brunei Darussalam")),
    ("bg", _(u"Bulgaria")),
    ("bf", _(u"Burkina Faso")),
    ("bi", _(u"Burundi")),
    ("kh", _(u"Cambodia")),
    ("cm", _(u"Cameroon")),
    ("ca", _(u"Canada")),
    ("cv", _(u"Cape Verde")),
    ("ky", _(u"Cayman Islands")),
    ("cf", _(u"Central African Republic")),
    ("td", _(u"Chad")),
    ("cl", _(u"Chile")),
    ("cn", _(u"China")),
    ("cx", _(u"Christmas Island")),
    ("cc", _(u"Cocos (keeling) Islands")),
    ("co", _(u"Colombia")),
    ("km", _(u"Comoros")),
    ("cg", _(u"Congo")),
    ("cd", _(u"Congo, The Democratic Republic of the")),
    ("ck", _(u"Cook Islands")),
    ("cr", _(u"Costa Rica")),
    ("ci", _(u"Côte D'ivoire")),
    ("hr", _(u"Croatia")),
    ("cu", _(u"Cuba")),
    ("cw", _(u"Curaçao")),
    ("cy", _(u"Cyprus")),
    ("cz", _(u"Czech Republic")),
    ("dk", _(u"Denmark")),
    ("dj", _(u"Djibouti")),
    ("dm", _(u"Dominica")),
    ("do", _(u"Dominican Republic")),
    ("ec", _(u"Ecuador")),
    ("eg", _(u"Egypt")),
    ("sv", _(u"El Salvador")),
    ("gq", _(u"Equatorial Guinea")),
    ("er", _(u"Eritrea")),
    ("ee", _(u"Estonia")),
    ("et", _(u"Ethiopia")),
    ("fk", _(u"Falkland Islands (Malvinas)")),
    ("fo", _(u"Faroe Islands")),
    ("fj", _(u"Fiji")),
    ("fi", _(u"Finland")),
    ("fr", _(u"France")),
    ("gf", _(u"French Guiana")),
    ("pf", _(u"French Polynesia")),
    ("tf", _(u"French Southern Territories")),
    ("ga", _(u"Gabon")),
    ("gm", _(u"Gambia")),
    ("ge", _(u"Georgia")),
    ("de", _(u"Germany")),
    ("gh", _(u"Ghana")),
    ("gi", _(u"Gibraltar")),
    ("gr", _(u"Greece")),
    ("gl", _(u"Greenland")),
    ("gd", _(u"Grenada")),
    ("gp", _(u"Guadeloupe")),
    ("gu", _(u"Guam")),
    ("gt", _(u"Guatemala")),
    ("gg", _(u"Guernsey")),
    ("gn", _(u"Guinea")),
    ("gw", _(u"Guinea-bissau")),
    ("gy", _(u"Guyana")),
    ("ht", _(u"Haiti")),
    ("hm", _(u"Heard Island and Mcdonald Islands")),
    ("va", _(u"Holy See (Vatican City State)")),
    ("hn", _(u"Honduras")),
    ("hk", _(u"Hong Kong")),
    ("hu", _(u"Hungary")),
    ("is", _(u"Iceland")),
    ("in", _(u"India")),
    ("id", _(u"Indonesia")),
    ("ir", _(u"Iran, Islamic Republic of")),
    ("iq", _(u"Iraq")),
    ("ie", _(u"Ireland")),
    ("im", _(u"Isle of Man")),
    ("il", _(u"Israel")),
    ("it", _(u"Italy")),
    ("jm", _(u"Jamaica")),
    ("jp", _(u"Japan")),
    ("je", _(u"Jersey")),
    ("jo", _(u"Jordan")),
    ("kz", _(u"Kazakhstan")),
    ("ke", _(u"Kenya")),
    ("ki", _(u"Kiribati")),
    ("kp", _(u"Korea, Democratic People's Republic of")),
    ("kr", _(u"Korea, Republic of")),
    ("kw", _(u"Kuwait")),
    ("kg", _(u"Kyrgyzstan")),
    ("la", _(u"Lao People's Democratic Republic")),
    ("lv", _(u"Latvia")),
    ("lb", _(u"Lebanon")),
    ("ls", _(u"Lesotho")),
    ("lr", _(u"Liberia")),
    ("ly", _(u"Libyan Arab Jamahiriya")),
    ("li", _(u"Liechtenstein")),
    ("lt", _(u"Lithuania")),
    ("lu", _(u"Luxembourg")),
    ("mo", _(u"Macao")),
    ("mk", _(u"Macedonia, The Former Yugoslav Republic of")),
    ("mg", _(u"Madagascar")),
    ("mw", _(u"Malawi")),
    ("my", _(u"Malaysia")),
    ("mv", _(u"Maldives")),
    ("ml", _(u"Mali")),
    ("mt", _(u"Malta")),
    ("mh", _(u"Marshall Islands")),
    ("mq", _(u"Martinique")),
    ("mr", _(u"Mauritania")),
    ("mu", _(u"Mauritius")),
    ("yt", _(u"Mayotte")),
    ("mx", _(u"Mexico")),
    ("fm", _(u"Micronesia, Federated States of")),
    ("md", _(u"Moldova, Republic of")),
    ("mc", _(u"Monaco")),
    ("mn", _(u"Mongolia")),
    ("me", _(u"Montenegro")),
    ("ms", _(u"Montserrat")),
    ("ma", _(u"Morocco")),
    ("mz", _(u"Mozambique")),
    ("mm", _(u"Myanmar")),
    ("na", _(u"Namibia")),
    ("nr", _(u"Nauru")),
    ("np", _(u"Nepal")),
    ("nl", _(u"Netherlands")),
    ("nc", _(u"New Caledonia")),
    ("nz", _(u"New Zealand")),
    ("ni", _(u"Nicaragua")),
    ("ne", _(u"Niger")),
    ("ng", _(u"Nigeria")),
    ("nu", _(u"Niue")),
    ("nf", _(u"Norfolk Island")),
    ("mp", _(u"Northern Mariana Islands")),
    ("no", _(u"Norway")),
    ("om", _(u"Oman")),
    ("pk", _(u"Pakistan")),
    ("pw", _(u"Palau")),
    ("ps", _(u"Palestinian Territory, Occupied")),
    ("pa", _(u"Panama")),
    ("pg", _(u"Papua New Guinea")),
    ("py", _(u"Paraguay")),
    ("pe", _(u"Peru")),
    ("ph", _(u"Philippines")),
    ("pn", _(u"Pitcairn")),
    ("pl", _(u"Poland")),
    ("pt", _(u"Portugal")),
    ("pr", _(u"Puerto Rico")),
    ("qa", _(u"Qatar")),
    ("re", _(u"Réunion")),
    ("ro", _(u"Romania")),
    ("ru", _(u"Russian Federation")),
    ("rw", _(u"Rwanda")),
    ("bl", _(u"Saint Barthélemy")),
    ("sh", _(u"Saint Helena, Ascension and Tristan Da Cunha")),
    ("kn", _(u"Saint Kitts and Nevis")),
    ("lc", _(u"Saint Lucia")),
    ("mf", _(u"Saint Martin (French part)")),
    ("pm", _(u"Saint Pierre and Miquelon")),
    ("vc", _(u"Saint Vincent and the Grenadines")),
    ("ws", _(u"Samoa")),
    ("sm", _(u"San Marino")),
    ("st", _(u"Sao Tome and Principe")),
    ("sa", _(u"Saudi Arabia")),
    ("sn", _(u"Senegal")),
    ("rs", _(u"Serbia")),
    ("sc", _(u"Seychelles")),
    ("sl", _(u"Sierra Leone")),
    ("sg", _(u"Singapore")),
    ("sx", _(u"Sint Maarten (Dutch part)")),
    ("sk", _(u"Slovakia")),
    ("si", _(u"Slovenia")),
    ("sb", _(u"Solomon Islands")),
    ("so", _(u"Somalia")),
    ("za", _(u"South Africa")),
    ("gs", _(u"South Georgia and the South Sandwich Islands")),
    ("ss", _(u"South Sudan")),
    ("es", _(u"Spain")),
    ("lk", _(u"Sri Lanka")),
    ("sd", _(u"Sudan")),
    ("sr", _(u"Suriname")),
    ("sj", _(u"Svalbard and Jan Mayen")),
    ("sz", _(u"Swaziland")),
    ("se", _(u"Sweden")),
    ("ch", _(u"Switzerland")),
    ("sy", _(u"Syrian Arab Republic")),
    ("tw", _(u"Taiwan, Province of China")),
    ("tj", _(u"Tajikistan")),
    ("tz", _(u"Tanzania, United Republic of")),
    ("th", _(u"Thailand")),
    ("tl", _(u"Timor-leste")),
    ("tg", _(u"Togo")),
    ("tk", _(u"Tokelau")),
    ("to", _(u"Tonga")),
    ("tt", _(u"Trinidad and Tobago")),
    ("tn", _(u"Tunisia")),
    ("tr", _(u"Turkey")),
    ("tm", _(u"Turkmenistan")),
    ("tc", _(u"Turks and Caicos Islands")),
    ("tv", _(u"Tuvalu")),
    ("ug", _(u"Uganda")),
    ("ua", _(u"Ukraine")),
    ("ae", _(u"United Arab Emirates")),
    ("gb", _(u"United Kingdom")),
    ("us", _(u"United States")),
    ("um", _(u"United States Minor Outlying Islands")),
    ("uy", _(u"Uruguay")),
    ("uz", _(u"Uzbekistan")),
    ("vu", _(u"Vanuatu")),
    ("ve", _(u"Venezuela, Bolivarian Republic of")),
    ("vn", _(u"Viet Nam")),
    ("vg", _(u"Virgin Islands, British")),
    ("vi", _(u"Virgin Islands, U.S.")),
    ("wf", _(u"Wallis and Futuna")),
    ("eh", _(u"Western Sahara")),
    ("ye", _(u"Yemen")),
    ("zm", _(u"Zambia")),
    ("zw", _(u"Zimbabwe")),
)

COUNTRY_CONTINENTS = {
    'ad': 'eu',
    'ae': 'as',
    'af': 'as',
    'ag': 'na',
    'ai': 'na',
    'al': 'eu',
    'am': 'as',
    'an': 'na',
    'ao': 'af',
    'ap': 'as',
    'aq': 'an',
    'ar': 'sa',
    'as': 'oc',
    'at': 'eu',
    'au': 'oc',
    'aw': 'na',
    'ax': 'eu',
    'az': 'as',
    'ba': 'eu',
    'bb': 'na',
    'bd': 'as',
    'be': 'eu',
    'bf': 'af',
    'bg': 'eu',
    'bh': 'as',
    'bi': 'af',
    'bj': 'af',
    'bl': 'na',
    'bm': 'na',
    'bn': 'as',
    'bo': 'sa',
    'br': 'sa',
    'bs': 'na',
    'bt': 'as',
    'bv': 'an',
    'bw': 'af',
    'by': 'eu',
    'bz': 'na',
    'ca': 'na',
    'cc': 'as',
    'cd': 'af',
    'cf': 'af',
    'cg': 'af',
    'ch': 'eu',
    'ci': 'af',
    'ck': 'oc',
    'cl': 'sa',
    'cm': 'af',
    'cn': 'as',
    'co': 'sa',
    'cr': 'na',
    'cu': 'na',
    'cv': 'af',
    'cx': 'as',
    'cy': 'as',
    'cz': 'eu',
    'de': 'eu',
    'dj': 'af',
    'dk': 'eu',
    'dm': 'na',
    'do': 'na',
    'dz': 'af',
    'ec': 'sa',
    'ee': 'eu',
    'eg': 'af',
    'eh': 'af',
    'er': 'af',
    'es': 'eu',
    'et': 'af',
    'eu': 'eu',
    'fi': 'eu',
    'fj': 'oc',
    'fk': 'sa',
    'fm': 'oc',
    'fo': 'eu',
    'fr': 'eu',
    'fx': 'eu',
    'ga': 'af',
    'gb': 'eu',
    'gd': 'na',
    'ge': 'as',
    'gf': 'sa',
    'gg': 'eu',
    'gh': 'af',
    'gi': 'eu',
    'gl': 'na',
    'gm': 'af',
    'gn': 'af',
    'gp': 'na',
    'gq': 'af',
    'gr': 'eu',
    'gs': 'an',
    'gt': 'na',
    'gu': 'oc',
    'gw': 'af',
    'gy': 'sa',
    'hk': 'as',
    'hm': 'an',
    'hn': 'na',
    'hr': 'eu',
    'ht': 'na',
    'hu': 'eu',
    'id': 'as',
    'ie': 'eu',
    'il': 'as',
    'im': 'eu',
    'in': 'as',
    'io': 'as',
    'iq': 'as',
    'ir': 'as',
    'is': 'eu',
    'it': 'eu',
    'je': 'eu',
    'jm': 'na',
    'jo': 'as',
    'jp': 'as',
    'ke': 'af',
    'kg': 'as',
    'kh': 'as',
    'ki': 'oc',
    'km': 'af',
    'kn': 'na',
    'kp': 'as',
    'kr': 'as',
    'kw': 'as',
    'ky': 'na',
    'kz': 'as',
    'la': 'as',
    'lb': 'as',
    'lc': 'na',
    'li': 'eu',
    'lk': 'as',
    'lr': 'af',
    'ls': 'af',
    'lt': 'eu',
    'lu': 'eu',
    'lv': 'eu',
    'ly': 'af',
    'ma': 'af',
    'mc': 'eu',
    'md': 'eu',
    'me': 'eu',
    'mf': 'na',
    'mg': 'af',
    'mh': 'oc',
    'mk': 'eu',
    'ml': 'af',
    'mm': 'as',
    'mn': 'as',
    'mo': 'as',
    'mp': 'oc',
    'mq': 'na',
    'mr': 'af',
    'ms': 'na',
    'mt': 'eu',
    'mu': 'af',
    'mv': 'as',
    'mw': 'af',
    'mx': 'na',
    'my': 'as',
    'mz': 'af',
    'na': 'af',
    'nc': 'oc',
    'ne': 'af',
    'nf': 'oc',
    'ng': 'af',
    'ni': 'na',
    'nl': 'eu',
    'no': 'eu',
    'np': 'as',
    'nr': 'oc',
    'nu': 'oc',
    'nz': 'oc',
    'o1': '--',
    'om': 'as',
    'pa': 'na',
    'pe': 'sa',
    'pf': 'oc',
    'pg': 'oc',
    'ph': 'as',
    'pk': 'as',
    'pl': 'eu',
    'pm': 'na',
    'pn': 'oc',
    'pr': 'na',
    'ps': 'as',
    'pt': 'eu',
    'pw': 'oc',
    'py': 'sa',
    'qa': 'as',
    're': 'af',
    'ro': 'eu',
    'rs': 'eu',
    'ru': 'eu',
    'rw': 'af',
    'sa': 'as',
    'sb': 'oc',
    'sc': 'af',
    'sd': 'af',
    'se': 'eu',
    'sg': 'as',
    'sh': 'af',
    'si': 'eu',
    'sj': 'eu',
    'sk': 'eu',
    'sl': 'af',
    'sm': 'eu',
    'sn': 'af',
    'so': 'af',
    'sr': 'sa',
    'st': 'af',
    'sv': 'na',
    'sy': 'as',
    'sz': 'af',
    'tc': 'na',
    'td': 'af',
    'tf': 'an',
    'tg': 'af',
    'th': 'as',
    'tj': 'as',
    'tk': 'oc',
    'tl': 'as',
    'tm': 'as',
    'tn': 'af',
    'to': 'oc',
    'tr': 'eu',
    'tt': 'na',
    'tv': 'oc',
    'tw': 'as',
    'tz': 'af',
    'ua': 'eu',
    'ug': 'af',
    'um': 'oc',
    'us': 'na',
    'uy': 'sa',
    'uz': 'as',
    'va': 'eu',
    'vc': 'na',
    've': 'sa',
    'vg': 'na',
    'vi': 'na',
    'vn': 'as',
    'vu': 'oc',
    'wf': 'oc',
    'ws': 'oc',
    'ye': 'as',
    'yt': 'af',
    'za': 'af',
    'zm': 'af',
    'zw': 'af',
}

CONTINENTS = (
    ("af", _(u"Africa")),
    ("as", _(u"Asia")),
    ("eu", _(u"Europe")),
    ("na", _(u"North America")),
    ("sa", _(u"South America")),
    ("oc", _(u"Oceania")),
    ("an", _(u"Antarctica")),
)
