#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Akvo RSR is covered by the GNU Affero General Public License. See more
# details in the license.txt file located at the root folder of the Akvo RSR
# module. For additional details on the GNU license please see
# <http://www.gnu.org/licenses/agpl.html>.

"""ISO 3166 country names and their corresponding 3166-1-alpha-2 codes."""

from django.utils.translation import ugettext_lazy as _

ISO_3166_COUNTRIES = (
    ("af", _("Afghanistan")),
    ("ax", _("Åland Islands")),
    ("al", _("Albania")),
    ("dz", _("Algeria")),
    ("as", _("American Samoa")),
    ("ad", _("Andorra")),
    ("ao", _("Angola")),
    ("ai", _("Anguilla")),
    ("aq", _("Antarctica")),
    ("ag", _("Antigua and Barbuda")),
    ("ar", _("Argentina")),
    ("am", _("Armenia")),
    ("aw", _("Aruba")),
    ("au", _("Australia")),
    ("at", _("Austria")),
    ("az", _("Azerbaijan")),
    ("bs", _("Bahamas")),
    ("bh", _("Bahrain")),
    ("bd", _("Bangladesh")),
    ("bb", _("Barbados")),
    ("by", _("Belarus")),
    ("be", _("Belgium")),
    ("bz", _("Belize")),
    ("bj", _("Benin")),
    ("bm", _("Bermuda")),
    ("bt", _("Bhutan")),
    ("bo", _("Bolivia, Plurinational State of")),
    ("bq", _("Bonaire, Sint Eustatius and Saba")),
    ("ba", _("Bosnia and Herzegovina")),
    ("bw", _("Botswana")),
    ("bv", _("Bouvet Island")),
    ("br", _("Brazil")),
    ("io", _("British Indian Ocean Territory")),
    ("bn", _("Brunei Darussalam")),
    ("bg", _("Bulgaria")),
    ("bf", _("Burkina Faso")),
    ("bi", _("Burundi")),
    ("kh", _("Cambodia")),
    ("cm", _("Cameroon")),
    ("ca", _("Canada")),
    ("cv", _("Cape Verde")),
    ("ky", _("Cayman Islands")),
    ("cf", _("Central African Republic")),
    ("td", _("Chad")),
    ("cl", _("Chile")),
    ("cn", _("China")),
    ("cx", _("Christmas Island")),
    ("cc", _("Cocos (keeling) Islands")),
    ("co", _("Colombia")),
    ("km", _("Comoros")),
    ("cg", _("Congo")),
    ("cd", _("Congo, The Democratic Republic of the")),
    ("ck", _("Cook Islands")),
    ("cr", _("Costa Rica")),
    ("ci", _("Côte D'ivoire")),
    ("hr", _("Croatia")),
    ("cu", _("Cuba")),
    ("cw", _("Curaçao")),
    ("cy", _("Cyprus")),
    ("cz", _("Czech Republic")),
    ("dk", _("Denmark")),
    ("dj", _("Djibouti")),
    ("dm", _("Dominica")),
    ("do", _("Dominican Republic")),
    ("ec", _("Ecuador")),
    ("eg", _("Egypt")),
    ("sv", _("El Salvador")),
    ("gq", _("Equatorial Guinea")),
    ("er", _("Eritrea")),
    ("ee", _("Estonia")),
    ("et", _("Ethiopia")),
    ("fk", _("Falkland Islands (Malvinas)")),
    ("fo", _("Faroe Islands")),
    ("fj", _("Fiji")),
    ("fi", _("Finland")),
    ("fr", _("France")),
    ("gf", _("French Guiana")),
    ("pf", _("French Polynesia")),
    ("tf", _("French Southern Territories")),
    ("ga", _("Gabon")),
    ("gm", _("Gambia")),
    ("ge", _("Georgia")),
    ("de", _("Germany")),
    ("gh", _("Ghana")),
    ("gi", _("Gibraltar")),
    ("gr", _("Greece")),
    ("gl", _("Greenland")),
    ("gd", _("Grenada")),
    ("gp", _("Guadeloupe")),
    ("gu", _("Guam")),
    ("gt", _("Guatemala")),
    ("gg", _("Guernsey")),
    ("gn", _("Guinea")),
    ("gw", _("Guinea-bissau")),
    ("gy", _("Guyana")),
    ("ht", _("Haiti")),
    ("hm", _("Heard Island and Mcdonald Islands")),
    ("va", _("Holy See (Vatican City State)")),
    ("hn", _("Honduras")),
    ("hk", _("Hong Kong")),
    ("hu", _("Hungary")),
    ("is", _("Iceland")),
    ("in", _("India")),
    ("id", _("Indonesia")),
    ("ir", _("Iran, Islamic Republic of")),
    ("iq", _("Iraq")),
    ("ie", _("Ireland")),
    ("im", _("Isle of Man")),
    ("il", _("Israel")),
    ("it", _("Italy")),
    ("jm", _("Jamaica")),
    ("jp", _("Japan")),
    ("je", _("Jersey")),
    ("jo", _("Jordan")),
    ("kz", _("Kazakhstan")),
    ("ke", _("Kenya")),
    ("ki", _("Kiribati")),
    ("kp", _("Korea, Democratic People's Republic of")),
    ("kr", _("Korea, Republic of")),
    ("xk", _("Kosovo")),
    ("kw", _("Kuwait")),
    ("kg", _("Kyrgyzstan")),
    ("la", _("Lao People's Democratic Republic")),
    ("lv", _("Latvia")),
    ("lb", _("Lebanon")),
    ("ls", _("Lesotho")),
    ("lr", _("Liberia")),
    ("ly", _("Libyan Arab Jamahiriya")),
    ("li", _("Liechtenstein")),
    ("lt", _("Lithuania")),
    ("lu", _("Luxembourg")),
    ("mo", _("Macao")),
    ("mk", _("Macedonia, The Former Yugoslav Republic of")),
    ("mg", _("Madagascar")),
    ("mw", _("Malawi")),
    ("my", _("Malaysia")),
    ("mv", _("Maldives")),
    ("ml", _("Mali")),
    ("mt", _("Malta")),
    ("mh", _("Marshall Islands")),
    ("mq", _("Martinique")),
    ("mr", _("Mauritania")),
    ("mu", _("Mauritius")),
    ("yt", _("Mayotte")),
    ("mx", _("Mexico")),
    ("fm", _("Micronesia, Federated States of")),
    ("md", _("Moldova, Republic of")),
    ("mc", _("Monaco")),
    ("mn", _("Mongolia")),
    ("me", _("Montenegro")),
    ("ms", _("Montserrat")),
    ("ma", _("Morocco")),
    ("mz", _("Mozambique")),
    ("mm", _("Myanmar")),
    ("na", _("Namibia")),
    ("nr", _("Nauru")),
    ("np", _("Nepal")),
    ("nl", _("Netherlands")),
    ("nc", _("New Caledonia")),
    ("nz", _("New Zealand")),
    ("ni", _("Nicaragua")),
    ("ne", _("Niger")),
    ("ng", _("Nigeria")),
    ("nu", _("Niue")),
    ("nf", _("Norfolk Island")),
    ("mp", _("Northern Mariana Islands")),
    ("no", _("Norway")),
    ("om", _("Oman")),
    ("pk", _("Pakistan")),
    ("pw", _("Palau")),
    ("ps", _("Palestine, State of")),
    ("pa", _("Panama")),
    ("pg", _("Papua New Guinea")),
    ("py", _("Paraguay")),
    ("pe", _("Peru")),
    ("ph", _("Philippines")),
    ("pn", _("Pitcairn")),
    ("pl", _("Poland")),
    ("pt", _("Portugal")),
    ("pr", _("Puerto Rico")),
    ("qa", _("Qatar")),
    ("re", _("Réunion")),
    ("ro", _("Romania")),
    ("ru", _("Russian Federation")),
    ("rw", _("Rwanda")),
    ("bl", _("Saint Barthélemy")),
    ("sh", _("Saint Helena, Ascension and Tristan Da Cunha")),
    ("kn", _("Saint Kitts and Nevis")),
    ("lc", _("Saint Lucia")),
    ("mf", _("Saint Martin (French part)")),
    ("pm", _("Saint Pierre and Miquelon")),
    ("vc", _("Saint Vincent and the Grenadines")),
    ("ws", _("Samoa")),
    ("sm", _("San Marino")),
    ("st", _("Sao Tome and Principe")),
    ("sa", _("Saudi Arabia")),
    ("sn", _("Senegal")),
    ("rs", _("Serbia")),
    ("sc", _("Seychelles")),
    ("sl", _("Sierra Leone")),
    ("sg", _("Singapore")),
    ("sx", _("Sint Maarten (Dutch part)")),
    ("sk", _("Slovakia")),
    ("si", _("Slovenia")),
    ("sb", _("Solomon Islands")),
    ("so", _("Somalia")),
    ("za", _("South Africa")),
    ("gs", _("South Georgia and the South Sandwich Islands")),
    ("ss", _("South Sudan")),
    ("es", _("Spain")),
    ("lk", _("Sri Lanka")),
    ("sd", _("Sudan")),
    ("sr", _("Suriname")),
    ("sj", _("Svalbard and Jan Mayen")),
    ("sz", _("Swaziland")),
    ("se", _("Sweden")),
    ("ch", _("Switzerland")),
    ("sy", _("Syrian Arab Republic")),
    ("tw", _("Taiwan, Province of China")),
    ("tj", _("Tajikistan")),
    ("tz", _("Tanzania, United Republic of")),
    ("th", _("Thailand")),
    ("tl", _("Timor-leste")),
    ("tg", _("Togo")),
    ("tk", _("Tokelau")),
    ("to", _("Tonga")),
    ("tt", _("Trinidad and Tobago")),
    ("tn", _("Tunisia")),
    ("tr", _("Turkey")),
    ("tm", _("Turkmenistan")),
    ("tc", _("Turks and Caicos Islands")),
    ("tv", _("Tuvalu")),
    ("ug", _("Uganda")),
    ("ua", _("Ukraine")),
    ("ae", _("United Arab Emirates")),
    ("gb", _("United Kingdom")),
    ("us", _("United States")),
    ("um", _("United States Minor Outlying Islands")),
    ("uy", _("Uruguay")),
    ("uz", _("Uzbekistan")),
    ("vu", _("Vanuatu")),
    ("ve", _("Venezuela, Bolivarian Republic of")),
    ("vn", _("Vietnam")),
    ("vg", _("Virgin Islands, British")),
    ("vi", _("Virgin Islands, U.S.")),
    ("wf", _("Wallis and Futuna")),
    ("eh", _("Western Sahara")),
    ("ye", _("Yemen")),
    ("zm", _("Zambia")),
    ("zw", _("Zimbabwe")),
)

COUNTRY_CONTINENTS = {
    'ad': 'eu',
    'ae': 'as',
    'af': 'as',
    'ag': 'na',
    'ai': 'na',
    'al': 'eu',
    'am': 'as',
    'an': 'na',
    'ao': 'af',
    'ap': 'as',
    'aq': 'an',
    'ar': 'sa',
    'as': 'oc',
    'at': 'eu',
    'au': 'oc',
    'aw': 'na',
    'ax': 'eu',
    'az': 'as',
    'ba': 'eu',
    'bb': 'na',
    'bd': 'as',
    'be': 'eu',
    'bf': 'af',
    'bg': 'eu',
    'bh': 'as',
    'bi': 'af',
    'bj': 'af',
    'bl': 'na',
    'bm': 'na',
    'bn': 'as',
    'bo': 'sa',
    'bq': 'na',
    'br': 'sa',
    'bs': 'na',
    'bt': 'as',
    'bv': 'an',
    'bw': 'af',
    'by': 'eu',
    'bz': 'na',
    'ca': 'na',
    'cc': 'as',
    'cd': 'af',
    'cf': 'af',
    'cg': 'af',
    'ch': 'eu',
    'ci': 'af',
    'ck': 'oc',
    'cl': 'sa',
    'cm': 'af',
    'cn': 'as',
    'co': 'sa',
    'cr': 'na',
    'cu': 'na',
    'cv': 'af',
    'cx': 'as',
    'cw': 'sa',
    'cy': 'as',
    'cz': 'eu',
    'de': 'eu',
    'dj': 'af',
    'dk': 'eu',
    'dm': 'na',
    'do': 'na',
    'dz': 'af',
    'ec': 'sa',
    'ee': 'eu',
    'eg': 'af',
    'eh': 'af',
    'er': 'af',
    'es': 'eu',
    'et': 'af',
    'eu': 'eu',
    'fi': 'eu',
    'fj': 'oc',
    'fk': 'sa',
    'fm': 'oc',
    'fo': 'eu',
    'fr': 'eu',
    'fx': 'eu',
    'ga': 'af',
    'gb': 'eu',
    'gd': 'na',
    'ge': 'as',
    'gf': 'sa',
    'gg': 'eu',
    'gh': 'af',
    'gi': 'eu',
    'gl': 'na',
    'gm': 'af',
    'gn': 'af',
    'gp': 'na',
    'gq': 'af',
    'gr': 'eu',
    'gs': 'an',
    'gt': 'na',
    'gu': 'oc',
    'gw': 'af',
    'gy': 'sa',
    'hk': 'as',
    'hm': 'an',
    'hn': 'na',
    'hr': 'eu',
    'ht': 'na',
    'hu': 'eu',
    'id': 'as',
    'ie': 'eu',
    'il': 'as',
    'im': 'eu',
    'in': 'as',
    'io': 'as',
    'iq': 'as',
    'ir': 'as',
    'is': 'eu',
    'it': 'eu',
    'je': 'eu',
    'jm': 'na',
    'jo': 'as',
    'jp': 'as',
    'ke': 'af',
    'kg': 'as',
    'kh': 'as',
    'ki': 'oc',
    'km': 'af',
    'kn': 'na',
    'kp': 'as',
    'kr': 'as',
    'kw': 'as',
    'ky': 'na',
    'kz': 'as',
    'la': 'as',
    'lb': 'as',
    'lc': 'na',
    'li': 'eu',
    'lk': 'as',
    'lr': 'af',
    'ls': 'af',
    'lt': 'eu',
    'lu': 'eu',
    'lv': 'eu',
    'ly': 'af',
    'ma': 'af',
    'mc': 'eu',
    'md': 'eu',
    'me': 'eu',
    'mf': 'na',
    'mg': 'af',
    'mh': 'oc',
    'mk': 'eu',
    'ml': 'af',
    'mm': 'as',
    'mn': 'as',
    'mo': 'as',
    'mp': 'oc',
    'mq': 'na',
    'mr': 'af',
    'ms': 'na',
    'mt': 'eu',
    'mu': 'af',
    'mv': 'as',
    'mw': 'af',
    'mx': 'na',
    'my': 'as',
    'mz': 'af',
    'na': 'af',
    'nc': 'oc',
    'ne': 'af',
    'nf': 'oc',
    'ng': 'af',
    'ni': 'na',
    'nl': 'eu',
    'no': 'eu',
    'np': 'as',
    'nr': 'oc',
    'nu': 'oc',
    'nz': 'oc',
    'o1': '--',
    'om': 'as',
    'pa': 'na',
    'pe': 'sa',
    'pf': 'oc',
    'pg': 'oc',
    'ph': 'as',
    'pk': 'as',
    'pl': 'eu',
    'pm': 'na',
    'pn': 'oc',
    'pr': 'na',
    'ps': 'as',
    'pt': 'eu',
    'pw': 'oc',
    'py': 'sa',
    'qa': 'as',
    're': 'af',
    'ro': 'eu',
    'rs': 'eu',
    'ru': 'eu',
    'rw': 'af',
    'sa': 'as',
    'sb': 'oc',
    'sc': 'af',
    'sd': 'af',
    'se': 'eu',
    'sg': 'as',
    'sh': 'af',
    'si': 'eu',
    'sj': 'eu',
    'sk': 'eu',
    'sx': 'na',
    'sl': 'af',
    'sm': 'eu',
    'sn': 'af',
    'so': 'af',
    'sr': 'sa',
    'ss': 'af',
    'st': 'af',
    'sv': 'na',
    'sy': 'as',
    'sz': 'af',
    'tc': 'na',
    'td': 'af',
    'tf': 'an',
    'tg': 'af',
    'th': 'as',
    'tj': 'as',
    'tk': 'oc',
    'tl': 'as',
    'tm': 'as',
    'tn': 'af',
    'to': 'oc',
    'tr': 'eu',
    'tt': 'na',
    'tv': 'oc',
    'tw': 'as',
    'tz': 'af',
    'ua': 'eu',
    'ug': 'af',
    'um': 'oc',
    'us': 'na',
    'uy': 'sa',
    'uz': 'as',
    'va': 'eu',
    'vc': 'na',
    've': 'sa',
    'vg': 'na',
    'vi': 'na',
    'vn': 'as',
    'vu': 'oc',
    'wf': 'oc',
    'ws': 'oc',
    'xk': 'eu',
    'ye': 'as',
    'yt': 'af',
    'za': 'af',
    'zm': 'af',
    'zw': 'af',
}

CONTINENTS = (
    ("af", _("Africa")),
    ("as", _("Asia")),
    ("eu", _("Europe")),
    ("na", _("North America")),
    ("sa", _("South America")),
    ("oc", _("Oceania")),
    ("an", _("Antarctica")),
)


# Obtained from http://download.geonames.org/export/dump/countryInfo.txt
ISO_ALPHA3_ALPHA2_MAP = {
    'ABW': 'AW',
    'AFG': 'AF',
    'AGO': 'AO',
    'AIA': 'AI',
    'ALA': 'AX',
    'ALB': 'AL',
    'AND': 'AD',
    'ANT': 'AN',
    'ARE': 'AE',
    'ARG': 'AR',
    'ARM': 'AM',
    'ASM': 'AS',
    'ATA': 'AQ',
    'ATF': 'TF',
    'ATG': 'AG',
    'AUS': 'AU',
    'AUT': 'AT',
    'AZE': 'AZ',
    'BDI': 'BI',
    'BEL': 'BE',
    'BEN': 'BJ',
    'BES': 'BQ',
    'BFA': 'BF',
    'BGD': 'BD',
    'BGR': 'BG',
    'BHR': 'BH',
    'BHS': 'BS',
    'BIH': 'BA',
    'BLM': 'BL',
    'BLR': 'BY',
    'BLZ': 'BZ',
    'BMU': 'BM',
    'BOL': 'BO',
    'BRA': 'BR',
    'BRB': 'BB',
    'BRN': 'BN',
    'BTN': 'BT',
    'BVT': 'BV',
    'BWA': 'BW',
    'CAF': 'CF',
    'CAN': 'CA',
    'CCK': 'CC',
    'CHE': 'CH',
    'CHL': 'CL',
    'CHN': 'CN',
    'CIV': 'CI',
    'CMR': 'CM',
    'COD': 'CD',
    'COG': 'CG',
    'COK': 'CK',
    'COL': 'CO',
    'COM': 'KM',
    'CPV': 'CV',
    'CRI': 'CR',
    'CUB': 'CU',
    'CUW': 'CW',
    'CXR': 'CX',
    'CYM': 'KY',
    'CYP': 'CY',
    'CZE': 'CZ',
    'DEU': 'DE',
    'DJI': 'DJ',
    'DMA': 'DM',
    'DNK': 'DK',
    'DOM': 'DO',
    'DZA': 'DZ',
    'ECU': 'EC',
    'EGY': 'EG',
    'ERI': 'ER',
    'ESH': 'EH',
    'ESP': 'ES',
    'EST': 'EE',
    'ETH': 'ET',
    'FIN': 'FI',
    'FJI': 'FJ',
    'FLK': 'FK',
    'FRA': 'FR',
    'FRO': 'FO',
    'FSM': 'FM',
    'GAB': 'GA',
    'GBR': 'GB',
    'GEO': 'GE',
    'GGY': 'GG',
    'GHA': 'GH',
    'GIB': 'GI',
    'GIN': 'GN',
    'GLP': 'GP',
    'GMB': 'GM',
    'GNB': 'GW',
    'GNQ': 'GQ',
    'GRC': 'GR',
    'GRD': 'GD',
    'GRL': 'GL',
    'GTM': 'GT',
    'GUF': 'GF',
    'GUM': 'GU',
    'GUY': 'GY',
    'HKG': 'HK',
    'HMD': 'HM',
    'HND': 'HN',
    'HRV': 'HR',
    'HTI': 'HT',
    'HUN': 'HU',
    'IDN': 'ID',
    'IMN': 'IM',
    'IND': 'IN',
    'IOT': 'IO',
    'IRL': 'IE',
    'IRN': 'IR',
    'IRQ': 'IQ',
    'ISL': 'IS',
    'ISR': 'IL',
    'ITA': 'IT',
    'JAM': 'JM',
    'JEY': 'JE',
    'JOR': 'JO',
    'JPN': 'JP',
    'KAZ': 'KZ',
    'KEN': 'KE',
    'KGZ': 'KG',
    'KHM': 'KH',
    'KIR': 'KI',
    'KNA': 'KN',
    'KOR': 'KR',
    'KWT': 'KW',
    'LAO': 'LA',
    'LBN': 'LB',
    'LBR': 'LR',
    'LBY': 'LY',
    'LCA': 'LC',
    'LIE': 'LI',
    'LKA': 'LK',
    'LSO': 'LS',
    'LTU': 'LT',
    'LUX': 'LU',
    'LVA': 'LV',
    'MAC': 'MO',
    'MAF': 'MF',
    'MAR': 'MA',
    'MCO': 'MC',
    'MDA': 'MD',
    'MDG': 'MG',
    'MDV': 'MV',
    'MEX': 'MX',
    'MHL': 'MH',
    'MKD': 'MK',
    'MLI': 'ML',
    'MLT': 'MT',
    'MMR': 'MM',
    'MNE': 'ME',
    'MNG': 'MN',
    'MNP': 'MP',
    'MOZ': 'MZ',
    'MRT': 'MR',
    'MSR': 'MS',
    'MTQ': 'MQ',
    'MUS': 'MU',
    'MWI': 'MW',
    'MYS': 'MY',
    'MYT': 'YT',
    'NAM': 'NA',
    'NCL': 'NC',
    'NER': 'NE',
    'NFK': 'NF',
    'NGA': 'NG',
    'NIC': 'NI',
    'NIU': 'NU',
    'NLD': 'NL',
    'NOR': 'NO',
    'NPL': 'NP',
    'NRU': 'NR',
    'NZL': 'NZ',
    'OMN': 'OM',
    'PAK': 'PK',
    'PAN': 'PA',
    'PCN': 'PN',
    'PER': 'PE',
    'PHL': 'PH',
    'PLW': 'PW',
    'PNG': 'PG',
    'POL': 'PL',
    'PRI': 'PR',
    'PRK': 'KP',
    'PRT': 'PT',
    'PRY': 'PY',
    'PSE': 'PS',
    'PYF': 'PF',
    'QAT': 'QA',
    'REU': 'RE',
    'ROU': 'RO',
    'RUS': 'RU',
    'RWA': 'RW',
    'SAU': 'SA',
    'SCG': 'CS',
    'SDN': 'SD',
    'SEN': 'SN',
    'SGP': 'SG',
    'SGS': 'GS',
    'SHN': 'SH',
    'SJM': 'SJ',
    'SLB': 'SB',
    'SLE': 'SL',
    'SLV': 'SV',
    'SMR': 'SM',
    'SOM': 'SO',
    'SPM': 'PM',
    'SRB': 'RS',
    'SSD': 'SS',
    'STP': 'ST',
    'SUR': 'SR',
    'SVK': 'SK',
    'SVN': 'SI',
    'SWE': 'SE',
    'SWZ': 'SZ',
    'SXM': 'SX',
    'SYC': 'SC',
    'SYR': 'SY',
    'TCA': 'TC',
    'TCD': 'TD',
    'TGO': 'TG',
    'THA': 'TH',
    'TJK': 'TJ',
    'TKL': 'TK',
    'TKM': 'TM',
    'TLS': 'TL',
    'TON': 'TO',
    'TTO': 'TT',
    'TUN': 'TN',
    'TUR': 'TR',
    'TUV': 'TV',
    'TWN': 'TW',
    'TZA': 'TZ',
    'UGA': 'UG',
    'UKR': 'UA',
    'UMI': 'UM',
    'URY': 'UY',
    'USA': 'US',
    'UZB': 'UZ',
    'VAT': 'VA',
    'VCT': 'VC',
    'VEN': 'VE',
    'VGB': 'VG',
    'VIR': 'VI',
    'VNM': 'VN',
    'VUT': 'VU',
    'WLF': 'WF',
    'WSM': 'WS',
    'XKX': 'XK',
    'YEM': 'YE',
    'ZAF': 'ZA',
    'ZMB': 'ZM',
    'ZWE': 'ZW'
}
