@startuml
    actor dev as developer
    participant local as "local system"
    participant github as Github
    participant gha as "GitHub Actions"
    participant kube as "Google Kubernetes"
    participant zulip

    dev ->> local:  checkout production branch

    dev ->> local: ci/promote-test-to-prod.sh
    activate local
        local ->> kube: get running versions
        activate kube
            kube -->> local: versions of TEST & PROD
        deactivate kube
        local ->> local: print github diff link
        local -->> dev: commands for git tag and zulip notif
    deactivate local

    dev ->> local: git tag

    dev ->> local: git push
    activate local
        local -->> github: tag
        activate github
        github ->> local:
        local ->> dev:
    deactivate local

    dev ->> local: notify through zulip
    activate local
        local ->> zulip: notify others
        activate zulip
            zulip ->> local: notified
        deactivate zulip
        local ->> dev:
    deactivate local


    github ->> gha: new tag pushed
    activate gha
        gha -->> github: OK
        deactivate github
        gha ->> kube: deploy tagged version
        activate kube
            kube ->> gha: applying new config
        deactivate kube
        loop Until containers are ready
            gha ->> kube: please provide container status
            activate kube
                kube -->> gha: status
            deactivate kube
        end
    deactivate gha
@enduml