# doc-warnings: yes
test-warnings: no
strictness: verylow
max-line-length: 100
requirements:
    - scripts/deployment/pip/requirements/2_rsr.txt
ignore-paths:
    - akvo/rsr/migrations
    - akvo/codelists/migrations
