FROM python:3.8.16-bullseye

RUN set -ex; apt-get update \
    && apt-get install -y --no-install-recommends --no-install-suggests \
        cron \
        curl  \
        gettext \
        git  \
        gosu  \
        graphviz \
        libffi-dev \
        libfontenc1  \
        libfreetype6-dev \
        libjpeg-dev \
        libssl-dev \
        libxml2-dev \
        libxslt1-dev \
        plantuml \
        postgresql-client  \
        python3-dev \
        runit  \
        xfonts-75dpi \
        xfonts-base \
        xfonts-encodings \
        xfonts-utils \
        zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && \
    python get-pip.py && \
    pip install --upgrade pip && \
    rm get-pip.py

ENV NODE_VERSION 14.21.3

RUN curl -fsSLO --compressed "https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.xz" \
  && tar -xJf "node-v$NODE_VERSION-linux-x64.tar.xz" -C /usr/local --strip-components=1 --no-same-owner \
  && rm "node-v$NODE_VERSION-linux-x64.tar.xz" \
  && ln -s /usr/local/bin/node /usr/local/bin/nodejs

RUN addgroup akvo && adduser --disabled-password --home /home/akvo --shell /bin/bash --ingroup akvo --gecos "" akvo

WORKDIR /var/akvo/rsr/code

COPY scripts/deployment/pip/requirements/2_rsr.txt ./
RUN pip install --no-cache-dir -r 2_rsr.txt

COPY scripts/deployment/pip/requirements/3_dev.txt ./
RUN pip install --no-cache-dir -r 3_dev.txt

ENV PYTHONUNBUFFERED 1

CMD [ "scripts/docker/dev/run-as-user.sh", "scripts/docker/dev/start-django.sh"]
