FROM python:2.7.16-buster

RUN set -ex; apt-get update && \
    apt-get install -y --no-install-recommends --no-install-suggests \
    libgeos-dev curl git postgresql-client runit cron \
    libjpeg-dev libfreetype6-dev \
    libffi-dev libssl-dev \
    libxml2-dev libxslt1-dev zlib1g-dev python-dev gosu && \
    rm -rf /var/lib/apt/lists/*

RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && \
    python get-pip.py && \
    rm get-pip.py

ENV NODE_VERSION 10.15.0

RUN curl -fsSLO --compressed "https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.xz" \
  && tar -xJf "node-v$NODE_VERSION-linux-x64.tar.xz" -C /usr/local --strip-components=1 --no-same-owner \
  && rm "node-v$NODE_VERSION-linux-x64.tar.xz" \
  && ln -s /usr/local/bin/node /usr/local/bin/nodejs

RUN addgroup akvo && adduser --disabled-password --home /home/akvo --shell /bin/bash --ingroup akvo --gecos "" akvo

WORKDIR /var/akvo/rsr/code

COPY scripts/deployment/pip/requirements/2_rsr.txt ./
RUN pip install --no-cache-dir -r 2_rsr.txt

COPY scripts/deployment/pip/requirements/5_dev.txt ./
RUN pip install --no-cache-dir -r 5_dev.txt

COPY scripts/deployment/pip/requirements/3_testing.txt ./
RUN pip install --no-cache-dir -r 3_testing.txt

ENV PYTHONUNBUFFERED 1

CMD [ "scripts/docker/dev/run-as-user.sh", "scripts/docker/dev/start-django.sh"]