FROM python:3.8.16-bullseye

RUN set -ex; apt-get update && \
    apt-get install -y --no-install-recommends --no-install-suggests \
    curl git postgresql-client runit cron \
    libjpeg-dev libfreetype6-dev \
    libffi-dev libssl-dev \
    libfontenc1 xfonts-encodings xfonts-utils xfonts-75dpi xfonts-base \
    libxml2-dev libxslt1-dev zlib1g-dev python3-dev && \
    rm -rf /var/lib/apt/lists/*

RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && \
    python get-pip.py && \
    rm get-pip.py

WORKDIR /var/akvo/rsr/code

COPY scripts/deployment/pip/requirements/2_rsr.txt ./
RUN pip install --no-cache-dir -r 2_rsr.txt

RUN mkdir -p /var/akvo/rsr/logs/
RUN mkdir -p /var/log/akvo/
RUN mkdir -p /var/akvo/rsr/code/data

COPY manage.py /var/akvo/rsr/code/
COPY scripts/docker/prod/start-django.sh /var/akvo/rsr/code/
COPY scripts/docker/dev/wait-for-dependencies.sh /var/akvo/rsr/code/
COPY scripts/probes/worker.sh /var/akvo/rsr/code/scripts/probes/

CMD ["./start-django.sh"]
