FROM akvo/rsr-backend-prod-no-code-with-nodejs:local

WORKDIR /var/akvo/rsr/code/akvo/rsr/front-end

COPY akvo/rsr/front-end /var/akvo/rsr/code/akvo/rsr/front-end

RUN npm install && rm -rf node_modules && npm install && npm run prod