{
 "title": "RSR",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Request per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_count{app=\"rsr\"}[$__interval])) by (url)",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "95% latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_requests_bucket{app=\"rsr\"}[$__interval])) by (le,url,method))",
     "legendFormat": "{{method}} - {{url}}"
    }
   ]
  },
  {
   "title": "Memory (MB)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{pod=~\"rsr.*\",container!=\"POD\",container=~\".+\"} / 1024 / 1024",
     "legendFormat": "{{pod}} - {{container}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=~\".+\",container!=\"POD\",pod=~\"rsr.*\",namespace=\"default\"}[$__interval])) by (container, pod)",
     "legendFormat": "{{pod}} - {{container}}"
    }
   ]
  },
  {
   "title": "DB - Query per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(db_count{app=\"rsr\"}[$__interval])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "DB - latencies",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(db_bucket{app=\"rsr\"}[$__interval])) by (le,method))",
     "legendFormat": "95% - {{method}} "
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(db_bucket{app=\"rsr\"}[$__interval])) by (le,method))",
     "legendFormat": "99% - {{method}} "
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{pod=~\"rsr.*\"}[$__interval])) by (container, pod)",
     "legendFormat": "{{pod}} - {{container}}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{pod=~\"rsr.*\"}[$__interval])) by (container, pod)",
     "legendFormat": "{{pod}} - {{container}}"
    }
   ]
  },
  {
   "title": "Memory Leak Detection - Application Memory (MB)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "django_memory_usage_bytes{container!=\"unknown\"} / 1024 / 1024",
     "legendFormat": "{{container}} - {{view_name}}"
    }
   ]
  },
  {
   "title": "Memory Leak Events (1h)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(django_memory_growth_events_total{container!=\"unknown\"}[1h])",
     "legendFormat": "{{container}} - {{threshold}} growth"
    }
   ]
  },
  {
   "title": "Python Object Counts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "django_python_objects_total{container!=\"unknown\",object_type=~\"dict|list|str\"}",
     "legendFormat": "{{container}} - {{object_type}} objects"
    }
   ]
  },
  {
   "title": "Memory Growth Rate (MB/h)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(django_memory_usage_bytes{container!=\"unknown\"}[1h]) / 1024 / 1024",
     "legendFormat": "{{container}} - {{view_name}} growth rate"
    }
   ]
  },
  {
   "title": "Restarts per 30 mins",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{pod=~\"rsr.*\"}[30m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Garbage Collection Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(django_gc_collections_total{container!=\"unknown\"}[5m])",
     "legendFormat": "{{container}} - Gen {{generation}} GC"
    }
   ]
  },
  {
   "title": "Worker Container Memory Usage (MB)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "django_memory_usage_bytes{container=\"rsr-worker\",component=\"worker\"} / 1024 / 1024",
     "legendFormat": "Worker Memory Usage (MB)"
    }
   ]
  },
  {
   "title": "Worker Task Execution Rate (tasks/hour)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(django_worker_tasks_total{container=\"rsr-worker\"}[1h])",
     "legendFormat": "{{task_name}} - {{status}}"
    }
   ]
  },
  {
   "title": "Worker Task Memory Usage by Task (MB)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "django_worker_task_memory_bytes{container=\"rsr-worker\"} / 1024 / 1024",
     "legendFormat": "{{task_name}} - {{phase}}"
    }
   ]
  }
 ]
}