{
 "title": "RSR",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Request per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_count{app=\"rsr\"}[5m])) by (url)",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "95% latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_requests_bucket{app=\"rsr\"}[5m])) by (le,url,method))",
     "legendFormat": "{{method}} - {{url}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"rsr.*\", container_name!=\"POD\"}",
     "legendFormat": "{{container_name}} - {{pod_name}} "
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",pod_name=~\"rsr.*\"}[5m])) by (container_name, pod_name)",
     "legendFormat": "{{container_name}} - {{pod_name}}"
    }
   ]
  },
  {
   "title": "DB - Query per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(db_count{app=\"rsr\"}[5m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "DB - latencies",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(db_bucket{app=\"rsr\"}[5m])) by (le,method))",
     "legendFormat": "95% - {{method}} "
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(db_bucket{app=\"rsr\"}[5m])) by (le,method))",
     "legendFormat": "99% - {{method}} "
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"rsr.*\"}[5m])) by (container_name, pod_name)",
     "legendFormat": "{{container_name}} - {{pod_name}}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"rsr.*\"}[5m])) by (container_name, pod_name)",
     "legendFormat": "{{container_name}} - {{pod_name}}"
    }
   ]
  },
  {
   "title": "Restarts per 30 mins",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{pod=~\"rsr.*\"}[30m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}