# -*- mode: ruby -*-
# vi: set ft=ruby :

# Akvo RSR is covered by the GNU Affero General Public License.
# See more details in the license.txt file located at the root folder of the
# Akvo RSR module. For additional details on the GNU license please
# see < http://www.gnu.org/licenses/agpl.html >.


Vagrant.configure("2") do |config|
  config.vm.box = "rsr-dev-20150209"
  config.vm.box_url = "http://files.akvo-ops.org/rsr-dev-20150209.box"

  config.vm.synced_folder "../", "/vagrant/rsr/checkout/", id: "vagrant-root",
  :owner => "rsr",
  :group => "rsr"

  config.vm.network :private_network, ip: "192.168.50.101"

  config.vm.provision "shell", run: "always", path: "./provisioning/start_postgres.sh"
  config.vm.provision "shell", path: "./provisioning/link_code.sh"
  config.vm.provision "shell", path: "./provisioning/install_dependencies.sh"
  config.vm.provision "shell", path: "./provisioning/install_dev_dependencies.sh"
  config.vm.provision "shell", run: "always", path: "./provisioning/fix_dns.sh"
  config.vm.provision "shell", path: "./provisioning/load_test_db.sh"
  config.vm.provision "shell", run: "always", path: "./provisioning/prepare_rsr.sh"

end
