# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "rsr-dev-pg-20150209"
  condig.vm.box_url = "https://www.dropbox.com/s/z9378xx7ab6fh58/rsr-dev-pg-20150209.box?dl=1"
  # config.vm.box_url = "http://files.akvo-ops.org/rsr-dev-20141022.box"

  config.vm.synced_folder "../", "/vagrant/rsr/checkout/", id: "vagrant-root",
  :owner => "rsr",
  :group => "rsr"

  config.vm.network :private_network, ip: "192.168.50.101"

  # Deactivated until we have a proper base box
  # config.vm.provision :shell, :path => "./provision_vagrant.sh"

end
