export default {
  EDIT_FIELD: 'PE_REPORTING_EDIT_FIELD',
  ADD_ARRAY_ITEM: 'PE_REPORTING_ADD_ARRAY_ITEM',
  REMOVE_ARRAY_ITEM: 'PE_REPORTING_REMOVE_ARRAY_ITEM',
  EDIT_ARRAY_ITEM_FIELD: 'PE_REPORTING_EDIT_ARRAY_ITEM_FIELD'
}
