export default {
  EDIT_FIELD: 'PE_REPORTING_EDIT_FIELD',
  FLAGS: {
    ADD: 'PE_REPORTING_ADD_FLAG',
    REMOVE: 'PE_REPORTING_REMOVE_FLAG',
    EDIT_FIELD: 'PE_REPORTING_EDIT_FLAG_FIELD',
  },
  FORECASTS: {
    ADD: 'PE_REPORTING_ADD_FLAG',
    REMOVE: 'PE_REPORTING_REMOVE_FLAG',
    EDIT_FIELD: 'PE_REPORTING_EDIT_FLAG_FIELD',
  },
  LEGACIES: {
    ADD: 'PE_REPORTING_ADD_LEGACY',
    REMOVE: 'PE_REPORTING_REMOVE_LEGACY',
    EDIT_FIELD: 'PE_REPORTING_EDIT_LEGACY_FIELD',
  }
}
