export default {
  LINKS: {
    ADD: 'PE_LINKS_ADD',
    REMOVE: 'PE_LINKS_REMOVE',
    EDIT_FIELD: 'PE_LINKS_EDIT_FIELD'
  },
  DOCS: {
    ADD: 'PE_DOCS_ADD',
    REMOVE: 'PE_DOCS_REMOVE',
    EDIT_FIELD: 'PE_DOCS_EDIT_FIELD'
  }
}
