FROM python:2.7.16-buster

RUN set -ex; apt-get update && \
    apt-get install -y --no-install-recommends --no-install-suggests \
    curl git postgresql-client runit \
    libjpeg-dev libfreetype6-dev \
    libffi-dev libssl-dev wkhtmltopdf \
    libxml2-dev libxslt1-dev zlib1g-dev python-dev gosu && \
    rm -rf /var/lib/apt/lists/*

RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && \
    python get-pip.py && \
    rm get-pip.py

RUN addgroup akvo && adduser --disabled-password --home /home/akvo --shell /bin/bash --ingroup akvo --gecos "" akvo

WORKDIR /var/akvo/rsr/code

COPY scripts/deployment/pip/requirements/2_rsr.txt ./
RUN pip install --no-cache-dir -r 2_rsr.txt

ENV PYTHONUNBUFFERED 1
ENV RSR_REPORTS 1

CMD [ "scripts/docker/dev/run-as-user.sh", "reports/start-dev.sh"]
