# Generated by Django 3.2.10 on 2023-01-07 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PolicyConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("expiration", models.DurationField(blank=True, null=True)),
                (
                    "reuse",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Reuse policy"
                    ),
                ),
                ("min_length", models.PositiveSmallIntegerField(default=5)),
                (
                    "letters",
                    models.PositiveSmallIntegerField(blank=True, default=1, null=True),
                ),
                ("uppercases", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("numbers", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("symbols", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("no_common_password", models.BooleanField(default=False)),
                ("no_user_attributes", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="RegexRuleConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pattern", models.CharField(max_length=255)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regex_rules",
                        to="password_policy.policyconfig",
                    ),
                ),
            ],
        ),
    ]
