# Generated by Django 3.2.18 on 2023-08-09 10:56

from django.db import migrations, models


def migrate_expiration_days(apps, _):
    PolicyConfig = apps.get_model('password_policy', 'PolicyConfig')
    for config in PolicyConfig.objects.all():
        if not config.expiration:
            continue
        config.expiration_days = config.expiration.seconds
        config.save()


class Migration(migrations.Migration):

    dependencies = [
        ('password_policy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policyconfig',
            options={},
        ),
        migrations.AddField(
            model_name='policyconfig',
            name='expiration_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Maximum password age (days). Set empty for never expires', null=True),
        ),
        migrations.RunPython(migrate_expiration_days),
    ]
