# Generated by Django 3.2.18 on 2023-08-09 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password_policy', '0002_auto_20230809_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policyconfig',
            name='expiration',
        ),
    ]
