# Generated by Django 3.2.18 on 2023-08-09 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password_policy', '0003_remove_policyconfig_expiration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policyconfig',
            old_name='expiration_days',
            new_name='expiration',
        ),
    ]
