name: Feature request
description: Suggest an idea/improvement for this project
title: 'Feature Request: '
labels:
    - "Feature request"

body:
    - type: textarea
      id: goal
      validations:
          required: true
      attributes:
        label: What are you trying to do?
        placeholder: A clear and concise description of the steps you're taking.

    - type: textarea
      id: description
      validations:
          required: true
      attributes:
        label: Describe the solution you'd like
        description: A clear and concise description of what you believe should be happening
        placeholder: |
            If it gets longer, please add bullet point list of the expected result e.g

              - Dialog is moved to upper left corner
              - Click on "Do something" button in dialog triggers:
                * Text to bizzle
                * Title to hizzle
                * Dialog to fizzle

    - type: textarea
      id: alternatives
      attributes:
        label: Have you consider alternatives?
        description: A clear and concise description of any alternative solutions or features you've considered.

    - type: textarea
      id: additional_context
      attributes:
        label: Additional context
        description: Add any other context or screenshots about the feature request
