#!/bin/bash
#
# Auto-start script for TeamCity build agent 1
#
# description: Starts the TeamCity build agent automatically on server startup
# processname: teamcity_agent1

TEAMCITY_AGENTS_HOME=/home/tomcat/.BuildServer/agents
AGENT_LOG_PATH=$TEAMCITY_AGENTS_HOME/agent1/logs

UTC_LOG_TIMESTAMP=`date -u +%Y%m%d_%H%M%S`
PROCESS_OUTPUT_FILE=$AGENT_LOG_PATH/init_process_$UTC_LOG_TIMESTAMP.out


function start_agent
{
    su -s /bin/bash -l tomcat $TEAMCITY_AGENTS_HOME/agent1/bin/agent.sh start > $PROCESS_OUTPUT_FILE 2>&1
}

function stop_agent
{
    su -s /bin/bash -l tomcat $TEAMCITY_AGENTS_HOME/agent1/bin/agent.sh stop >> $PROCESS_OUTPUT_FILE 2>&1
}

case $1 in
start)
        start_agent
        ;;
stop)
        stop_agent
        ;;
restart)
        stop_agent
        start_agent
        ;;
esac
exit 0
