#!/bin/bash
#
# Tomcat auto-start script
# 
# description: Starts Tomcat automatically on server startup
# processname: tomcat

CATALINA_HOME=/usr/local/tomcat6


function start_tomcat
{
    su -s /bin/bash -l tomcat $CATALINA_HOME/bin/startup.sh
}

function stop_tomcat
{
    su -s /bin/bash -l tomcat $CATALINA_HOME/bin/shutdown.sh
}

case $1 in
start)
        start_tomcat
        ;; 
stop)   
        stop_tomcat
        ;; 
restart)
        stop_tomcat
        start_tomcat
        ;; 
esac    
exit 0
