export default {
  FETCH_SECTION: 'PE_FETCH_SECTION',
  SAVE_FIELDS: 'PE_SAVE_FIELDS',
  TOUCH_SECTION: 'PE_TOUCH_SECTION',
  ADD_SET_ITEM: 'PE_ADD_SET_ITEM',
  EDIT_SET_ITEM: 'PE_EDIT_SET_ITEM',
  REMOVE_SET_ITEM: 'PE_REMOVE_SET_ITEM'
}
