export default {
  FETCH_SECTION: 'PE_FETCH_SECTION',
  FETCH_SET_ITEMS: 'PE_FETCH_SET_ITEMS',
  SAVE_FIELDS: 'PE_SAVE_FIELDS',
  TOUCH_SECTION: 'PE_TOUCH_SECTION',
  ADD_SET_ITEM: 'PE_ADD_SET_ITEM',
  EDIT_SET_ITEM: 'PE_EDIT_SET_ITEM',
  REMOVE_SET_ITEM: 'PE_REMOVE_SET_ITEM',
  BACKEND_SYNC: 'PE_BACKEND_SYNC',
  BACKEND_ERROR: 'PE_BACKEND_ERROR',
  CHECK_VALIDATION: 'PE_CHECK_VALIDATION',
  TOGGLE_PRIVACY: 'PE_TOGGLE_PRIVACY',
  SET_PROJECT_ID: 'PE_SET_PROJECT_ID'
}
