table = 'auth_permission'
fields = ['id', 'name', 'content_type_id', 'codename']
#default item format: "fieldname":("type", "value")
default = {}
records = [
[1, u'Can add message', 1, u'add_message']
[2, u'Can change message', 1, u'change_message']
[3, u'Can delete message', 1, u'delete_message']
[4, u'Can add group', 2, u'add_group']
[5, u'Can change group', 2, u'change_group']
[6, u'Can delete group', 2, u'delete_group']
[7, u'Can add user', 3, u'add_user']
[8, u'Can change user', 3, u'change_user']
[9, u'Can delete user', 3, u'delete_user']
[10, u'Can add permission', 4, u'add_permission']
[11, u'Can change permission', 4, u'change_permission']
[12, u'Can delete permission', 4, u'delete_permission']
[13, u'Can add content type', 5, u'add_contenttype']
[14, u'Can change content type', 5, u'change_contenttype']
[15, u'Can delete content type', 5, u'delete_contenttype']
[16, u'Can add session', 6, u'add_session']
[17, u'Can change session', 6, u'change_session']
[18, u'Can delete session', 6, u'delete_session']
[19, u'Can add site', 7, u'add_site']
[20, u'Can change site', 7, u'change_site']
[21, u'Can delete site', 7, u'delete_site']
[22, u'Can add log entry', 8, u'add_logentry']
[23, u'Can change log entry', 8, u'change_logentry']
[24, u'Can delete log entry', 8, u'delete_logentry']
[25, u'Can add funding partner', 9, u'add_fundingpartner']
[26, u'Can change funding partner', 9, u'change_fundingpartner']
[27, u'Can delete funding partner', 9, u'delete_fundingpartner']
[28, u'Can add funding', 10, u'add_funding']
[29, u'Can change funding', 10, u'change_funding']
[30, u'Can delete funding', 10, u'delete_funding']
[31, u'Can add field partner', 11, u'add_fieldpartner']
[32, u'Can change field partner', 11, u'change_fieldpartner']
[33, u'Can delete field partner', 11, u'delete_fieldpartner']
[34, u'Can add project', 12, u'add_project']
[35, u'Can change project', 12, u'change_project']
[36, u'Can delete project', 12, u'delete_project']
[37, u'Can add project update', 13, u'add_projectupdate']
[38, u'Can change project update', 13, u'change_projectupdate']
[39, u'Can delete project update', 13, u'delete_projectupdate']
[40, u'Can add organization', 14, u'add_organization']
[41, u'Can change organization', 14, u'change_organization']
[42, u'Can delete organization', 14, u'delete_organization']
[43, u'Can add sponsor partner', 15, u'add_sponsorpartner']
[44, u'Can change sponsor partner', 15, u'change_sponsorpartner']
[45, u'Can delete sponsor partner', 15, u'delete_sponsorpartner']
[46, u'Can add link', 16, u'add_link']
[47, u'Can change link', 16, u'change_link']
[48, u'Can delete link', 16, u'delete_link']
[49, u'Can add site', 17, u'add_site']
[50, u'Can change site', 17, u'change_site']
[51, u'Can delete site', 17, u'delete_site']
[52, u'Can add feed', 18, u'add_feed']
[53, u'Can change feed', 18, u'change_feed']
[54, u'Can delete feed', 18, u'delete_feed']
[55, u'Can add tag', 19, u'add_tag']
[56, u'Can change tag', 19, u'change_tag']
[57, u'Can delete tag', 19, u'delete_tag']
[58, u'Can add post', 20, u'add_post']
[59, u'Can change post', 20, u'change_post']
[60, u'Can delete post', 20, u'delete_post']
[61, u'Can add subscriber', 21, u'add_subscriber']
[62, u'Can change subscriber', 21, u'change_subscriber']
[63, u'Can delete subscriber', 21, u'delete_subscriber']
]
