table = 'django_content_type'
fields = ['id', 'name', 'app_label', 'model']
#default item format: "fieldname":("type", "value")
default = {}
records = [
[1, u'message', u'auth', u'message']
[2, u'group', u'auth', u'group']
[3, u'user', u'auth', u'user']
[4, u'permission', u'auth', u'permission']
[5, u'content type', u'contenttypes', u'contenttype']
[6, u'session', u'sessions', u'session']
[7, u'site', u'sites', u'site']
[8, u'log entry', u'admin', u'logentry']
[9, u'funding partner', u'rsr', u'fundingpartner']
[10, u'funding', u'rsr', u'funding']
[11, u'field partner', u'rsr', u'fieldpartner']
[12, u'project', u'rsr', u'project']
[13, u'project update', u'rsr', u'projectupdate']
[14, u'organization', u'rsr', u'organization']
[16, u'link', u'feedjack', u'link']
[17, u'site', u'feedjack', u'site']
[18, u'feed', u'feedjack', u'feed']
[19, u'tag', u'feedjack', u'tag']
[20, u'post', u'feedjack', u'post']
[21, u'subscriber', u'feedjack', u'subscriber']
[22, u'project comment', u'rsr', u'projectcomment']
[23, u'support partner', u'rsr', u'supportpartner']
[24, u'country', u'rsr', u'country']
[25, u'link', u'rsr', u'link']
[26, u'registration profile', u'registration', u'registrationprofile']
[27, u'rs r_ registration profile', u'rsr', u'rsr_registrationprofile']
[28, u'user profile', u'rsr', u'userprofile']
]
