table = 'rsr_projectcomment'
fields = ['id', 'project_id', 'user_id', 'comment', 'time']
#default item format: "fieldname":("type", "value")
default = {}
records = [
[1, 1, 1, u'Foo bar baz', '2008-06-25 13:05:02']
[2, 1, 1, u'Frogs like flies', '2008-06-25 13:20:20']
[3, 1, 1, u'froo', '2008-06-25 13:20:58']
[4, 1, 1, u'gruff', '2008-06-25 13:21:49']
[5, 1, 1, u'dsfgsdf', '2008-06-25 13:28:33']
[6, 1, 1, u'fooo', '2008-06-25 13:29:37']
[7, 1, 1, u'', '2008-06-25 13:30:28']
[8, 1, 1, u'Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment Really loong comment ', '2008-06-25 13:41:29']
[9, 1, 1, u'ReallylongcommentReallylongcommentReallylongcommentReallylongcommentReallylongcommentReallylongcommentReallylongcommentReallylongcommentReallylongcommentReallylongcommentReallylongcommentReallylongcommentReallylongcommentReallylongcommentReallylongcommentReallylongcommentReallylongcommentReallylongcommentReallylongcommentReallylongcommentReallylongcommentReallylongcommentReallylongcommentReallylongcommentReallylongcommentReallylongcommentReallylongcommentReallylongcommentReallylongcommentReallylongcommentReallylongcommentReallylongcommentReallylongcommentReallylongcommentReallylongcommentReallylongcommentReallylongcommentReallylongcommentReallylongcommentReallylongcommentReallylongcommentReallylongcommentReallylongcommentReallylongcommentReallylongcommentReallylongcommentReallylongcommentReallylongcomment', '2008-06-25 13:42:33']
[10, 1, 4, u'dj sdfgj \xe5aodjg a\xe5oj asodjas\xe5ojf a\xe5sodjf a\xe5sodjf as\xe5odijf aso\xe5djf \xe5aosdijf \xe5asodijf as\xe5odijf a\xe5sodifj aso\xe5djf aso\xe5dijf as\xe5odijf ', '2008-06-25 13:44:51']
[11, 2, 1, u'The first comment on this project!\r\n\r\n', '2008-06-25 13:47:26']
[12, 2, 2, u'This is a very interesting project. We have been trying something like this ourselves and it is very successful quickly.', '2008-06-26 07:10:26']
[13, 1, 2, u'This is a very interesting project. I am looking forward to using Akvo with my projects soon.', '2008-06-27 13:45:36']
]
