table = 'rsr_projectupdate'
fields = ['id', 'project_id', 'user_id', 'title', 'text', 'status', 'photo', 'photo_location', 'photo_caption', 'photo_credit', 'update_method', 'time']
#default item format: "fieldname":("type", "value")
default = {}
records = [
[3, 1, 1, u'foo', u'', u'H', u'', u'', u'', u'', u'W', '2008-06-22 17:42:16']
[4, 1, 1, u'asdasd', u'asdasd asdasd', u'N', u'', u'E', u'', u'', u'W', '2008-06-22 17:44:33']
[5, 1, 1, u'Students at school', u'This is a picture from just outside the school where the students normally work every day. They are lined up before starting class.', u'H', u'img/2008/06/22/fodra-group-1_.png', u'B', u'Students at school', u'Mark charmer', u'W', '2008-06-22 21:59:11']
[6, 2, 1, u'Integer eget sem.', u'Nulla facilisi. In vel sem. Morbi id urna in diam dignissim feugiat. Proin molestie tortor eu velit. Aliquam erat volutpat. Nullam ultrices, diam tempus vulputate egestas, eros pede varius leo, sed imperdiet lectus est ornare odio. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin consectetuer velit in dui. Phasellus wisi purus, interdum vitae, rutrum accumsan, viverra in, velit. Sed enim risus, congue non, tristique in, commodo eu, metus. Aenean tortor mi, imperdiet id, gravida eu, posuere eu, felis. Mauris sollicitudin, turpis in hendrerit sodales, lectus ipsum pellentesque ligula, sit amet scelerisque urna nibh ut arcu. Aliquam in lacus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla placerat aliquam wisi. Mauris viverra odio. Quisque fermentum pulvinar odio. Proin posuere est vitae ligula. Etiam euismod. Cras a eros.', u'H', u'img/2008/06/23/logo_akvo_250.png', u'B', u'Lorem ipsum dolor sit amet, consectetuer adipiscing elit', u'', u'W', '2008-06-23 19:27:53']
[7, 2, 1, u'Donec non tortor in arcu mollis feugiat', u'Aliquam adipiscing libero vitae leo\r\n\r\nVivamus convallis urna id felis\r\n\r\nFusce luctus convallis justo\r\n\r\nMaecenas tempus dictum libero\r\n\r\nLorem ipsum dolor sit amet, consectetuer adipiscing elit\r\n\r\n', u'A', u'', u'', u'', u'', u'W', '2008-06-23 19:31:04']
[8, 2, 1, u'Donec non tortor in arcu mollis feugiat', u'Aliquam adipiscing libero vitae leo\r\n\r\nVivamus convallis urna id felis\r\n\r\nFusce luctus convallis justo\r\n\r\nMaecenas tempus dictum libero\r\n\r\nLorem ipsum dolor sit amet, consectetuer adipiscing elit\r\n\r\n', u'A', u'', u'', u'', u'', u'W', '2008-06-23 19:31:26']
[9, 2, 1, u'Picture from outside school', u'This is a picture from just outside one of the schools. During summer season this road is usually flooded and this creates problems when no proper sanitation facilities are in place.', u'H', u'img/2008/06/23/fodra-group-3.jpg', u'E', u'dfgsd sdfg sdfg', u'dsfg sdf sdfg sdfg sdfgs', u'W', '2008-06-23 20:17:05']
[12, 1, 1, u'Maintenance training completed', u'We have completed the the maintenance training for the ecosan toilets. We did it for 30 people last saturday.', u'A', u'', u'', u'', u'', u'W', '2008-06-23 21:20:55']
[13, 1, 1, u'Community meeting', u'Completed first community meeting today.', u'A', u'img/2008/06/23/1493799561_8a474eca3f_m.jpg', u'E', u'Pratap Nagar', u'Mark Charmer', u'W', '2008-06-23 21:25:04']
[14, 2, 1, u'Installed new collection facilities', u'This week we have been installing new rain water harvesting equipment in 10 homes. We are still in the process of doing this, but here is a progress picture.', u'A', u'img/2008/06/24/1531738658_e1c104c32e.jpg', u'', u'Rainwater harvesting installation', u'Mark Charmer', u'W', '2008-06-24 23:37:17']
[15, 3, 1, u'blah', u'foo', u'H', u'', u'E', u'', u'', u'W', '2008-07-10 22:40:33']
[16, 2, 2, u'Training', u'Performed training session on how to clean the tanks for 10 people today.', u'A', u'', u'', u'', u'', u'W', '2008-07-11 10:21:03']
]
