table = 'rsr_organization'
fields = ['id', 'field_partner', 'support_partner', 'funding_partner', 'name', 'long_name', 'organization_type', 'logo', 'city', 'state', 'country', 'url', 'map', 'address_1', 'address_2', 'postcode', 'phone', 'fax', 'contact_person', 'contact_email', 'description']
#default item format: "fieldname":("type", "value")
default = {}
records = [
[1, False, False, True, u'Plieger', u'', u'C', u'img/2008/07/10/plieger_logo.gif', u'Zaltbommel', u'Provincie Gelde', u'The Netherlands', u'http://www.plieger.nl', u'map', u'5301 KK Zaltbommel', u'Postbus 10', u'5300 AA Za', u'00 31 418 682 682', u'00 31 418 680 207   ', u'REPLACE ME', u'REPLACE@ME.COM', u'Quisque facilisis erat a dui. Nam malesuada ornare dolor. Cras gravida, diam sit amet rhoncus ornare, erat elit consectetuer erat, id egestas pede nibh eget odio. Proin tincidunt, velit vel porta elementum, magna diam molestie sapien, non aliquet massa pede eu diam. Aliquam iaculis. Fusce et ipsum et nulla tristique facilisis. Donec eget sem sit amet ligula viverra gravida. Etiam vehicula urna vel turpis. Suspendisse sagittis ante a urna. Morbi a est quis orci consequat rutrum. Nullam egestas feugiat felis. Integer adipiscing semper ligula. Nunc molestie, nisl sit amet cursus convallis, sapien lectus pretium metus, vitae pretium enim wisi id lectus. Donec vestibulum. Etiam vel nibh. Nulla facilisi. Mauris pharetra. Donec augue. Fusce ultrices, neque id dignissim ultrices, tellus mauris dictum elit, vel lacinia enim metus eu nunc.']
[2, True, False, False, u'IDYDC', u'"Iringa Development of Youth, Disabled and Children Care ', u'N', u'', u'Iringa region', u'Iringa region', u'Tanzania', u'', u'map', u'Iringa', u'', u'PO Box 794', u'255-745-830303', u'', u'J\xf6rg Henkel', u'idydc94@gmail.com', u'Proin at eros non eros adipiscing mollis. Donec semper turpis sed diam. Sed consequat ligula nec tortor. Integer eget sem. Ut vitae enim eu est vehicula gravida. Morbi ipsum ipsum, porta nec, tempor id, auctor vitae, purus. Pellentesque neque. Nulla luctus erat vitae libero. Integer nec enim. Phasellus aliquam enim et tortor. Quisque aliquet, quam elementum condimentum feugiat, tellus odio consectetuer wisi, vel nonummy sem neque in elit. Curabitur eleifend wisi iaculis ipsum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In non velit non ligula laoreet ultrices. Praesent ultricies facilisis nisl. Vivamus luctus elit sit amet mi. Phasellus pellentesque, erat eget elementum volutpat, dolor nisl porta neque, vitae sodales ipsum nibh in ligula. Maecenas mattis pulvinar diam. Curabitur sed leo.']
[3, False, True, False, u'WASTE', u'', u'N', u'img/2008/07/10/logo_waste.jpg', u'Gouda', u'Provincie Zuid ', u'The Netherlands', u'http://www.waste.nl', u'map', u'Nieuwehaven 201', u'', u'2801 CW', u'+31 (0)182 522625', u'+31 (0)182 550313', u'Gert de Bruijne', u'gdebruijne@waste.nl', u'Aliquam aliquet, est a ullamcorper condimentum, tellus nulla fringilla elit, a iaculis nulla turpis sed wisi. Fusce volutpat. Etiam sodales ante id nunc. Proin ornare dignissim lacus. Nunc porttitor nunc a sem. Sed sollicitudin velit eu magna. Aliquam erat volutpat. Vivamus ornare est non wisi. Proin vel quam. Vivamus egestas. Nunc tempor diam vehicula mauris. Nullam sapien eros, facilisis vel, eleifend non, auctor dapibus, pede.']
[4, True, False, False, u'BASA', u'Bangladesh Association for Social Advancement', u'N', u'', u'Dhaka', u'Dhaka', u'Bangladesh', u'http://www.basango.org', u'map', u'House 247, Road 18', u'New Dohs Mohakhali', u'Dhaka', u'+008802-9862464', u'008802-9880957', u'A.K.M. Shirajul Islam', u'edbasa@worldnetbd.net', u'Proin at eros non eros adipiscing mollis. Donec semper turpis sed diam. Sed consequat ligula nec tortor. Integer eget sem. Ut vitae enim eu est vehicula gravida. Morbi ipsum ipsum, porta nec, tempor id, auctor vitae, purus. Pellentesque neque. Nulla luctus erat vitae libero. Integer nec enim. Phasellus aliquam enim et tortor. Quisque aliquet, quam elementum condimentum feugiat, tellus odio consectetuer wisi, vel nonummy sem neque in elit. Curabitur eleifend wisi iaculis ipsum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In non velit non ligula laoreet ultrices. Praesent ultricies facilisis nisl. Vivamus luctus elit sit amet mi. Phasellus pellentesque, erat eget elementum volutpat, dolor nisl porta neque, vitae sodales ipsum nibh in ligula. Maecenas mattis pulvinar diam. Curabitur sed leo.']
[5, True, False, False, u'PA Bangladesh', u'Practical Action Bangladesh', u'N', u'', u'Dhaka', u'Dhaka', u'Bangladesh', u'http://practicalaction.org/?id=region_bangladesh', u'map', u'House 32, Road 13A', u'Dhanmondi R/A', u' Dhaka-120', u'+ 8802 8111934', u'', u'A.K.M. Shirajul Islam ', u'edbasa@worldnetbd.net', u'Aliquam aliquet, est a ullamcorper condimentum, tellus nulla fringilla elit, a iaculis nulla turpis sed wisi. Fusce volutpat. Etiam sodales ante id nunc. Proin ornare dignissim lacus. Nunc porttitor nunc a sem. Sed sollicitudin velit eu magna. Aliquam erat volutpat. Vivamus ornare est non wisi. Proin vel quam. Vivamus egestas. Nunc tempor diam vehicula mauris. Nullam sapien eros, facilisis vel, eleifend non, auctor dapibus, pede.']
[7, True, False, False, u'CBHCC', u'COMMUNITY BASED HEALTH CARE COUNCIL ', u'N', u'', u'Arusha', u'Arusha', u'Tanzania', u'', u'map', u'', u'', u'', u'', u'', u'Eng. SHIJA MLINGWA', u'', u'Ut nulla. Vivamus bibendum, nulla ut congue fringilla, lorem ipsum ultricies risus, ut rutrum velit tortor vel purus. In hac habitasse platea dictumst. Duis fermentum, metus sed congue gravida, arcu dui ornare urna, ut imperdiet enim odio dignissim ipsum. Nulla facilisi. Cras magna ante, bibendum sit amet, porta vitae, laoreet ut, justo. Nam tortor sapien, pulvinar nec, malesuada in, ultrices in, tortor. Cras ultricies placerat eros. Quisque odio eros, feugiat non, iaculis nec, lobortis sed, arcu. Pellentesque sit amet sem et purus pretium consectetuer.']
[8, False, True, True, u'Simawi', u'', u'N', u'img/2008/07/10/simavi_logo_.jpg', u'Haarlem', u'Provincie Noord', u'The Netherlands', u'http://www.simavi.org/', u'map', u'Fonteinlaan 5', u'', u'2012 JG', u'+31 (0) 23 531 80 55', u'+31 (0) 23 532 85 38', u'Saskia Geling', u'saskia.geling@simkavi.org', u'Simavi is a a Dutch non-governmental organisation, committed to working for a world without poverty where people share responsibility towards achieving optimum health for everyone through supporting healthy solutions by local communities.']
[9, True, False, False, u'FP: Athos', u'Test Partner: 3 Musketeers', u'N', u'', u'San Francisco', u'California', u'USA', u'http://www.myurl.tst', u'', u'17th Ave.', u'', u'94122', u'415-333-3333', u'', u'beth w', u'bethwaaa@mydomain.test', u"Field partner for beth's 3 testing Musketeers. "]
[10, False, True, False, u'S: Porthos', u'Test Partner: 3 Musketeers', u'G', u'', u'San Jose', u'CA', u'USA', u'http://www.myurl.tst', u'', u'17th Ave', u'', u'94122', u'415-333-3333', u'', u'beth w', u'bethwaaa@mydomain.test', u"Support partner for beth's 3 testing Musketeers."]
[11, False, False, True, u'M: Aramis', u'Test Partner: 3 Musketeers', u'C', u'', u'Oakland', u'CA', u'USA', u'http://www.myurl.tst', u'', u'17th Ave', u'', u'94122', u'415-333-3333', u'', u'beth w', u'bethwaaa@mydomain.test', u'']
]
