table = 'rsr_organization'
fields = ['id', 'is_field_partner', 'is_support_partner', 'is_funding_partner', 'name', 'long_name', 'logo', 'city', 'state', 'country', 'url', 'map', 'address_1', 'address_2', 'postcode', 'phone', 'fax', 'contact_person', 'contact_email']
#default item format: "fieldname":("type", "value")
default = {}
records = [
[1, u'is_field_partner', u'is_support_partner', u'is_funding_partner', u'Plieger', u'long_name', u'', u'Zaltbommel', u'Provincie Gelde', u'The Netherlands', u'http://www.plieger.nl', u'map', u'5301 KK Zaltbommel', u'Postbus 10', u'5300 AA Za', u'00 31 418 682 682', u'00 31 418 680 207   ', u'123456789 123456789 123456789 ', u'1234567890@23456789012345678901234567890']
[2, u'is_field_partner', u'is_support_partner', u'is_funding_partner', u'IDYDC', u'long_name', u'', u'Iringa region', u'Iringa region', u'Tanzania', u'', u'map', u'Iringa', u'', u'PO Box 794', u'255-745-830303', u'', u'J\xf6rg Henkel', u'idydc94@gmail.com']
[3, u'is_field_partner', u'is_support_partner', u'is_funding_partner', u'WASTE', u'long_name', u'img/2008/06/21/logo_waste.png', u'Gouda', u'Provincie Zuid ', u'The Netherlands', u'http://www.waste.nl', u'map', u'Nieuwehaven 201', u'', u'2801 CW', u'+31 (0)182 522625', u'+31 (0)182 550313', u'Gert de Bruijne', u'gdebruijne@waste.nl']
[4, u'is_field_partner', u'is_support_partner', u'is_funding_partner', u'BASA', u'long_name', u'', u'Dhaka', u'Dhaka', u'Bangladesh', u'http://www.basango.org', u'map', u'House 247, Road 18', u'New Dohs Mohakhali', u'Dhaka', u'+008802-9862464', u'008802-9880957', u'A.K.M. Shirajul Islam', u'edbasa@worldnetbd.net']
[5, u'is_field_partner', u'is_support_partner', u'is_funding_partner', u'PA Bangladesh', u'long_name', u'', u'Dhaka', u'Dhaka', u'Bangladesh', u'http://practicalaction.org/?id=region_bangladesh', u'map', u'House 32, Road 13A', u'Dhanmondi R/A', u' Dhaka-120', u'+ 8802 8111934', u'', u'A.K.M. Shirajul Islam ', u'edbasa@worldnetbd.net']
[6, u'is_field_partner', u'is_support_partner', u'is_funding_partner', u'Simawi', u'long_name', u'', u'Haarlem', u'Provincie Noord', u'The Netherlands', u'http://www.simavi.org/', u'map', u'Fonteinlaan 5', u'', u'2012 JG', u'+31 (0) 23 531 80 55', u'+31 (0) 23 532 85 38', u'Saskia Geling', u'saskia.geling@simkavi.org']
[7, u'is_field_partner', u'is_support_partner', u'is_funding_partner', u'COMMUNITY BASED HEALTH CA', u'long_name', u'', u'Arusha', u'Arusha', u'Tanzania', u'', u'map', u'', u'', u'', u'', u'', u'Eng. SHIJA MLINGWA', u'']
[8, u'is_field_partner', u'is_support_partner', u'is_funding_partner', u'Simawi', u'long_name', u'', u'Haarlem', u'Provincie Noord', u'The Netherlands', u'http://www.simavi.org/', u'map', u'Fonteinlaan 5', u'', u'2012 JG', u'+31 (0) 23 531 80 55', u'+31 (0) 23 532 85 38', u'Saskia Geling', u'saskia.geling@simkavi.org']
]
