table = 'rsr_link'
fields = ['id', 'kind', 'url', 'caption', 'project_id']
#default item format: "fieldname":("type", "value")
default = {}
records = [
[4, u'A', u'http://www.akvo.org/wiki/index.php/Dry_toilet', u'Dry toilets', 3]
[5, u'A', u'http://www.akvo.org/wiki/index.php/Rainwater_harvesting', u'Rain water harvesting', 3]
[6, u'E', u'http://www.akvo.org/', u'Example of external link to Akvo.org', 3]
[7, u'E', u'http://youtube.com/watch?v=_nJMI-Mo_oc', u'YouTube video about project', 25]
[8, u'A', u'http://www.akvo.org/wiki/index.php/Rainwater_harvesting', u'Rain water harvesting', 25]
[9, u'E', u'http://www.seejaneknit.com', u"Nothin' but knit.", 7]
[10, u'A', u'http://www.akvo.org/wiki/index.php/Dry_urine_diversion_toilet', u'Dry urine diversion toilet', 15]
[11, u'A', u'http://www.akvo.org/wiki/index.php/Plastic-lined_tank', u'Plastic Lined Tank', 16]
[12, u'A', u'http://www.akvo.org/wiki/index.php/Groundwater_-_Rota_sludge_well_drilling', u'Rota Sludge Well Drilling', 17]
[13, u'A', u'http://www.akvo.org/wiki/index.php/Rope_pump', u'Rope Pump', 17]
[14, u'A', u'http://www.akvo.org/wiki/index.php/Dry_urine_diversion_toilet', u'Dry Urine Diversion Toilet', 18]
[15, u'A', u'http://www.akvo.org/wiki/index.php/Ceramic_filter', u'Ceramic Filter', 19]
[16, u'A', u'http://www.akvo.org/wiki/index.php/Dry_urine_diversion_toilet', u'Dry urine diversion toilets', 22]
[17, u'A', u'http://www.akvo.org/wiki/index.php/Human_urine_as_fertiliser', u'Human urine as fertiliser', 22]
[18, u'A', u'http://www.akvo.org/wiki/index.php/Compost_as_soil_conditioner', u'Compost as soil conditioner', 22]
[19, u'A', u'http://www.akvo.org/wiki/index.php/Ceramic_filter', u'Ceramic Filter', 24]
[20, u'A', u'http://www.akvo.org/wiki/index.php/Dry_urine_diversion_toilet', u'Dry Urine Diversion Toilet', 32]
[21, u'A', u'http://www.akvo.org/wiki/index.php/Dry_urine_diversion_toilet', u'Dry Urine Diverting Toilet', 33]
[22, u'A', u'http://www.akvo.org/wiki/index.php/Dry_urine_diversion_toilet', u'Dry Urine Diversion Toilet', 34]
[23, u'A', u'http://www.akvo.org/wiki/index.php/Dry_urine_diversion_toilet', u'Dry Urine Diversion Toilet', 35]
[24, u'A', u'http://www.akvo.org/wiki/index.php/Groundwater_-_Rota_sludge_well_drilling', u'Rota Sludge Well Drilling', 30]
[25, u'A', u'http://www.akvo.org/wiki/index.php/Rainwater_harvesting', u'Rainwater Harvesting', 30]
[26, u'A', u'http://www.akvo.org/wiki/index.php/Dry_urine_diversion_toilet', u'Dry Urine Diversion Toilet', 37]
[27, u'E', u'http://www.irc.nl/home/themes/sanitation/wash_in_schools', u'IRC: WASH in schools', 25]
]
