apiVersion: v1
kind: Service
metadata:
  name: {{ include "rsrchart.fullname" . }}
  labels:
{{ include "rsrchart.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "rsrchart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}