# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0138_organisation_original'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crsadd',
            name='loan_status_year',
            field=models.PositiveIntegerField(blank=True, help_text='CRS reporting year (CRS++ Column 1).', null=True, verbose_name='loan status year'),
        ),
        migrations.AlterField(
            model_name='fss',
            name='phaseout_year',
            field=models.PositiveIntegerField(blank=True, help_text='If there are plans to phase out operations from the partner country, this shows the projected year of last disbursements.', null=True, verbose_name='phaseout year'),
        ),
        migrations.AlterField(
            model_name='fssforecast',
            name='year',
            field=models.PositiveIntegerField(blank=True, help_text='The calendar year that the forward spend covers.', null=True, verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='baseline_year',
            field=models.PositiveIntegerField(blank=True, help_text='The year the baseline value was taken.', null=True, verbose_name='baseline year'),
        ),
        migrations.AlterField(
            model_name='loginlog',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='user email'),
        ),
        migrations.AlterField(
            model_name='project',
            name='hierarchy',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Core Activity'), (2, 'Sub Activity'), (3, 'Lower Sub Activity')], help_text='If you are reporting multiple levels of projects in RSR, you can specify whether this is a core, sub, or lower sub activity here.', null=True, verbose_name='hierarchy'),
        ),
        migrations.AlterField(
            model_name='projectcontact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='contact email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='userprojects',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='accessible_by', to='rsr.Project'),
        ),
    ]
