# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-27 13:57
from __future__ import unicode_literals

from django.db import migrations


def results_framework_report_add_comment_param(apps, schema):
    Report = apps.get_model('rsr', 'Report')
    try:
        report = Report.objects.get(name='results-framework')
    except Exception:
        pass
    else:
        report.url += '&p_Comment={comment}'
        report.save()


def results_framework_report_remove_comment_param(apps, schema):
    Report = apps.get_model('rsr', 'Report')
    try:
        report = Report.objects.get(name='results-framework')
    except Exception:
        pass
    else:
        report.url = report.url.replace('&p_Comment={comment}', '')
        report.save()


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0141_auto_20190222_1126'),
    ]

    operations = [
        migrations.RunPython(
            results_framework_report_add_comment_param,
            results_framework_report_remove_comment_param
        )
    ]
