# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-01 11:11


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0142_auto_20190227_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='allow_edit',
        ),
    ]
