# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-02 14:11


import akvo.rsr.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0143_remove_organisation_allow_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='iati_prefixes',
            field=akvo.rsr.fields.ValidXMLCharField(blank=True, help_text='This is a ; separated list of IATI identifier prefixes used by projectswhere the organisation is a reporting partner.', max_length=2000, null=True, verbose_name='IATI identifier prefixes'),
        ),
    ]
