# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-11 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0144_organisation_iati_prefixes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectHierarchy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_depth', models.PositiveSmallIntegerField()),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsr.Organisation')),
                ('root_project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rsr.Project')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name': 'project hierarchy',
                'verbose_name_plural': 'project hierarchies',
            },
        ),
    ]
