# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-29 13:36


import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0146_auto_20190411_0831'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationCodelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Enter a short word or hyphenated-words to identify the codelist.', verbose_name='slug')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name': 'organisation codelist',
                'verbose_name_plural': 'organisation codelists',
            },
        ),
        migrations.AddField(
            model_name='organisation',
            name='codelist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rsr.OrganisationCodelist'),
        ),
    ]
