# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-22 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0146_auto_20190411_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='projects',
            field=models.ManyToManyField(blank=True, to='rsr.Project'),
        ),
    ]
