# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-09 06:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0147_auto_20190429_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatordimension',
            name='parent_dimension',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_dimensions', to='rsr.IndicatorDimension', verbose_name='parent dimension'),
        ),
    ]
