# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-24 11:15
from __future__ import unicode_literals

import akvo.rsr.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0149_indicator_export_to_iati'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicatordimension',
            options={'ordering': ['id'], 'verbose_name': 'indicator disaggregation', 'verbose_name_plural': 'indicator disaggregations'},
        ),
        migrations.AlterField(
            model_name='indicatordimension',
            name='name',
            field=akvo.rsr.fields.ValidXMLCharField(blank=True, help_text='The name of a category to be used when disaggregating (e.g "Age")', max_length=100, verbose_name='disaggregation name'),
        ),
        migrations.AlterField(
            model_name='indicatordimension',
            name='value',
            field=akvo.rsr.fields.ValidXMLCharField(blank=True, help_text='A value in the category being disaggregated (e.g. "Older than 60 years").', max_length=100, verbose_name='disaggregation value'),
        ),
    ]
