# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-23 10:08


import akvo.rsr.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0150_auto_20190524_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorDimensionName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', akvo.rsr.fields.ValidXMLCharField(help_text='The name of a category to be used when disaggregating (e.g "Age").', max_length=100, verbose_name='dimension name')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_names', to='rsr.Project', verbose_name='project')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'indicator dimension name',
                'verbose_name_plural': 'indicator dimension names',
            },
        ),
        migrations.CreateModel(
            name='IndicatorDimensionValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', akvo.rsr.fields.ValidXMLCharField(help_text='A value in the category being disaggregated (e.g. "Older than 60 years").', max_length=100, verbose_name='dimension value')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_values', to='rsr.IndicatorDimensionName', verbose_name='dimension name')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'indicator dimension value',
                'verbose_name_plural': 'indicator dimension values',
            },
        ),
        migrations.AddField(
            model_name='indicator',
            name='dimension_names',
            field=models.ManyToManyField(related_name='indicators', to='rsr.IndicatorDimensionName'),
        ),
    ]
