# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-02 05:22
from __future__ import unicode_literals

import akvo.rsr.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0151_migrate_disaggregations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicatordimensionname',
            options={'ordering': ['id'], 'verbose_name': 'indicator disaggregation name', 'verbose_name_plural': 'indicator disaggregation names'},
        ),
        migrations.AlterModelOptions(
            name='indicatordimensionvalue',
            options={'ordering': ['id'], 'verbose_name': 'indicator disaggregation value', 'verbose_name_plural': 'indicator disaggregation values'},
        ),
        migrations.AlterField(
            model_name='indicatordimensionname',
            name='name',
            field=akvo.rsr.fields.ValidXMLCharField(help_text='The name of a category to be used when disaggregating (e.g "Age").', max_length=100, verbose_name='disaggregation name'),
        ),
        migrations.AlterField(
            model_name='indicatordimensionvalue',
            name='value',
            field=akvo.rsr.fields.ValidXMLCharField(help_text='A value in the category being disaggregated (e.g. "Older than 60 years").', max_length=100, verbose_name='disaggregation value'),
        ),
    ]
