# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-17 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0154_auto_20190603_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='disaggregation',
            name='incomplete_data',
            field=models.BooleanField(default=False, verbose_name='disaggregation data is incomplete'),
        ),
    ]
