# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-25 14:15


import akvo.rsr.models.partner_site
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0155_disaggregation_incomplete_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnersite',
            name='custom_map_marker',
            field=models.FileField(blank=True, help_text='Upload an image file to use as the map marker', upload_to=akvo.rsr.models.partner_site.custom_map_marker_path, verbose_name='map marker'),
        ),
    ]
