# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-25 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0156_partnersite_custom_map_marker'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnersite',
            name='tagline',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='tagline'),
        ),
    ]
