# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-12 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0157_partnersite_tagline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorperioddata',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data', to='rsr.IndicatorPeriod', verbose_name='indicator period'),
        ),
    ]
