# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-24 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0159_partnersite_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorPeriodDisaggregation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='quantitative disaggregated value')),
                ('numerator', models.DecimalField(blank=True, decimal_places=2, help_text='The numerator for a percentage value', max_digits=20, null=True, verbose_name='numerator for indicator')),
                ('denominator', models.DecimalField(blank=True, decimal_places=2, help_text='The denominator for a percentage value', max_digits=20, null=True, verbose_name='denominator for indicator')),
                ('dimension_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_disaggregations', to='rsr.IndicatorDimensionValue')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disaggregations', to='rsr.IndicatorPeriod', verbose_name='indicator period')),
            ],
            options={
                'ordering': ('id',),
                'verbose_name': 'period disaggregation',
                'verbose_name_plural': 'period disaggregations',
            },
        ),
    ]
