# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-30 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0161_migrate_period_disaggregations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disaggregation',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='quantitative update value'),
        ),
        migrations.AlterField(
            model_name='indicatorperioddata',
            name='denominator',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The denominator for a percentage value', max_digits=20, null=True, verbose_name='denominator for indicator'),
        ),
        migrations.AlterField(
            model_name='indicatorperioddata',
            name='numerator',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The numerator for a percentage value', max_digits=20, null=True, verbose_name='numerator for indicator'),
        ),
        migrations.AlterField(
            model_name='indicatorperioddata',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='quantitative update value'),
        ),
        migrations.AlterField(
            model_name='indicatorperioddisaggregation',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='quantitative update value'),
        ),
    ]
