# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-15 12:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0164_disaggregationtarget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicatorperiodactualdimension',
            name='period',
        ),
        migrations.RemoveField(
            model_name='indicatorperiodtargetdimension',
            name='period',
        ),
        migrations.DeleteModel(
            name='IndicatorPeriodActualDimension',
        ),
        migrations.DeleteModel(
            name='IndicatorPeriodTargetDimension',
        ),
    ]
