# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-24 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0165_auto_20190515_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisaggregationContribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='quantitative update value')),
                ('numerator', models.DecimalField(blank=True, decimal_places=2, help_text='The numerator for a percentage value', max_digits=20, null=True, verbose_name='numerator for indicator')),
                ('denominator', models.DecimalField(blank=True, decimal_places=2, help_text='The denominator for a percentage value', max_digits=20, null=True, verbose_name='denominator for indicator')),
                ('contributing_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disaggregation_contributions', to='rsr.Project')),
                ('disaggregation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='rsr.IndicatorPeriodDisaggregation')),
            ],
            options={
                'ordering': ('id',),
                'verbose_name': 'disaggregation contribution',
                'verbose_name_plural': 'disaggregation contributions',
            },
        ),
    ]
