# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-25 09:44


import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0165_auto_20190515_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='descriptions_order',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=['project_plan_summary', 'goals_overview', 'background', 'current_status', 'target_group', 'project_plan', 'sustainability']),
        ),
    ]
