# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-13 08:23
from __future__ import unicode_literals

import akvo.rsr.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0168_migrate_disaggregation_contributions'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationcustomfield',
            name='dropdown_options',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='List of options for the dropdown fields. Leave empty if field is not a dropdown', null=True, verbose_name='dropdown options'),
        ),
        migrations.AddField(
            model_name='organisationcustomfield',
            name='show_in_searchbar',
            field=models.BooleanField(default=False, help_text='Indicate whether this field is show in the partner site search bar', verbose_name='show in searchbar'),
        ),
        migrations.AddField(
            model_name='projectcustomfield',
            name='dropdown_options',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='dropdown options'),
        ),
        migrations.AddField(
            model_name='projectcustomfield',
            name='dropdown_selection',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='dropdown selection'),
        ),
        migrations.AlterField(
            model_name='organisationcustomfield',
            name='type',
            field=akvo.rsr.fields.ValidXMLCharField(choices=[(b'text', 'Text'), (b'boolean', 'Checkbox'), (b'dropdown', 'Dropdown')], default=b'text', help_text='Select the type of custom field. Text will show a text area in the project editor, and checkbox will show a checkbox.', max_length=20, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='projectcustomfield',
            name='type',
            field=akvo.rsr.fields.ValidXMLCharField(choices=[(b'text', 'Text'), (b'boolean', 'Checkbox'), (b'dropdown', 'Dropdown')], default=b'text', help_text='Select the type of custom field. Text will show a text area in the project editor, and checkbox will show a checkbox.', max_length=20, verbose_name='type'),
        ),
    ]
