# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-25 13:53


import akvo.rsr.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0170_defaultperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iatiexport',
            name='version',
            field=akvo.rsr.fields.ValidXMLCharField(default='2.03', max_length=4, verbose_name='version'),
        ),
        migrations.AlterField(
            model_name='iatiimport',
            name='enabled',
            field=models.BooleanField(default=False, help_text='Set to enable running of this import.', verbose_name='importing enabled'),
        ),
        migrations.AlterField(
            model_name='iatiimport',
            name='frequency',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'hourly'), (2, 'every six hours'), (3, 'daily'), (4, 'every three days'), (5, 'weekly'), (6, 'bi-weekly'), (7, 'every four weeks'), (8, 'every two minutes')], help_text='Set the frequency interval of the import', null=True),
        ),
        migrations.AlterField(
            model_name='iatiimport',
            name='mapper_prefix',
            field=models.CharField(blank=True, choices=[('Cordaid', 'Cordaid'), ('CordaidZip', 'CordaidZip'), ('ICCO', 'ICCO'), ('Result_only', 'Result_only')], help_text='Choose a custom mapper to invoke custom behaviour for this import', max_length=30, verbose_name='Custom mappers'),
        ),
        migrations.AlterField(
            model_name='iatiimport',
            name='run_immediately',
            field=models.BooleanField(default=False, help_text='Run the job immediately.', verbose_name='run immediately'),
        ),
        migrations.AlterField(
            model_name='iatiimport',
            name='running',
            field=models.BooleanField(default=False, help_text='Running is set while the import executes. This is to guarantee that the same import never runs twice (or more) in parallel.', verbose_name='import currently running'),
        ),
        migrations.AlterField(
            model_name='iatiimportlog',
            name='field',
            field=akvo.rsr.fields.ValidXMLCharField(default='', max_length=100, verbose_name='field'),
        ),
        migrations.AlterField(
            model_name='iatiimportlog',
            name='model',
            field=akvo.rsr.fields.ValidXMLCharField(default='', max_length=255, verbose_name='model'),
        ),
        migrations.AlterField(
            model_name='iatiimportlog',
            name='tag',
            field=akvo.rsr.fields.ValidXMLCharField(default='', max_length=100, verbose_name='xml tag'),
        ),
        migrations.AlterField(
            model_name='indicatorperioddata',
            name='period_actual_value',
            field=akvo.rsr.fields.ValidXMLCharField(default='', max_length=50, verbose_name='period actual value'),
        ),
        migrations.AlterField(
            model_name='indicatorperioddata',
            name='update_method',
            field=akvo.rsr.fields.ValidXMLCharField(blank=True, choices=[('W', 'web'), ('M', 'mobile')], db_index=True, default='W', max_length=1, verbose_name='update method'),
        ),
        migrations.AlterField(
            model_name='link',
            name='kind',
            field=akvo.rsr.fields.ValidXMLCharField(choices=[('A', 'Akvopedia entry'), ('E', 'External link')], default='E', max_length=1, verbose_name='kind'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='currency',
            field=akvo.rsr.fields.ValidXMLCharField(choices=[('AED', 'AED - UAE Dirham'), ('AFN', 'AFN - Afghani'), ('ALL', 'ALL - Lek'), ('AMD', 'AMD - Armenian Dram'), ('ANG', 'ANG - Netherlands Antillian Guilder'), ('AOA', 'AOA - Kwanza'), ('ARS', 'ARS - Argentine Peso'), ('AUD', 'AUD - Australian Dollar'), ('AWG', 'AWG - Aruban Guilder'), ('AZN', 'AZN - Azerbaijanian Manat'), ('BAM', 'BAM - Convertible Marks'), ('BBD', 'BBD - Barbados Dollar'), ('BDT', 'BDT - Taka'), ('BGN', 'BGN - Bulgarian Lev'), ('BHD', 'BHD - Bahraini Dinar'), ('BIF', 'BIF - Burundi Franc'), ('BMD', 'BMD - Bermudian Dollar'), ('BND', 'BND - Brunei Dollar'), ('BOB', 'BOB - Boliviano'), ('BOV', 'BOV - Mvdol'), ('BRL', 'BRL - Brazilian Real'), ('BSD', 'BSD - Bahamian Dollar'), ('BTN', 'BTN - Ngultrum'), ('BWP', 'BWP - Pula'), ('BYR', 'BYR - Belarussian Ruble'), ('BZD', 'BZD - Belize Dollar'), ('CAD', 'CAD - Canadian Dollar'), ('CDF', 'CDF - Congolese Franc'), ('CHF', 'CHF - Swiss Franc'), ('CLF', 'CLF - Unidades de fomento'), ('CLP', 'CLP - Chilean Peso'), ('CNY', 'CNY - Yuan Renminbi'), ('COP', 'COP - Colombian Peso'), ('COU', 'COU - Unidad de Valor Real'), ('CRC', 'CRC - Costa Rican Colon'), ('CUC', 'CUC - Peso Convertible'), ('CUP', 'CUP - Cuban Peso'), ('CVE', 'CVE - Cape Verde Escudo'), ('CZK', 'CZK - Czech Koruna'), ('DJF', 'DJF - Djibouti Franc'), ('DKK', 'DKK - Danish Krone'), ('DOP', 'DOP - Dominican Peso'), ('DZD', 'DZD - Algerian Dinar'), ('EEK', 'EEK - Kroon'), ('EGP', 'EGP - Egyptian Pound'), ('ERN', 'ERN - Nakfa'), ('ETB', 'ETB - Ethiopian Birr'), ('EUR', 'EUR - Euro'), ('FJD', 'FJD - Fiji Dollar'), ('FKP', 'FKP - Falkland Islands Pound'), ('GBP', 'GBP - Pound Sterling'), ('GEL', 'GEL - Lari'), ('GHS', 'GHS - Cedi'), ('GIP', 'GIP - Gibraltar Pound'), ('GMD', 'GMD - Dalasi'), ('GNF', 'GNF - Guinea Franc'), ('GTQ', 'GTQ - Quetzal'), ('GYD', 'GYD - Guyana Dollar'), ('HKD', 'HKD - Hong Kong Dollar'), ('HNL', 'HNL - Lempira'), ('HRK', 'HRK - Kuna'), ('HTG', 'HTG - Gourde'), ('HUF', 'HUF - Forint'), ('IDR', 'IDR - Rupiah'), ('ILS', 'ILS - New Israeli Sheqel'), ('INR', 'INR - Indian Rupee'), ('IQD', 'IQD - Iraqi Dinar'), ('IRR', 'IRR - Iranian Rial'), ('ISK', 'ISK - Iceland Krona'), ('JMD', 'JMD - Jamaican Dollar'), ('JOD', 'JOD - Jordanian Dinar'), ('JPY', 'JPY - Yen'), ('KES', 'KES - Kenyan Shilling'), ('KGS', 'KGS - Som'), ('KHR', 'KHR - Riel'), ('KMF', 'KMF - Comoro Franc'), ('KPW', 'KPW - North Korean Won'), ('KRW', 'KRW - Won'), ('KWD', 'KWD - Kuwaiti Dinar'), ('KYD', 'KYD - Cayman Islands Dollar'), ('KZT', 'KZT - Tenge'), ('LAK', 'LAK - Kip'), ('LBP', 'LBP - Lebanese Pound'), ('LKR', 'LKR - Sri Lanka Rupee'), ('LRD', 'LRD - Liberian Dollar'), ('LSL', 'LSL - Loti'), ('LTL', 'LTL - Lithuanian Litas'), ('LVL', 'LVL - Latvian Lats'), ('LYD', 'LYD - Libyan Dinar'), ('MAD', 'MAD - Moroccan Dirham'), ('MDL', 'MDL - Moldovan Leu'), ('MGA', 'MGA - Malagasy Ariary'), ('MKD', 'MKD - Denar'), ('MMK', 'MMK - Kyat'), ('MNT', 'MNT - Tugrik'), ('MOP', 'MOP - Pataca'), ('MRO', 'MRO - Ouguiya'), ('MUR', 'MUR - Mauritius Rupee'), ('MVR', 'MVR - Rufiyaa'), ('MWK', 'MWK - Malawi Kwacha'), ('MXN', 'MXN - Mexican Peso'), ('MXV', 'MXV - Mexican Unidad de Inversion (UDI)'), ('MYR', 'MYR - Malaysian Ringgit'), ('MZN', 'MZN - Metical'), ('NAD', 'NAD - Namibia Dollar'), ('NGN', 'NGN - Naira'), ('NIO', 'NIO - Cordoba Oro'), ('NOK', 'NOK - Norwegian Krone'), ('NPR', 'NPR - Nepalese Rupee'), ('NZD', 'NZD - New Zealand Dollar'), ('OMR', 'OMR - Rial Omani'), ('PAB', 'PAB - Balboa'), ('PEN', 'PEN - Nuevo Sol'), ('PGK', 'PGK - Kina'), ('PHP', 'PHP - Philippine Peso'), ('PKR', 'PKR - Pakistan Rupee'), ('PLN', 'PLN - Zloty'), ('PYG', 'PYG - Guarani'), ('QAR', 'QAR - Qatari Rial'), ('RON', 'RON - Romanian Leu'), ('RSD', 'RSD - Serbian Dinar'), ('RUB', 'RUB - Russian Ruble'), ('RWF', 'RWF - Rwanda Franc'), ('SAR', 'SAR - Saudi Riyal'), ('SBD', 'SBD - Solomon Islands Dollar'), ('SCR', 'SCR - Seychelles Rupee'), ('SDG', 'SDG - Sudanese Pound'), ('SEK', 'SEK - Swedish Krona'), ('SGD', 'SGD - Singapore Dollar'), ('SHP', 'SHP - Saint Helena Pound'), ('SLL', 'SLL - Leone'), ('SOS', 'SOS - Somali Shilling'), ('SSP', 'SSP - South Sudanese Pound'), ('SRD', 'SRD - Surinam Dollar'), ('STD', 'STD - Dobra'), ('SVC', 'SVC - El Salvador Colon'), ('SYP', 'SYP - Syrian Pound'), ('SZL', 'SZL - Lilangeni'), ('THB', 'THB - Baht'), ('TJS', 'TJS - Somoni'), ('TMT', 'TMT - Manat'), ('TND', 'TND - Tunisian Dinar'), ('TOP', 'TOP - Paanga'), ('TRY', 'TRY - Turkish Lira'), ('TTD', 'TTD - Trinidad and Tobago Dollar'), ('TWD', 'TWD - New Taiwan Dollar'), ('TZS', 'TZS - Tanzanian Shilling'), ('UAH', 'UAH - Hryvnia'), ('UGX', 'UGX - Uganda Shilling'), ('USD', 'USD - US Dollar'), ('USN', 'USN - US Dollar (Next day)'), ('USS', 'USS - US Dollar (Same day)'), ('UYI', 'UYI - Uruguay Peso en Unidades Indexadas'), ('UYU', 'UYU - Peso Uruguayo'), ('UZS', 'UZS - Uzbekistan Sum'), ('VEF', 'VEF - Bolivar'), ('VND', 'VND - Dong'), ('VUV', 'VUV - Vatu'), ('WST', 'WST - Tala'), ('XAF', 'XAF - CFA Franc BEAC'), ('XBT', 'XBT - Bitcoin'), ('XCD', 'XCD - East Caribbean Dollar'), ('XDR', 'XDR - International Monetary Fund (IMF) Special Drawing Right (SDR)'), ('XOF', 'XOF - CFA Franc BCEAO'), ('XPF', 'XPF - CFP Franc'), ('YER', 'YER - Yemeni Rial'), ('ZAR', 'ZAR - Rand'), ('ZMK', 'ZMK - Zambian Kwacha'), ('ZWL', 'ZWL - Zimbabwe Dollar')], default='EUR', help_text='The default currency for this organisation. Used in all financial aspects of the organisation.', max_length=3, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='language',
            field=akvo.rsr.fields.ValidXMLCharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French')], default='en', help_text='The main language of the organisation', max_length=2, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='notes',
            field=akvo.rsr.fields.ValidXMLTextField(blank=True, default='', verbose_name='Notes and comments'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='organisation_type',
            field=akvo.rsr.fields.ValidXMLCharField(blank=True, choices=[('N', 'NGO'), ('G', 'Governmental'), ('C', 'Commercial'), ('K', 'Knowledge institution')], db_index=True, max_length=1, null=True, verbose_name='organisation type'),
        ),
        migrations.AlterField(
            model_name='organisationaccount',
            name='account_level',
            field=akvo.rsr.fields.ValidXMLCharField(choices=[('archived', 'Free'), ('freemium', 'Freemium'), ('premium', 'Premium'), ('plus', 'Premium Plus'), ('archived', 'Archived')], default='archived', max_length=12, verbose_name='account level'),
        ),
        migrations.AlterField(
            model_name='organisationcustomfield',
            name='type',
            field=akvo.rsr.fields.ValidXMLCharField(choices=[('text', 'Text'), ('boolean', 'Checkbox'), ('dropdown', 'Dropdown')], default='text', help_text='Select the type of custom field. Text will show a text area in the project editor, and checkbox will show a checkbox.', max_length=20, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='partnersite',
            name='custom_return_url_text',
            field=akvo.rsr.fields.ValidXMLCharField(blank=True, default='', help_text='<p>Enter a text for the back button and return URL. Leave empty to display "Back to <em>myorganisation</em>".</p>', max_length=50, verbose_name='Return URL text'),
        ),
        migrations.AlterField(
            model_name='partnersite',
            name='default_language',
            field=akvo.rsr.fields.ValidXMLCharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French')], default='en', max_length=5, verbose_name='Site UI default language'),
        ),
        migrations.AlterField(
            model_name='partnersite',
            name='notes',
            field=akvo.rsr.fields.ValidXMLTextField(blank=True, default='', verbose_name='Akvo page notes'),
        ),
        migrations.AlterField(
            model_name='project',
            name='currency',
            field=akvo.rsr.fields.ValidXMLCharField(choices=[('AED', 'AED - UAE Dirham'), ('AFN', 'AFN - Afghani'), ('ALL', 'ALL - Lek'), ('AMD', 'AMD - Armenian Dram'), ('ANG', 'ANG - Netherlands Antillian Guilder'), ('AOA', 'AOA - Kwanza'), ('ARS', 'ARS - Argentine Peso'), ('AUD', 'AUD - Australian Dollar'), ('AWG', 'AWG - Aruban Guilder'), ('AZN', 'AZN - Azerbaijanian Manat'), ('BAM', 'BAM - Convertible Marks'), ('BBD', 'BBD - Barbados Dollar'), ('BDT', 'BDT - Taka'), ('BGN', 'BGN - Bulgarian Lev'), ('BHD', 'BHD - Bahraini Dinar'), ('BIF', 'BIF - Burundi Franc'), ('BMD', 'BMD - Bermudian Dollar'), ('BND', 'BND - Brunei Dollar'), ('BOB', 'BOB - Boliviano'), ('BOV', 'BOV - Mvdol'), ('BRL', 'BRL - Brazilian Real'), ('BSD', 'BSD - Bahamian Dollar'), ('BTN', 'BTN - Ngultrum'), ('BWP', 'BWP - Pula'), ('BYR', 'BYR - Belarussian Ruble'), ('BZD', 'BZD - Belize Dollar'), ('CAD', 'CAD - Canadian Dollar'), ('CDF', 'CDF - Congolese Franc'), ('CHF', 'CHF - Swiss Franc'), ('CLF', 'CLF - Unidades de fomento'), ('CLP', 'CLP - Chilean Peso'), ('CNY', 'CNY - Yuan Renminbi'), ('COP', 'COP - Colombian Peso'), ('COU', 'COU - Unidad de Valor Real'), ('CRC', 'CRC - Costa Rican Colon'), ('CUC', 'CUC - Peso Convertible'), ('CUP', 'CUP - Cuban Peso'), ('CVE', 'CVE - Cape Verde Escudo'), ('CZK', 'CZK - Czech Koruna'), ('DJF', 'DJF - Djibouti Franc'), ('DKK', 'DKK - Danish Krone'), ('DOP', 'DOP - Dominican Peso'), ('DZD', 'DZD - Algerian Dinar'), ('EEK', 'EEK - Kroon'), ('EGP', 'EGP - Egyptian Pound'), ('ERN', 'ERN - Nakfa'), ('ETB', 'ETB - Ethiopian Birr'), ('EUR', 'EUR - Euro'), ('FJD', 'FJD - Fiji Dollar'), ('FKP', 'FKP - Falkland Islands Pound'), ('GBP', 'GBP - Pound Sterling'), ('GEL', 'GEL - Lari'), ('GHS', 'GHS - Cedi'), ('GIP', 'GIP - Gibraltar Pound'), ('GMD', 'GMD - Dalasi'), ('GNF', 'GNF - Guinea Franc'), ('GTQ', 'GTQ - Quetzal'), ('GYD', 'GYD - Guyana Dollar'), ('HKD', 'HKD - Hong Kong Dollar'), ('HNL', 'HNL - Lempira'), ('HRK', 'HRK - Kuna'), ('HTG', 'HTG - Gourde'), ('HUF', 'HUF - Forint'), ('IDR', 'IDR - Rupiah'), ('ILS', 'ILS - New Israeli Sheqel'), ('INR', 'INR - Indian Rupee'), ('IQD', 'IQD - Iraqi Dinar'), ('IRR', 'IRR - Iranian Rial'), ('ISK', 'ISK - Iceland Krona'), ('JMD', 'JMD - Jamaican Dollar'), ('JOD', 'JOD - Jordanian Dinar'), ('JPY', 'JPY - Yen'), ('KES', 'KES - Kenyan Shilling'), ('KGS', 'KGS - Som'), ('KHR', 'KHR - Riel'), ('KMF', 'KMF - Comoro Franc'), ('KPW', 'KPW - North Korean Won'), ('KRW', 'KRW - Won'), ('KWD', 'KWD - Kuwaiti Dinar'), ('KYD', 'KYD - Cayman Islands Dollar'), ('KZT', 'KZT - Tenge'), ('LAK', 'LAK - Kip'), ('LBP', 'LBP - Lebanese Pound'), ('LKR', 'LKR - Sri Lanka Rupee'), ('LRD', 'LRD - Liberian Dollar'), ('LSL', 'LSL - Loti'), ('LTL', 'LTL - Lithuanian Litas'), ('LVL', 'LVL - Latvian Lats'), ('LYD', 'LYD - Libyan Dinar'), ('MAD', 'MAD - Moroccan Dirham'), ('MDL', 'MDL - Moldovan Leu'), ('MGA', 'MGA - Malagasy Ariary'), ('MKD', 'MKD - Denar'), ('MMK', 'MMK - Kyat'), ('MNT', 'MNT - Tugrik'), ('MOP', 'MOP - Pataca'), ('MRO', 'MRO - Ouguiya'), ('MUR', 'MUR - Mauritius Rupee'), ('MVR', 'MVR - Rufiyaa'), ('MWK', 'MWK - Malawi Kwacha'), ('MXN', 'MXN - Mexican Peso'), ('MXV', 'MXV - Mexican Unidad de Inversion (UDI)'), ('MYR', 'MYR - Malaysian Ringgit'), ('MZN', 'MZN - Metical'), ('NAD', 'NAD - Namibia Dollar'), ('NGN', 'NGN - Naira'), ('NIO', 'NIO - Cordoba Oro'), ('NOK', 'NOK - Norwegian Krone'), ('NPR', 'NPR - Nepalese Rupee'), ('NZD', 'NZD - New Zealand Dollar'), ('OMR', 'OMR - Rial Omani'), ('PAB', 'PAB - Balboa'), ('PEN', 'PEN - Nuevo Sol'), ('PGK', 'PGK - Kina'), ('PHP', 'PHP - Philippine Peso'), ('PKR', 'PKR - Pakistan Rupee'), ('PLN', 'PLN - Zloty'), ('PYG', 'PYG - Guarani'), ('QAR', 'QAR - Qatari Rial'), ('RON', 'RON - Romanian Leu'), ('RSD', 'RSD - Serbian Dinar'), ('RUB', 'RUB - Russian Ruble'), ('RWF', 'RWF - Rwanda Franc'), ('SAR', 'SAR - Saudi Riyal'), ('SBD', 'SBD - Solomon Islands Dollar'), ('SCR', 'SCR - Seychelles Rupee'), ('SDG', 'SDG - Sudanese Pound'), ('SEK', 'SEK - Swedish Krona'), ('SGD', 'SGD - Singapore Dollar'), ('SHP', 'SHP - Saint Helena Pound'), ('SLL', 'SLL - Leone'), ('SOS', 'SOS - Somali Shilling'), ('SSP', 'SSP - South Sudanese Pound'), ('SRD', 'SRD - Surinam Dollar'), ('STD', 'STD - Dobra'), ('SVC', 'SVC - El Salvador Colon'), ('SYP', 'SYP - Syrian Pound'), ('SZL', 'SZL - Lilangeni'), ('THB', 'THB - Baht'), ('TJS', 'TJS - Somoni'), ('TMT', 'TMT - Manat'), ('TND', 'TND - Tunisian Dinar'), ('TOP', 'TOP - Paanga'), ('TRY', 'TRY - Turkish Lira'), ('TTD', 'TTD - Trinidad and Tobago Dollar'), ('TWD', 'TWD - New Taiwan Dollar'), ('TZS', 'TZS - Tanzanian Shilling'), ('UAH', 'UAH - Hryvnia'), ('UGX', 'UGX - Uganda Shilling'), ('USD', 'USD - US Dollar'), ('USN', 'USN - US Dollar (Next day)'), ('USS', 'USS - US Dollar (Same day)'), ('UYI', 'UYI - Uruguay Peso en Unidades Indexadas'), ('UYU', 'UYU - Peso Uruguayo'), ('UZS', 'UZS - Uzbekistan Sum'), ('VEF', 'VEF - Bolivar'), ('VND', 'VND - Dong'), ('VUV', 'VUV - Vatu'), ('WST', 'WST - Tala'), ('XAF', 'XAF - CFA Franc BEAC'), ('XBT', 'XBT - Bitcoin'), ('XCD', 'XCD - East Caribbean Dollar'), ('XDR', 'XDR - International Monetary Fund (IMF) Special Drawing Right (SDR)'), ('XOF', 'XOF - CFA Franc BCEAO'), ('XPF', 'XPF - CFP Franc'), ('YER', 'YER - Yemeni Rial'), ('ZAR', 'ZAR - Rand'), ('ZMK', 'ZMK - Zambian Kwacha'), ('ZWL', 'ZWL - Zimbabwe Dollar')], default='EUR', help_text='The default currency for this project. Used in all financial aspects of the project.', max_length=3, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='project',
            name='default_aid_type_vocabulary',
            field=akvo.rsr.fields.ValidXMLCharField(blank=True, choices=[('1', '1 - OECD DAC'), ('2', '2 - Earmarking Category'), ('3', '3 - Earmarking Modality')], default='1', help_text='This is the IATI identifier for the type of vocabulary being used for describing the type of the aid being supplied or activity being undertaken. For reference, please visit: <a href="http://iatistandard.org/203/codelists/AidTypeVocabulary/" target="_blank"> http://iatistandard.org/203/codelists/AidTypeVocabulary/</a>.', max_length=1, verbose_name='default aid type vocabulary'),
        ),
        migrations.AlterField(
            model_name='project',
            name='descriptions_order',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=['project_plan_summary', 'goals_overview', 'background', 'current_status', 'target_group', 'project_plan', 'sustainability']),
        ),
        migrations.AlterField(
            model_name='project',
            name='language',
            field=akvo.rsr.fields.ValidXMLCharField(blank=True, choices=[('de', 'German'), ('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('nl', 'Dutch'), ('ru', 'Russian')], help_text='Enter the language used when entering the details for this project.', max_length=2),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=akvo.rsr.fields.ValidXMLCharField(choices=[('N', ''), ('H', 'Needs funding'), ('A', 'Active'), ('C', 'Complete'), ('L', 'Cancelled'), ('R', 'Archived')], db_index=True, default='N', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='projectcustomfield',
            name='type',
            field=akvo.rsr.fields.ValidXMLCharField(choices=[('text', 'Text'), ('boolean', 'Checkbox'), ('dropdown', 'Dropdown')], default='text', help_text='Select the type of custom field. Text will show a text area in the project editor, and checkbox will show a checkbox.', max_length=20, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='projectupdate',
            name='language',
            field=akvo.rsr.fields.ValidXMLCharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French')], default='en', help_text='The language of the update', max_length=2),
        ),
        migrations.AlterField(
            model_name='projectupdate',
            name='notes',
            field=akvo.rsr.fields.ValidXMLTextField(blank=True, default='', verbose_name='Notes and comments'),
        ),
        migrations.AlterField(
            model_name='projectupdate',
            name='update_method',
            field=akvo.rsr.fields.ValidXMLCharField(blank=True, choices=[('W', 'web'), ('E', 'e-mail'), ('S', 'SMS'), ('M', 'mobile')], db_index=True, default='W', max_length=1, verbose_name='update method'),
        ),
        migrations.AlterField(
            model_name='projectupdate',
            name='user_agent',
            field=akvo.rsr.fields.ValidXMLCharField(blank=True, default='', max_length=200, verbose_name='user agent'),
        ),
        migrations.AlterField(
            model_name='projectupdate',
            name='uuid',
            field=akvo.rsr.fields.ValidXMLCharField(blank=True, db_index=True, default='', help_text='Universally unique ID set by creating user agent', max_length=40, verbose_name='uuid'),
        ),
        migrations.AlterField(
            model_name='publishingstatus',
            name='status',
            field=akvo.rsr.fields.ValidXMLCharField(choices=[('unpublished', 'Unpublished'), ('published', 'Published')], db_index=True, default='unpublished', max_length=30),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='aid_type_vocabulary',
            field=akvo.rsr.fields.ValidXMLCharField(blank=True, choices=[('1', '1 - OECD DAC'), ('2', '2 - Earmarking Category'), ('3', '3 - Earmarking Modality')], default='1', help_text='Enter the type of vocabulary being used to describe the aid type For reference, please visit: <a href="http://iatistandard.org/203/codelists/AidTypeVocabulary/" target="_blank"> http://iatistandard.org/203/codelists/AidTypeVocabulary/</a>.', max_length=1, verbose_name='transaction aid type vocabulary'),
        ),
        migrations.AlterField(
            model_name='user',
            name='notes',
            field=akvo.rsr.fields.ValidXMLTextField(blank=True, default='', verbose_name='Notes and comments'),
        ),
    ]
