# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-12 09:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0171_auto_20191225_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='group')),
            ],
            options={
                'verbose_name': 'project role',
                'verbose_name_plural': 'project roles',
            },
        ),
        migrations.AddField(
            model_name='organisation',
            name='use_project_roles',
            field=models.BooleanField(default=False, help_text='Projects with this organisation as reporting partner will use projectroles for permissions instead of employment based permissions', verbose_name='use project roles'),
        ),
        migrations.AddField(
            model_name='project',
            name='use_project_roles',
            field=models.BooleanField(default=False, help_text='Toggle between using project roles and employment based permissions', verbose_name='use project roles'),
        ),
        migrations.AddField(
            model_name='projectrole',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsr.Project', verbose_name='project'),
        ),
        migrations.AddField(
            model_name='projectrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterUniqueTogether(
            name='projectrole',
            unique_together=set([('project', 'user', 'group')]),
        ),
    ]
