# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-20 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0172_add_project_role'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='indicatordimensionname',
            unique_together=set([]),
        ),
    ]
