# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-29 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0173_auto_20200420_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='enforce_program_projects',
            field=models.BooleanField(
                default=False,
                help_text=('Enforce creation of projects only under programs. If the organisation has '
                           'explicitly set a content owner, this flag remains in sync with the content owner')),
        ),
    ]
