# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-16 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0175_partnersite_piwik_id_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcomment',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectcomment',
            name='user',
        ),
        migrations.DeleteModel(
            name='ProjectComment',
        ),
    ]
