# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-07-20 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0176_auto_20200616_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='target_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The target value for all reporting periods in this indicator.', max_digits=20, null=True, verbose_name='target value'),
        ),
    ]
