# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-08-04 09:36
from __future__ import unicode_literals

import akvo.rsr.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0177_indicator_target_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='target_comment',
            field=akvo.rsr.fields.ValidXMLCharField(blank=True, help_text='Here you can provide extra information on the target value, if needed.', max_length=2000, verbose_name='target value comment'),
        ),
    ]
