# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-08-04 13:59
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0178_indicator_target_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='seen_announcements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=[], size=None),
        ),
    ]
