# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-08-10 23:58
from __future__ import unicode_literals

from django.db import migrations


def migrate_program_reports(apps, schema_editor):
    Report = apps.get_model('rsr', 'Report')
    ReportFormat = apps.get_model('rsr', 'ReportFormat')

    reports = Report.objects.filter(url__icontains='{organisation}').filter(url__icontains='program=true')
    for report in reports:
        report.url = report.url.replace('&program=true', '').replace('/organisation/{organisation}', '/program/{program}')
        report.save()

    new_report = Report.objects.create(
        name='program-overview-table',
        title='Program overview table',
        description="This report gives an overview of your program",
        url="/py-reports/program/{program}/program-overview-table/?format={format}&download=true")

    new_report.formats.add(ReportFormat.objects.get(name='excel'))


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0180_projecthierarchy_is_master'),
    ]

    operations = [
        migrations.RunPython(migrate_program_reports)
    ]
