# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-08-10 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0181_program_reports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprojects',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='userprojects',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProjects',
        ),
    ]
