# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-08-20 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0183_remove_organisation_enable_restrictions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecthierarchy',
            options={'ordering': ['-id'], 'verbose_name': 'program', 'verbose_name_plural': 'programs'},
        ),
    ]
