# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-08-12 11:09
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0184_auto_20200820_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='scores',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=[], size=None),
        ),
    ]
