# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-08-17 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0185_indicator_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorperiod',
            name='score_index',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='score index'),
        ),
        migrations.AddField(
            model_name='indicatorperioddata',
            name='score_index',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='score index'),
        ),
    ]
