# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-08-24 10:42
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0186_auto_20200817_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='scores',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), default=[], size=None),
        ),
    ]
