# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-22 01:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0187_auto_20200824_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=1, help_text="Percentages should add up to 100%% of the activity being reported if they are shown for each sector. Fill in 100%% if there's one sector. Use a period to denote decimals.", max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='sector percentage'),
        ),
    ]
