# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-28 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0192_iatiexport_latest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iatiexport',
            name='is_public',
        ),
    ]
