# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-12 06:17
from __future__ import unicode_literals

import akvo.rsr.models.result.indicator_period_data
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0194_auto_20201109_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorPeriodDataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to=akvo.rsr.models.result.indicator_period_data.update_file_path, verbose_name='file')),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsr.IndicatorPeriodData')),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorPeriodDataPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', sorl.thumbnail.fields.ImageField(max_length=255, upload_to=akvo.rsr.models.result.indicator_period_data.update_image_path, verbose_name='photo')),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsr.IndicatorPeriodData')),
            ],
        ),
    ]
