# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-18 23:33
from __future__ import unicode_literals

import akvo.rsr.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0195_auto_20201112_0617'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorCustomField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', akvo.rsr.fields.ValidXMLTextField(verbose_name='name')),
                ('order', models.PositiveSmallIntegerField(default=1, help_text='The order of the fields as they will be displayed in the project editor. Must be a positive number, and the lowest number will be shown on top.', verbose_name='order')),
                ('mandatory', models.BooleanField(default=False, help_text='Indicate whether this field is mandatory or not', verbose_name='mandatory')),
                ('help_text', akvo.rsr.fields.ValidXMLTextField(blank=True, help_text='The help text to be displayed with the field in the admin. Leave empty if there is no need for a help text. (max 1000 characters)', max_length=1000, verbose_name='help text')),
                ('type', akvo.rsr.fields.ValidXMLCharField(choices=[('text', 'Text'), ('boolean', 'Checkbox'), ('dropdown', 'Dropdown')], default='text', help_text='Select the type of custom field. Text will show a text area in the project editor, and checkbox will show a checkbox.', max_length=20, verbose_name='type')),
                ('dropdown_options', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='dropdown options')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_custom_fields', to='rsr.Project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'indicator custom field',
                'verbose_name_plural': 'indicator custom fields',
            },
        ),
        migrations.CreateModel(
            name='IndicatorCustomValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_value', akvo.rsr.fields.ValidXMLTextField(blank=True, verbose_name='text_value')),
                ('boolean_value', models.BooleanField(default=False, verbose_name='boolean_value')),
                ('dropdown_selection', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='dropdown selection')),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='rsr.IndicatorCustomField', verbose_name='custom_field')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_values', to='rsr.Indicator', verbose_name='indicator')),
            ],
            options={
                'verbose_name': 'indicator custom value',
                'verbose_name_plural': 'indicator custom values',
            },
        ),
    ]
