# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-12 09:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0196_indicatorcustomfield_indicatorcustomvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='enumerators',
            field=models.ManyToManyField(related_name='assigned_indicators', to=settings.AUTH_USER_MODEL),
        ),
    ]
