# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-20 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0197_indicator_enumerators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them. Use this only for RSR team members. For other Akvo users, use is_admin flag.', verbose_name='superuser status'),
        ),
    ]
