# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-09 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0198_auto_20201120_0535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecthierarchy',
            name='organisation',
        ),
    ]
