# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-14 14:14
from __future__ import unicode_literals

import akvo.rsr.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0199_remove_projecthierarchy_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='targets_at',
            field=akvo.rsr.fields.ValidXMLCharField(choices=[('period', 'Period'), ('indicator', 'Indicator'), ('both', 'Both')], default='period', help_text='Which project attributes that has a target value', max_length=9),
        ),
    ]
