# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-02 10:54
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0200_project_targets_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorperioddata',
            name='score_indices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), default=[], size=None),
        ),
    ]
