# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-03 10:28
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0201_indicatorperioddata_score_indices'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorperiod',
            name='score_indices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), default=[], size=None),
        ),
    ]
