# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-04 10:04
from __future__ import unicode_literals

import akvo.rsr.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0202_indicatorperiod_score_indices'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorperioddata',
            name='review_note',
            field=akvo.rsr.fields.ValidXMLTextField(blank=True, verbose_name='text'),
        ),
    ]
