# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-01 13:41
from __future__ import unicode_literals

import akvo.rsr.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0203_indicatorperioddata_review_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectupdate',
            name='photo_caption',
            field=akvo.rsr.fields.ValidXMLCharField(blank=True, help_text='1024 characters', max_length=1024, verbose_name='photo caption'),
        ),
        migrations.AlterField(
            model_name='projectupdate',
            name='photo_credit',
            field=akvo.rsr.fields.ValidXMLCharField(blank=True, help_text='1024 characters', max_length=1024, verbose_name='photo credit'),
        ),
        migrations.AlterField(
            model_name='projectupdate',
            name='title',
            field=akvo.rsr.fields.ValidXMLCharField(db_index=True, help_text='1024 characters', max_length=1024, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='projectupdate',
            name='video_caption',
            field=akvo.rsr.fields.ValidXMLCharField(blank=True, help_text='1024 characters', max_length=1024, verbose_name='video caption'),
        ),
        migrations.AlterField(
            model_name='projectupdate',
            name='video_credit',
            field=akvo.rsr.fields.ValidXMLCharField(blank=True, help_text='1024 characters', max_length=1024, verbose_name='video credit'),
        ),
    ]
