# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-07 06:19
from __future__ import unicode_literals

import akvo.rsr.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0204_auto_20210401_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectupdate',
            name='photo_caption',
            field=akvo.rsr.fields.ValidXMLTextField(blank=True, verbose_name='photo caption'),
        ),
        migrations.AlterField(
            model_name='projectupdate',
            name='photo_credit',
            field=akvo.rsr.fields.ValidXMLTextField(blank=True, verbose_name='photo credit'),
        ),
        migrations.AlterField(
            model_name='projectupdate',
            name='video_caption',
            field=akvo.rsr.fields.ValidXMLTextField(blank=True, verbose_name='video caption'),
        ),
        migrations.AlterField(
            model_name='projectupdate',
            name='video_credit',
            field=akvo.rsr.fields.ValidXMLTextField(blank=True, verbose_name='video credit'),
        ),
    ]
