# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-07 13:03
from __future__ import unicode_literals

from django.db import migrations


def make_report(apps, schema_editor):
    Report = apps.get_model('rsr', 'Report')
    ReportFormat = apps.get_model('rsr', 'ReportFormat')

    new_report = Report.objects.create(
        name='program-labeled-periods-overview',
        title='Program labeled periods overview',
        description="This report gives an overview of your program based on labeled periods.",
        url="/py-reports/program/{program}/program-labeled-periods-overview/?format={format}&download=true")

    new_report.formats.add(ReportFormat.objects.get(name='pdf'))


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0206_auto_20210318_2304'),
    ]

    operations = [
        migrations.RunPython(make_report)
    ]
