# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-12 10:11
from __future__ import unicode_literals

from django.db import migrations


def make_report(apps, schema_editor):
    Report = apps.get_model('rsr', 'Report')
    ReportFormat = apps.get_model('rsr', 'ReportFormat')

    new_report = Report.objects.create(
        name='nuffic-country-overview',
        title='Nuffic country level overview',
        description="This report gives an overview of projects in selected country.",
        url=(
            "/py-reports/program/{program}/nuffic-country-level-report/"
            "?format={format}&download=true&period_start={period_start}"
            "&period_end={period_end}&comment={comment}&country={country}"))

    new_report.formats.add(ReportFormat.objects.get(name='pdf'))


def drop_report(apps, schema_editor):
    Report = apps.get_model('rsr', 'Report')
    Report.objects.filter(name='nuffic-country-overview').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0207_labeled_period_report'),
    ]

    operations = [
        migrations.RunPython(make_report, drop_report)
    ]
