# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-26 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0209_partnersite_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='baseline_score',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='baseline score'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='target_score',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='target score'),
        ),
    ]
