# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-07 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0210_auto_20210426_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorperiod',
            name='target_score',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='target score'),
        ),
    ]
