# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-31 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0212_projectupdatephoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectupdatephoto',
            options={'ordering': ['id']},
        ),
    ]
