# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-04 11:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0214_eutf-common-indicators-report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitem',
            name='label',
            field=models.ForeignKey(blank=True, help_text='Select the budget item(s) to indicate how the project budget is divided. Use the ‘Other’ fields to add custom budget items.', null=True, on_delete=django.db.models.deletion.CASCADE, to='rsr.BudgetItemLabel', verbose_name='budget item'),
        ),
        migrations.AlterField(
            model_name='defaultperiod',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_periods', to='rsr.DefaultPeriod', verbose_name='parent period'),
        ),
        migrations.AlterField(
            model_name='disaggregation',
            name='dimension_value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disaggregations', to='rsr.IndicatorDimensionValue'),
        ),
        migrations.AlterField(
            model_name='indicatordimensionname',
            name='parent_dimension_name',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_dimension_names', to='rsr.IndicatorDimensionName', verbose_name='parent dimension name'),
        ),
        migrations.AlterField(
            model_name='indicatordimensionvalue',
            name='parent_dimension_value',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_dimension_values', to='rsr.IndicatorDimensionValue', verbose_name='parent dimension value'),
        ),
        migrations.AlterField(
            model_name='indicatordisaggregationtarget',
            name='dimension_value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicator_disaggregation_targets', to='rsr.IndicatorDimensionValue'),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='organisation',
            field=models.ForeignKey(blank=True, help_text='Select an organisation that is taking an active role in the project.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partnerships', to='rsr.Organisation', verbose_name='organisation'),
        ),
        migrations.AlterField(
            model_name='partnersite',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Select your program from the drop-down list.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rsr.ProjectHierarchy'),
        ),
        migrations.AlterField(
            model_name='projectcontact',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='rsr.Country', verbose_name='country'),
        ),
    ]
