# Generated by Django 3.2.10 on 2022-02-03 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0216_django_3_2_upgrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorperiod',
            name='parent_period',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_periods', to='rsr.indicatorperiod', verbose_name='parent indicator period'),
        ),
    ]
