# Generated by Django 3.2.10 on 2022-06-07 14:12

import akvo.rsr.models.project_thumbnail
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0217_cascade_indicator_period_deletes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectThumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', models.CharField(max_length=100, validators=[akvo.rsr.models.project_thumbnail.validate_geometry_string])),
                ('url', models.URLField()),
                ('full_size_url', models.URLField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='rsr.project')),
            ],
            options={
                'unique_together': {('project', 'full_size_url', 'geometry')},
            },
        ),
    ]
