# Generated by Django 3.2.8 on 2021-11-30 10:59
from sys import stderr, stdout

from django.db import migrations, models
import django_ltree.fields
import uuid

import akvo.rsr.fields
from akvo.rsr.management.commands.migrate_related_project_hierarchies import Migrator
from akvo.rsr.management.commands.migrate_external_projects import Migrator as ExternalProjectMigrator
from akvo.rsr.management.commands.migrate_related_project_contributors import Migrator as ContributorMigrator


def project_path_forward(apps, schema_editor):
    Project = apps.get_model("rsr", "Project")
    projects = list(Project.objects.all())
    for project in projects:
        project.uuid = uuid.uuid4()
        project.path = str(project.uuid).replace("-", "_")
    Project.objects.bulk_update(projects, ["path", "uuid"])

def project_hierarchies(apps, schema_editor):
    Migrator(
        stdout, stderr,
        apps.get_model("rsr", "Project"),
        apps.get_model("rsr", "RelatedProject"),
        apply=True,
    ).run()

def migrate_external_projects(apps, schema_editor):
    ExternalProjectMigrator(stdout, stderr, apply=True).run()

def migrate_contributing_projects(apps, schema_editor):
    ContributorMigrator(
        stdout, stderr,
        apps.get_model("rsr", "Project"),
        apps.get_model("rsr", "RelatedProject"),
        apply=True
    ).run()



class Migration(migrations.Migration):
    dependencies = [
        ('rsr', '0218_project_thumbnail_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='uuid',
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.AddField(
            model_name='project',
            name='path',
            field=django_ltree.fields.PathField(null=True),
            preserve_default=False,
        ),
        migrations.RunPython(project_path_forward),
        migrations.AlterField(
            model_name='project',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='path',
            field=django_ltree.fields.PathField(null=False, unique=True),
            preserve_default=False,
        ),
        migrations.RunPython(project_hierarchies),

        # Contributing parents
        migrations.AddField(
            model_name='project',
            name='contributes_to_project',
            field=models.ForeignKey(null=True, on_delete=models.deletion.SET_NULL, to='rsr.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='external_parent_iati_activity_id',
            field=akvo.rsr.fields.ValidXMLCharField(blank=True, db_index=True,
                                                    help_text='This is a globally unique identifier for an activity. It is a requirement to be compliant with the IATI standard. This code consists of: [country code]-[Chamber of Commerce number]-[organisation’s internal project code]. For Dutch organisations this is e.g. NL-KVK-31156201-TZ1234. For more information see <a href="http://iatistandard.org/202/activity-standard/iati-activities/iati-activity/iati-identifier/#definition" target="_blank">http://iatistandard.org/201/activity-standard/iati-activities/iati-activity/iati-identifier/#definition</a>',
                                                    max_length=100, null=True, verbose_name='IATI identifier'),
        ),
        migrations.RunPython(migrate_contributing_projects),

        # External contributing children
        migrations.CreateModel(
            name='ExternalProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('iati_id', akvo.rsr.fields.ValidXMLCharField(blank=True, db_index=True,
                                                              help_text='This is a globally unique identifier for this activity. It is a requirement to be compliant with the IATI standard. This code consists of: [country code]-[Chamber of Commerce number]-[organisation’s internal project code]. For Dutch organisations this is e.g. NL-KVK-31156201-TZ1234. For more information see <a href="http://iatistandard.org/202/activity-standard/iati-activities/iati-activity/iati-identifier/#definition" target="_blank">http://iatistandard.org/201/activity-standard/iati-activities/iati-activity/iati-identifier/#definition</a>',
                                                              max_length=100, null=True, unique=True,
                                                              verbose_name='IATI identifier')),
                ('cofunded', models.BooleanField(default=False)),
                ('related_project',
                 models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='third_party_projects',
                                   to='rsr.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(migrate_external_projects),
    ]
