# Generated by Django 3.2.10 on 2022-08-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0218_project_thumbnail_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='cumulative',
            field=models.BooleanField(default=False, help_text='Select if the reporting update is cumulative', verbose_name='cumulative'),
        ),
    ]
