# Generated by Django 3.2.10 on 2022-09-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0219_iatiactivityvalidationjob_iatiorganisationvalidationjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailReportJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('report', models.CharField(max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('recipient', models.EmailField(max_length=254)),
            ],
        ),
    ]
