# Generated by Django 3.2.10 on 2022-05-03 16:13

import akvo.rsr.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0219_project_tree'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('iati_id', akvo.rsr.fields.ValidXMLCharField(blank=True, db_index=True, help_text='This is a globally unique identifier for this activity. It is a requirement to be compliant with the IATI standard. This code consists of: [country code]-[Chamber of Commerce number]-[organisation’s internal project code]. For Dutch organisations this is e.g. NL-KVK-31156201-TZ1234. For more information see <a href="http://iatistandard.org/202/activity-standard/iati-activities/iati-activity/iati-identifier/#definition" target="_blank">http://iatistandard.org/201/activity-standard/iati-activities/iati-activity/iati-identifier/#definition</a>', max_length=100, null=True, unique=True, verbose_name='IATI identifier')),
                ('cofunded', models.BooleanField(default=False)),
                ('related_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_party_projects', to='rsr.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='iatiactivityimport',
            name='iati_import_job',
        ),
        migrations.RemoveField(
            model_name='iatiactivityimport',
            name='project',
        ),
        migrations.RemoveField(
            model_name='iatiimport',
            name='user',
        ),
        migrations.RemoveField(
            model_name='iatiimportjob',
            name='iati_import',
        ),
        migrations.RemoveField(
            model_name='iatiimportjob',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='iatiimportlog',
            name='iati_activity_import',
        ),
        migrations.RemoveField(
            model_name='iatiimportlog',
            name='iati_import_job',
        ),
        migrations.RemoveField(
            model_name='iatiimportlog',
            name='project',
        ),
        migrations.DeleteModel(
            name='CordaidZipIatiImportJob',
        ),
        migrations.DeleteModel(
            name='IatiActivityImport',
        ),
        migrations.DeleteModel(
            name='IatiImport',
        ),
        migrations.DeleteModel(
            name='IatiImportJob',
        ),
        migrations.DeleteModel(
            name='IatiImportLog',
        ),
    ]
