# Generated by Django 3.2.10 on 2022-07-18 12:12

from sys import stderr, stdout

from django.db import migrations, models
import django.db.models.deletion
import akvo.rsr.fields
from akvo.rsr.management.commands.migrate_external_projects import Migrator as ExternalProjectMigrator
from akvo.rsr.management.commands.migrate_related_project_contributors import Migrator as ContributorMigrator


def migrate_external_projects(apps, schema_editor):
    ExternalProjectMigrator(stdout, stderr, apply=True).run()

def migrate_contributing_projects(apps, schema_editor):
    ContributorMigrator(
        stdout, stderr,
        apps.get_model("rsr", "Project"),
        apps.get_model("rsr", "RelatedProject"),
        apply=True
    ).run()


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0220_rm_iati_import'),
    ]

    operations = [

        migrations.AddField(
            model_name='project',
            name='contributes_to_project',
            field=models.ForeignKey(null=True, on_delete=models.deletion.SET_NULL, to='rsr.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='external_parent_iati_activity_id',
            field=akvo.rsr.fields.ValidXMLCharField(blank=True, db_index=True,
                                                    help_text='This is a globally unique identifier for an activity. It is a requirement to be compliant with the IATI standard. This code consists of: [country code]-[Chamber of Commerce number]-[organisation’s internal project code]. For Dutch organisations this is e.g. NL-KVK-31156201-TZ1234. For more information see <a href="http://iatistandard.org/202/activity-standard/iati-activities/iati-activity/iati-identifier/#definition" target="_blank">http://iatistandard.org/201/activity-standard/iati-activities/iati-activity/iati-identifier/#definition</a>',
                                                    max_length=100, null=True, verbose_name='IATI identifier'),
        ),
        migrations.RunPython(migrate_contributing_projects),
        migrations.CreateModel(
            name='ExternalProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('iati_id', akvo.rsr.fields.ValidXMLCharField(blank=True, db_index=True,
                                                              help_text='This is a globally unique identifier for this activity. It is a requirement to be compliant with the IATI standard. This code consists of: [country code]-[Chamber of Commerce number]-[organisation’s internal project code]. For Dutch organisations this is e.g. NL-KVK-31156201-TZ1234. For more information see <a href="http://iatistandard.org/202/activity-standard/iati-activities/iati-activity/iati-identifier/#definition" target="_blank">http://iatistandard.org/201/activity-standard/iati-activities/iati-activity/iati-identifier/#definition</a>',
                                                              max_length=100, null=True, unique=True,
                                                              verbose_name='IATI identifier')),
                ('cofunded', models.BooleanField(default=False)),
                ('related_project',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_party_projects',
                                   to='rsr.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(migrate_external_projects),
    ]
