# Generated by Django 3.2.10 on 2022-10-18 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0220_emailreportjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorPeriodAggregationJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('RUNNING', 'Running'), ('FINISHED', 'Finished'), ('FAILED', 'Failed'), ('MAXXED', 'Max attempts reached')], default='SCHEDULED', max_length=15)),
                ('attempts', models.IntegerField(default=0)),
                ('pid', models.PositiveIntegerField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsr.indicatorperiod')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsr.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='employment',
            name='receives_indicator_aggregation_emails',
            field=models.BooleanField(default=False,
                                      help_text='Some events of indicator aggregations in projects of this org will trigger emails',
                                      verbose_name='Receive indicator emails'),
        ),
    ]
