# Generated by Django 3.2.10 on 2022-10-06 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0220_emailreportjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicatorperioddata',
            name='period_actual_value',
        ),
    ]
