# Generated by Django 3.2.10 on 2022-11-02 10:27

from django.db import migrations, models
import django.db.models.deletion


def get_root_period(period):
    root = period
    while root.parent_period:
        root = root.parent_period
    return root


def set_root_period(apps, schema_editor):
    IndicatorPeriodAggregationJob = apps.get_model("rsr", "IndicatorPeriodAggregationJob")
    jobs = []
    for job in IndicatorPeriodAggregationJob.objects.all():
        job.root_period = get_root_period(job.period)
        jobs.append(job)
    IndicatorPeriodAggregationJob.objects.bulk_update(jobs, ["root_period"])


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0221_indicatorperiodaggregationjob'),
    ]
    operations = [
        migrations.RemoveField(
            model_name='indicatorperiodaggregationjob',
            name='program',
        ),
        migrations.AddField(
            model_name='indicatorperiodaggregationjob',
            name='root_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_aggregation_jobs', to='rsr.indicatorperiod'),
            preserve_default=False,
        ),
        migrations.RunPython(set_root_period),

        migrations.AlterField(
            model_name='indicatorperiodaggregationjob',
            name='root_period',
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='child_aggregation_jobs', to='rsr.indicatorperiod'),
            preserve_default=False,
        ),
    ]
