# Generated by Django 3.2.10 on 2022-10-11 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0222_rm_iati_import'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicatorperioddata',
            name='period_actual_value',
        ),
    ]
