# Generated by Django 3.2.10 on 2023-01-12 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('password_policy', '0001_initial'),
        ('rsr', '0226_indicator_cumulative'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='password_policy',
            field=models.ForeignKey(blank=True, help_text='Password policies config for employees of this organization.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='password_policy.policyconfig'),
        ),
    ]
