# Generated by Django 3.2.17 on 2023-03-14 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0227_organisation_password_policy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailReportJob',
        ),
    ]
