table = 'auth_permission'
fields = ['id', 'name', 'content_type_id', 'codename']
#default item format: "fieldname":("type", "value")
default = {}
records = [
[1L, u'Can add message', 1L, u'add_message']
[2L, u'Can change message', 1L, u'change_message']
[3L, u'Can delete message', 1L, u'delete_message']
[4L, u'Can add group', 2L, u'add_group']
[5L, u'Can change group', 2L, u'change_group']
[6L, u'Can delete group', 2L, u'delete_group']
[7L, u'Can add user', 3L, u'add_user']
[8L, u'Can change user', 3L, u'change_user']
[9L, u'Can delete user', 3L, u'delete_user']
[10L, u'Can add permission', 4L, u'add_permission']
[11L, u'Can change permission', 4L, u'change_permission']
[12L, u'Can delete permission', 4L, u'delete_permission']
[13L, u'Can add content type', 5L, u'add_contenttype']
[14L, u'Can change content type', 5L, u'change_contenttype']
[15L, u'Can delete content type', 5L, u'delete_contenttype']
[16L, u'Can add session', 6L, u'add_session']
[17L, u'Can change session', 6L, u'change_session']
[18L, u'Can delete session', 6L, u'delete_session']
[19L, u'Can add site', 7L, u'add_site']
[20L, u'Can change site', 7L, u'change_site']
[21L, u'Can delete site', 7L, u'delete_site']
[22L, u'Can add log entry', 8L, u'add_logentry']
[23L, u'Can change log entry', 8L, u'change_logentry']
[24L, u'Can delete log entry', 8L, u'delete_logentry']
[25L, u'Can add funding partner', 9L, u'add_fundingpartner']
[26L, u'Can change funding partner', 9L, u'change_fundingpartner']
[27L, u'Can delete funding partner', 9L, u'delete_fundingpartner']
[28L, u'Can add funding', 10L, u'add_funding']
[29L, u'Can change funding', 10L, u'change_funding']
[30L, u'Can delete funding', 10L, u'delete_funding']
[31L, u'Can add field partner', 11L, u'add_fieldpartner']
[32L, u'Can change field partner', 11L, u'change_fieldpartner']
[33L, u'Can delete field partner', 11L, u'delete_fieldpartner']
[34L, u'Can add project', 12L, u'add_project']
[35L, u'Can change project', 12L, u'change_project']
[36L, u'Can delete project', 12L, u'delete_project']
[37L, u'Can add project update', 13L, u'add_projectupdate']
[38L, u'Can change project update', 13L, u'change_projectupdate']
[39L, u'Can delete project update', 13L, u'delete_projectupdate']
[40L, u'Can add organisation', 14L, u'add_organisation']
[41L, u'Can change organisation', 14L, u'change_organisation']
[42L, u'Can delete organisation', 14L, u'delete_organisation']
[100L, u'Can change pay pal invoice', 33L, u'change_paypalinvoice']
[98L, u'Can delete organisation account', 34L, u'delete_organisationaccount']
[97L, u'Can change organisation account', 34L, u'change_organisationaccount']
[101L, u'Can delete pay pal invoice', 33L, u'delete_paypalinvoice']
[95L, u'RSR limited change organisation', 14L, u'rsr_limited_change_organisation']
[94L, u'RSR limited change funding', 10L, u'rsr_limited_change_funding']
[99L, u'Can add pay pal invoice', 33L, u'add_paypalinvoice']
[96L, u'Can add organisation account', 34L, u'add_organisationaccount']
[64L, u'Can add project comment', 22L, u'add_projectcomment']
[65L, u'Can change project comment', 22L, u'change_projectcomment']
[66L, u'Can delete project comment', 22L, u'delete_projectcomment']
[67L, u'Can add support partner', 23L, u'add_supportpartner']
[68L, u'Can change support partner', 23L, u'change_supportpartner']
[69L, u'Can delete support partner', 23L, u'delete_supportpartner']
[70L, u'Can add country', 24L, u'add_country']
[71L, u'Can change country', 24L, u'change_country']
[72L, u'Can delete country', 24L, u'delete_country']
[73L, u'Can add link', 25L, u'add_link']
[74L, u'Can change link', 25L, u'change_link']
[75L, u'Can delete link', 25L, u'delete_link']
[76L, u'Can add registration profile', 26L, u'add_registrationprofile']
[77L, u'Can change registration profile', 26L, u'change_registrationprofile']
[78L, u'Can delete registration profile', 26L, u'delete_registrationprofile']
[104L, u'Can delete pay pal ipn', 32L, u'delete_paypalipn']
[103L, u'Can change pay pal ipn', 32L, u'change_paypalipn']
[102L, u'Can add pay pal ipn', 32L, u'add_paypalipn']
[82L, u'Can add user profile', 28L, u'add_userprofile']
[83L, u'Can change user profile', 28L, u'change_userprofile']
[84L, u'Can delete user profile', 28L, u'delete_userprofile']
[85L, u'Can add mo mms raw', 30L, u'add_mommsraw']
[86L, u'Can change mo mms raw', 30L, u'change_mommsraw']
[87L, u'Can delete mo mms raw', 30L, u'delete_mommsraw']
[88L, u'Can add mo mms file', 31L, u'add_mommsfile']
[89L, u'Can change mo mms file', 31L, u'change_mommsfile']
[90L, u'Can delete mo mms file', 31L, u'delete_mommsfile']
[91L, u'Can add mo sms raw', 29L, u'add_mosmsraw']
[92L, u'Can change mo sms raw', 29L, u'change_mosmsraw']
[93L, u'Can delete mo sms raw', 29L, u'delete_mosmsraw']
[105L, u'RSR limited change project', 12L, u'rsr_limited_change_project']
[106L, u'Can add publishing status', 35L, u'add_publishingstatus']
[107L, u'Can change publishing status', 35L, u'change_publishingstatus']
[108L, u'Can delete publishing status', 35L, u'delete_publishingstatus']
[109L, u'RSR limited change user profile', 28L, u'rsr_limited_change_userprofile']
[164L, u'Can add location', 54L, u'add_location']
[165L, u'Can change location', 54L, u'change_location']
[166L, u'Can delete location', 54L, u'delete_location']
[167L, u'Can add focus area', 55L, u'add_focusarea']
[168L, u'Can change focus area', 55L, u'change_focusarea']
[169L, u'Can delete focus area', 55L, u'delete_focusarea']
[170L, u'Can add category', 57L, u'add_category']
[171L, u'Can change category', 57L, u'change_category']
[172L, u'Can delete category', 57L, u'delete_category']
[173L, u'Can add MiniCMS', 56L, u'add_minicms']
[174L, u'Can change MiniCMS', 56L, u'change_minicms']
[175L, u'Can delete MiniCMS', 56L, u'delete_minicms']
[176L, u'Can add Budget item', 36L, u'add_budgetitem']
[177L, u'Can change Budget item', 36L, u'change_budgetitem']
[178L, u'Can delete Budget item', 36L, u'delete_budgetitem']
[179L, u'RSR limited change budget', 36L, u'rsr_limited_change_budget']
[180L, u'Can add Sponsor partner', 37L, u'add_sponsorpartner']
[181L, u'Can change Sponsor partner', 37L, u'change_sponsorpartner']
[182L, u'Can delete Sponsor partner', 37L, u'delete_sponsorpartner']
[183L, u'Can add PayPal gateway', 40L, u'add_paypalgateway']
[184L, u'Can change PayPal gateway', 40L, u'change_paypalgateway']
[185L, u'Can delete PayPal gateway', 40L, u'delete_paypalgateway']
[186L, u'Can add Mollie/iDEAL gateway', 41L, u'add_molliegateway']
[187L, u'Can change Mollie/iDEAL gateway', 41L, u'change_molliegateway']
[188L, u'Can delete Mollie/iDEAL gateway', 41L, u'delete_molliegateway']
[189L, u'Can add Project payment gateway configuration', 42L, u'add_paymentgatewayselector']
[190L, u'Can change Project payment gateway configuration', 42L, u'change_paymentgatewayselector']
[191L, u'Can delete Project payment gateway configuration', 42L, u'delete_paymentgatewayselector']
[192L, u'Can add invoice', 43L, u'add_invoice']
[193L, u'Can change invoice', 43L, u'change_invoice']
[194L, u'Can delete invoice', 43L, u'delete_invoice']
[195L, u'Can add PayPal IPN', 39L, u'add_paypalipn']
[196L, u'Can change PayPal IPN', 39L, u'change_paypalipn']
[197L, u'Can delete PayPal IPN', 39L, u'delete_paypalipn']
[198L, u'Can add View Counter', 58L, u'add_viewcounter']
[199L, u'Can change View Counter', 58L, u'change_viewcounter']
[200L, u'Can delete View Counter', 58L, u'delete_viewcounter']
[201L, u'Can add Download Counter', 59L, u'add_redircounter']
[202L, u'Can change Download Counter', 59L, u'change_redircounter']
[203L, u'Can delete Download Counter', 59L, u'delete_redircounter']
[204L, u'Can add Referer', 60L, u'add_referer']
[205L, u'Can change Referer', 60L, u'change_referer']
[206L, u'Can delete Referer', 60L, u'delete_referer']
[207L, u'Can add stored OEmbed', 61L, u'add_storedoembed']
[208L, u'Can change stored OEmbed', 61L, u'change_storedoembed']
[209L, u'Can delete stored OEmbed', 61L, u'delete_storedoembed']
[210L, u'Can add stored provider', 62L, u'add_storedprovider']
[211L, u'Can change stored provider', 62L, u'change_storedprovider']
[212L, u'Can delete stored provider', 62L, u'delete_storedprovider']
[213L, u'Can add aggregate media', 63L, u'add_aggregatemedia']
[214L, u'Can change aggregate media', 63L, u'change_aggregatemedia']
[215L, u'Can delete aggregate media', 63L, u'delete_aggregatemedia']
]
