table = 'django_content_type'
fields = ['id', 'name', 'app_label', 'model']
#default item format: "fieldname":("type", "value")
default = {}
records = [
[1L, u'message', u'auth', u'message']
[2L, u'group', u'auth', u'group']
[3L, u'user', u'auth', u'user']
[4L, u'permission', u'auth', u'permission']
[5L, u'content type', u'contenttypes', u'contenttype']
[6L, u'session', u'sessions', u'session']
[7L, u'site', u'sites', u'site']
[8L, u'log entry', u'admin', u'logentry']
[9L, u'funding partner', u'rsr', u'fundingpartner']
[10L, u'funding', u'rsr', u'funding']
[11L, u'field partner', u'rsr', u'fieldpartner']
[12L, u'project', u'rsr', u'project']
[13L, u'project update', u'rsr', u'projectupdate']
[14L, u'organisation', u'rsr', u'organisation']
[16L, u'link', u'feedjack', u'link']
[17L, u'site', u'feedjack', u'site']
[18L, u'feed', u'feedjack', u'feed']
[19L, u'tag', u'feedjack', u'tag']
[20L, u'post', u'feedjack', u'post']
[21L, u'subscriber', u'feedjack', u'subscriber']
[22L, u'project comment', u'rsr', u'projectcomment']
[23L, u'support partner', u'rsr', u'supportpartner']
[24L, u'country', u'rsr', u'country']
[25L, u'link', u'rsr', u'link']
[26L, u'registration profile', u'registration', u'registrationprofile']
[27L, u'rs r_ registration profile', u'rsr', u'rsr_registrationprofile']
[28L, u'user profile', u'rsr', u'userprofile']
[29L, u'mo sms raw', u'rsr', u'mosmsraw']
[30L, u'mo mms raw', u'rsr', u'mommsraw']
[31L, u'mo mms file', u'rsr', u'mommsfile']
[32L, u'PayPal IPN', u'standard', u'paypalipn']
[33L, u'pay pal invoice', u'rsr', u'paypalinvoice']
[34L, u'organisation account', u'rsr', u'organisationaccount']
[35L, u'publishing status', u'rsr', u'publishingstatus']
[36L, u'budget item', u'rsr', u'budgetitem']
[37L, u'sponsor partner', u'rsr', u'sponsorpartner']
[38L, u'Project PayPal gateway configuration', u'rsr', u'paypalgatewayselector']
[39L, u'PayPal IPN', u'ipn', u'paypalipn']
[40L, u'PayPal gateway', u'rsr', u'paypalgateway']
[41L, u'Mollie/iDEAL gateway', u'rsr', u'molliegateway']
[42L, u'Project payment gateway configuration', u'rsr', u'paymentgatewayselector']
[43L, u'invoice', u'rsr', u'invoice']
[54L, u'location', u'rsr', u'location']
[55L, u'focus area', u'rsr', u'focusarea']
[56L, u'MiniCMS', u'rsr', u'minicms']
[57L, u'category', u'rsr', u'category']
[58L, u'View Counter', u'django_counter', u'viewcounter']
[59L, u'Download Counter', u'django_counter', u'redircounter']
[60L, u'Referer', u'django_counter', u'referer']
[61L, u'stored OEmbed', u'oembed', u'storedoembed']
[62L, u'stored provider', u'oembed', u'storedprovider']
[63L, u'aggregate media', u'oembed', u'aggregatemedia']
[64L, u'benchmark name', u'rsr', u'benchmarkname']
[65L, u'category', u'rsr', u'benchmark']
]
