table = 'rsr_link'
fields = ['id', 'kind', 'url', 'caption', 'project_id']
#default item format: "fieldname":("type", "value")
default = {}
records = [
[33L, u'E', u'http://www.ramro.nl/filmpjes.php', u"Youtube video's by Ramro", 53L]
[31L, u'A', u'http://www.akvo.org/wiki/index.php/Rope_pump', u'Rope pump', 44L]
[7L, u'E', u'http://youtube.com/watch?v=_nJMI-Mo_oc', u'YouTube video about project', 25L]
[8L, u'A', u'http://www.akvo.org/wiki/index.php/Rainwater_harvesting', u'Rain water harvesting', 25L]
[28L, u'E', u'http://en.wikipedia.org/wiki/Republic_of_Somaliland', u'Somaliland Wikipedia', 41L]
[10L, u'A', u'http://www.akvo.org/wiki/index.php/Dry_urine_diversion_toilet', u'Dry urine diversion toilet', 15L]
[11L, u'A', u'http://www.akvo.org/wiki/index.php/Plastic-lined_tank', u'Plastic Lined Tank', 16L]
[12L, u'A', u'http://www.akvo.org/wiki/index.php/Groundwater_-_Rota_sludge_well_drilling', u'Rota Sludge Well Drilling', 17L]
[13L, u'A', u'http://www.akvo.org/wiki/index.php/Rope_pump', u'Rope Pump', 17L]
[14L, u'A', u'http://www.akvo.org/wiki/index.php/Dry_urine_diversion_toilet', u'Dry Urine Diversion Toilet', 18L]
[15L, u'A', u'http://www.akvo.org/wiki/index.php/Ceramic_filter', u'Ceramic Filter', 19L]
[16L, u'A', u'http://www.akvo.org/wiki/index.php/Dry_urine_diversion_toilet', u'Dry urine diversion toilets', 22L]
[17L, u'A', u'http://www.akvo.org/wiki/index.php/Human_urine_as_fertiliser', u'Human urine as fertiliser', 22L]
[18L, u'A', u'http://www.akvo.org/wiki/index.php/Compost_as_soil_conditioner', u'Compost as soil conditioner', 22L]
[19L, u'A', u'http://www.akvo.org/wiki/index.php/Ceramic_filter', u'Ceramic Filter', 24L]
[20L, u'A', u'http://www.akvo.org/wiki/index.php/Dry_urine_diversion_toilet', u'Dry Urine Diversion Toilet', 32L]
[21L, u'A', u'http://www.akvo.org/wiki/index.php/Dry_urine_diversion_toilet', u'Dry Urine Diverting Toilet', 33L]
[22L, u'A', u'http://www.akvo.org/wiki/index.php/Dry_urine_diversion_toilet', u'Dry Urine Diversion Toilet', 34L]
[23L, u'A', u'http://www.akvo.org/wiki/index.php/Dry_urine_diversion_toilet', u'Dry Urine Diversion Toilet', 35L]
[24L, u'A', u'http://www.akvo.org/wiki/index.php/Groundwater_-_Rota_sludge_well_drilling', u'Rota Sludge Well Drilling', 30L]
[25L, u'A', u'http://www.akvo.org/wiki/index.php/Rainwater_harvesting', u'Rainwater Harvesting', 30L]
[26L, u'A', u'http://www.akvo.org/wiki/index.php/Dry_urine_diversion_toilet', u'Dry Urine Diversion Toilet', 37L]
[27L, u'E', u'http://www.irc.nl/home/themes/sanitation/wash_in_schools', u'IRC: WASH in schools', 25L]
[29L, u'E', u'http://www.wecf.de/english/publications/2007/ecosan_cold_climates.php', u'Ecosan in Cold Climates', 31L]
[30L, u'E', u'http://www.africanews.com/site/list_messages/19451', u'Video about this project: before start', 24L]
[34L, u'E', u'http://www.youtube.com/watch?v=V5JsVE6QJsY&eurl=http://www.ramro.nl/filmpjes.php', u'Youtube WvW video 2008', 53L]
[35L, u'A', u'http://www.akvo.org/wiki/index.php/Rope_pump', u'Rope Pump', 55L]
[36L, u'A', u'http://www.akvo.org/wiki/index.php/Rope_pump', u'Rope Pump', 58L]
[37L, u'E', u'http://www.youtube.com/watch?v=4-LB7AEFDy0', u'Video from project, 24 Feb. 2009', 41L]
[38L, u'E', u'http://www.youtube.com/watch?v=WPrHtoZ0rds&eurl=http%3A%2F%2FAkvo%2Ehyves%2Enl%2F&feature=player_embedded', u'Video before start of project', 42L]
[39L, u'E', u'http://www.youtube.com/watch?v=5e1Oh_IXqio', u'Video before start of project', 50L]
[40L, u'A', u'http://www.akvo.org/wiki/index.php/Rope_pump', u'Rope Pump', 2L]
[214L, u'E', u'http://blip.tv/file/4296136', u'Video about project', 54L]
[42L, u'E', u'http://www.rainfoundation.org/index.php?id=182#c467', u'Movie: RAIN workshop & field visit, Ethiopia', 29L]
[44L, u'A', u'http://akvo.org/wiki/index.php/Storage_tanks_for_rooftop_harvesting', u'Rooftop harvesting', 72L]
[45L, u'E', u'http://akvo.org/rsr/project/31/', u'Sverdlov water rehabilitation', 65L]
[46L, u'A', u'http://www.akvo.org/wiki/index.php/Hydraulic_Ram_pump', u'Hydraulic Ram Pump', 75L]
[47L, u'A', u'http://akvo.org/wiki/index.php/Siphon_filter', u'Siphon Filter', 80L]
[48L, u'A', u'http://akvo.org/wiki/index.php/Sodis', u'Sodis', 80L]
[49L, u'E', u'http://www.youtube.com/watch?v=IcTlxBADqDM', u'Video about the training in Cambodia', 24L]
[181L, u'E', u'http://commersen.lokaltidningen.se/article/20090915/ARTIKLER/197765820/2012', u'Article in local newspaper Karlshamn', 50L]
[51L, u'E', u'http://akvo.org/rsr/project/24/', u'First phase of the project', 83L]
[52L, u'E', u'http://www.youtube.com/watch?v=IcTlxBADqDM', u'Video of the training in Cambodia', 83L]
[53L, u'A', u'http://www.akvo.org/wiki/index.php/Ceramic_filter', u'Ceramic water filter', 83L]
[54L, u'E', u'http://www.africanews.com/site/list_messages/19451', u'Video about this project: before start', 83L]
[55L, u'E', u'http://www.ceramicwaterfilter.org/', u'International ceramic water filter community', 83L]
[56L, u'E', u'http://rdic.org/', u'Training partner and filter producer in Cambodia', 83L]
[57L, u'E', u'http://achildsright.org/water_systems.php', u"A Child's Right- how we approach urban water issue", 84L]
[58L, u'A', u'http://www.akvo.org/wiki/index.php/Rainwater_harvesting', u'Rainwater Harvesting', 29L]
[59L, u'A', u'http://www.akvo.org/wiki/index.php/Rainwater_harvesting', u'Rain Water Harvesting', 86L]
[61L, u'A', u'http://www.akvo.org/wiki/index.php/Rainwater_harvesting', u'Rain Water Harvesting', 89L]
[62L, u'E', u'http://www.globalwaterchallenge.org/newscenter/multimedia-detail.php?id=951', u"GWC Video on EcoTact's program in Mathare slums", 90L]
[63L, u'E', u'http://www.globalwaterchallenge.org/newscenter/news-detail.php?id=971', u'CNN Video featuring EcoTact', 90L]
[64L, u'E', u'http://www.globalwaterchallenge.org/newscenter/multimedia-detail.php?id=933', u'GWC Video on water flow through UV filtration', 91L]
[65L, u'E', u'http://www.globalwaterchallenge.org/newscenter/multimedia-detail.php?id=820', u'GWC Video on Magdalena, a SWASH+ beneficiary', 92L]
[66L, u'A', u'http://www.akvo.org/wiki/index.php/Rope_pump', u'Rope Pump', 93L]
[67L, u'A', u'http://www.akvo.org/wiki/index.php/Rope_pump', u'Rope Pump', 94L]
[68L, u'A', u'http://www.akvo.org/wiki/index.php/Rainwater_harvesting', u'Rainwater Harvesting', 94L]
[69L, u'A', u'http://www.akvo.org/wiki/index.php/Tippy_Tap', u'Tippy Tap', 94L]
[70L, u'A', u'http://www.akvo.org/wiki/index.php/Hydraulic_Ram_pump', u'Hydraulic Ram Pump', 95L]
[71L, u'A', u'http://www.akvo.org/wiki/index.php/Rope_pump', u'Rope Pump', 96L]
[72L, u'E', u'http://www.dappzambia.org/', u'Website for DAPP in Zambia', 97L]
[73L, u'A', u'http://www.akvo.org/wiki/index.php/Rope_pump', u'Rope Pump', 97L]
[74L, u'E', u'http://www.shipo-tz.org/', u'Website for Shipo Information', 98L]
[75L, u'A', u'http://www.akvo.org/wiki/index.php/Rope_pump', u'Rope Pump', 98L]
[76L, u'E', u'http://www.shipo-tz.org/', u'Website for Shipo Information', 99L]
[77L, u'A', u'http://www.akvo.org/wiki/index.php/Tippy_Tap', u'Tippy Tap', 99L]
[78L, u'A', u'http://www.akvo.org/wiki/index.php/Single_Pit', u'Single Pit Latrine', 99L]
[79L, u'A', u'http://www.akvo.org/wiki/index.php/Urine_Diverting_Dry_Toilet', u'Urine Diverting Dry Toilet', 101L]
[80L, u'A', u'http://www.akvo.org/wiki/index.php/Application_of_Dehydrated_Faeces', u'Application of Dehydrated Faeces', 101L]
[81L, u'A', u'http://www.akvo.org/wiki/index.php/Application_of_Urine', u'Application of Urine', 101L]
[82L, u'E', u'http://www.wildlands.co.za/Programmes_TreesForLife_Map.aspx', u'Indigenous Trees for Life', 103L]
[84L, u'A', u'http://www.akvo.org/wiki/index.php/Rainwater_harvesting', u'Rainwater Harvesting', 103L]
[85L, u'A', u'http://www.akvo.org/wiki/index.php/Rope_pump', u'Rope Pump', 104L]
[86L, u'E', u'http://www.iicd.org/projects/zambia-cypro/', u'Project description CYP on website of IICD ', 105L]
[87L, u'A', u'http://www.akvo.org/wiki/index.php/Rainwater_harvesting', u'Rain Water Harvesting', 107L]
[213L, u'E', u'http://blip.tv/file/4296136', u'Video over project', 138L]
[89L, u'E', u'http://www.degevuldewaterkruik.nl/', u'Website of SVHB', 107L]
[90L, u'E', u'http://www.akvo.org/rsr/project/30/', u'Details of the 1st phase of project', 110L]
[91L, u'E', u'http://www.youtube.com/watch?v=phzt0HFTFNk', u'Youtube Video of Project', 60L]
[92L, u'E', u'http://www.practicafoundation.nl/', u'Website PRACTICA foundation', 111L]
[93L, u'A', u'http://www.akvo.org/wiki/index.php/Rainwater_harvesting', u'Rain Water Harvesting', 112L]
[94L, u'E', u'http://www.bspnepal.org.np/', u'Website of BSP Nepal', 112L]
[95L, u'A', u'http://www.akvo.org/wiki/index.php/Rainwater_harvesting', u'Rain Water Harvesting', 113L]
[96L, u'A', u'http://www.akvo.org/wiki/index.php/Rainwater_harvesting', u'Rain Water Harvesting', 114L]
[97L, u'A', u'http://www.akvo.org/wiki/index.php/Rainwater_harvesting', u'Rain Water Harvesting', 115L]
[98L, u'E', u'http://www.nrcs.org/', u'Website of NRCS', 115L]
[99L, u'E', u'http://www.bspnepal.org.np/', u'Website of BSP Nepal', 113L]
[100L, u'E', u'http://www.pumpaid.org/', u'Website Pump Aid', 116L]
[101L, u'E', u'http://www.pumpaid.org/', u'Pump Aid Website', 117L]
[102L, u'E', u'http://www.pumpaid.org/', u'Website Pump Aid', 118L]
[103L, u'A', u'http://www.akvo.org/wiki/index.php/Application_of_Urine', u'Application of Urine', 119L]
[104L, u'A', u'http://www.akvo.org/wiki/index.php/Application_of_Compost_-_Eco-Humus', u'Application of Compost', 119L]
[105L, u'A', u'http://www.akvo.org/wiki/index.php/Biogas_as_source_of_energy', u'Biogas', 119L]
[106L, u'E', u'http://achildsright.org/water_systems.php', u"A Child's Right- how we approach urban water issue", 120L]
[107L, u'E', u'http://www.resourcefnd.org/', u'Website Resource Foundation', 121L]
[108L, u'E', u'http://picasaweb.google.com/CUAguaClara/AgaltecaConstruction#5400673869649011858', u'Construction workers inspect the AguaClara plant', 121L]
[109L, u'E', u'http://picasaweb.google.com/CUAguaClara/AgaltecaConstruction#5400673943683902978', u'Workers from Agalateca during the initial phase.', 121L]
[110L, u'E', u'http://sa12345.jalbum.net/Pictures%20water%20project%20Rwanda%20december%202009/index.html', u'Pictures from December 2009', 69L]
[111L, u'E', u'http://jalbum.net/browse/user/album/344758/;jsessionid=WrJE9qL1XGO0jerLVR8D.63', u'Pictures at start of project', 69L]
[112L, u'E', u'http://www.hoat.nl/fotoalbum.php?albumid=77&page=1', u'More Pictures of Construction', 61L]
[113L, u'E', u'http://www.actionaidusa.org/what/monthly_feature/senegal/', u'Website of Action Aid', 122L]
[114L, u'A', u'http://www.akvo.org/wiki/index.php/Rainwater_harvesting', u'Rainwater Harvesting', 122L]
[115L, u'A', u'http://www.akvo.org/wiki/index.php/Rainwater_harvesting', u'Rainwater Harvesting', 123L]
[116L, u'A', u'http://www.akvo.org/wiki/index.php/Rainwater_harvesting', u'Rainwater Harvesting', 124L]
[117L, u'A', u'http://www.akvo.org/wiki/index.php/Rainwater_harvesting', u'Rainwater Harvesting', 125L]
[118L, u'A', u'http://www.akvo.org/wiki/index.php/Rainwater_harvesting', u'Rainwater Harvesting', 126L]
[119L, u'A', u'http://www.akvo.org/wiki/index.php/Rainwater_harvesting', u'Rainwater Harvesting', 127L]
[120L, u'A', u'http://www.akvo.org/wiki/index.php/Rainwater_harvesting', u'Rainwater Harvesting', 128L]
[121L, u'E', u'http://www.caritas-senegal.org/Caritas-Kaolack_r12.html', u'Website of Caritas Kaolack', 128L]
[122L, u'A', u'http://www.akvo.org/wiki/index.php/Rainwater_harvesting', u'Rainwater Harvesting', 129L]
[123L, u'A', u'http://www.akvo.org/wiki/index.php/Siphon_filter', u'Siphon Filter', 129L]
[124L, u'E', u'http://www.arrakis.nl/index.php?parent=Projects&page=Mozambique:_WATSAN_for_schools', u'Project description at ARRAKIS website', 129L]
[125L, u'E', u'http://www.amref.org/where-we-work/our-work-in-kenya/', u"An overview of AMREF's work in Kenya", 130L]
[126L, u'E', u'http://www.amref.org/where-we-work/our-work-in-tanzania/?keywords=mtwara', u"An overview of AMREF's work in Tanzania", 131L]
[127L, u'E', u'http://biswa.org/', u'Website BISWA', 132L]
[128L, u'E', u'http://www.practicafoundation.nl/', u'Practica foundation', 110L]
[129L, u'E', u'http://www.stichtingmax.nl/', u'Website Stichting Max', 133L]
[130L, u'E', u'http://blip.tv/file/3147242', u'Video of Practica in Madagascar', 21L]
[131L, u'E', u'http://blip.tv/file/3147242', u'Video of Practica in Madagascar', 45L]
[132L, u'E', u'http://blip.tv/file/3147242', u'Video of Practica in Madagascar', 110L]
[133L, u'E', u'http://blip.tv/file/3147242', u'Video of Practica in Madagascar', 19L]
[134L, u'E', u'http://www.stichtingmax.nl/', u'Website Stichting Max', 134L]
[135L, u'E', u'http://www.youtube.com/watch?v=nmqyIgVdxXY', u'Promotie film Wandelen voor Water', 134L]
[136L, u'A', u'http://www.akvo.org/wiki/index.php/Rainwater_harvesting', u'Rain Water Harvesting', 136L]
[137L, u'A', u'http://www.akvo.org/wiki/index.php/Rainwater_harvesting', u'Rain Water Harvesting', 137L]
[138L, u'A', u'http://www.akvo.org/wiki/index.php/Rainwater_harvesting', u'Rain Water Harvesting', 138L]
[203L, u'E', u'http://www.dorcas.nl/', u'website of dorcas', 181L]
[140L, u'E', u'http://www.arche-nova.org/version6/seiten/seite.php?layout=aktuell&inhalt=aktuell&sprache=en&id=270', u'Latest Haiti News by Arche Nova', 139L]
[141L, u'E', u'http://www.silentwork.org/', u'Website Silent Work', 140L]
[142L, u'E', u'http://demotech.org/d-design/designA.php?d=43', u'Demotech rope pump', 141L]
[143L, u'E', u'http://demotech.org/d-publications/designB.php?sub=45', u'1986, 10 years of rope pump experience', 141L]
[144L, u'E', u'http://demotech.org/d-design/d-alldesign.php', u'All designs', 141L]
[145L, u'A', u'http://www.akvo.org/wiki/index.php/Rope_pump', u'Rope Pump', 141L]
[146L, u'E', u'http://www.dutchchannelswimmers2010.nl/', u'Website Dutch Channel Swimmers', 128L]
[147L, u'E', u'http://www.tweed.nsw.gov.au/kenya/', u'Website Tweed Kenya', 144L]
[148L, u'E', u'http://www.akvo.org/rsr/project/57/', u'Vorig project op Akvo', 145L]
[149L, u'E', u'http://www.kansarmensrilanka.nl/promotiefilm.htm', u'Promotie Film', 147L]
[150L, u'E', u'http://www.kansarmensrilanka.nl/promotiefilm.htm', u'Promotie Film', 148L]
[151L, u'E', u'http://www.kansarmensrilanka.nl/promotiefilm.htm', u'Promotion Video (Dutch)', 149L]
[152L, u'E', u'http://www.kansarmensrilanka.nl/promotiefilm.htm', u'Promotie Film', 150L]
[153L, u'E', u'http://www.kansarmensrilanka.nl/promotiefilm.htm', u'Promotie Film', 151L]
[154L, u'E', u'http://www.kansarmensrilanka.nl/video%20water%20en%20sanitatie%20projecten.htm', u'Film over Water en Sanitatie Projecten, Sri Lanka', 147L]
[155L, u'E', u'http://www.kansarmensrilanka.nl/video%20water%20en%20sanitatie%20projecten.htm', u'Film over Water en Sanitatie Projecten, Sri Lanka', 148L]
[156L, u'E', u'http://www.kansarmensrilanka.nl/video%20water%20en%20sanitatie%20projecten.htm', u'Video on WASH projects in Sri Lanka (Dutch) ', 149L]
[157L, u'E', u'http://www.kansarmensrilanka.nl/video%20water%20en%20sanitatie%20projecten.htm', u'Film over Water en Sanitatie Projecten, Sri Lanka', 150L]
[158L, u'E', u'http://www.kansarmensrilanka.nl/video%20water%20en%20sanitatie%20projecten.htm', u'Film over Water en Sanitatie Projecten, Sri Lanka', 151L]
[159L, u'E', u'http://www.sbnn.nl/', u'Website SBNN', 153L]
[160L, u'E', u"http://www.msele.nl/Documenten/Foto's%20Wvw%202009.htm", u"Foto's Wandelen voor water 2009 in Coevorden", 154L]
[161L, u'E', u'http://www.msele.nl/WvW_nl.htm', u'Over Wandelen voor Water 2009 in Coevorden', 154L]
[162L, u'E', u'http://hmaburkina.waarbenjij.nu/', u'Reisverslagen van Yelkabe', 155L]
[163L, u'E', u'http://hmaburkina.waarbenjij.nu/?page=pictures&intTravelId=214293', u"Foto's van reisverslagen", 155L]
[164L, u'E', u'http://www.youtube.com/watch?v=IWsRrvAysgs', u'Mkomo School health club performing, Tanzania', 131L]
[165L, u'E', u'http://www.youtube.com/watch?v=Eh7TlkZ8GJM', u"Fragment of Dutch documentary 'Het Blauwe Goud'", 62L]
[166L, u'E', u'http://www.espacioagua.org.ar/', u'Website Espacio Agua', 156L]
[167L, u'E', u'http://www.iied-al.org.ar/', u'Website IIED-AL', 156L]
[168L, u'E', u'http://www.cambodia-dutch.org/', u'CDO: wat we doen', 157L]
[169L, u'A', u'http://www.akvo.org/wiki/index.php/Rainwater_harvesting', u'Rainwater Harvesting', 158L]
[170L, u'E', u'http://www.globalwaterchallenge.org/programs/projects-detail.php?id=817', u'Find out more information', 160L]
[171L, u'E', u'http://www.youtube.com/watch?v=_O9fVutwpQU', u'Video over CDO (Nederlands)', 157L]
[172L, u'E', u'http://www.youtube.com/watch?v=dLAut_DnEcc', u'Video over CDO (Engels)', 157L]
[173L, u'E', u'http://www.simavi.nl/simavi/wandelenvoorwater.do', u'Wandelen voor Water op Simavi Website', 161L]
[174L, u'E', u'http://www.youtube.com/watch?v=itVgV54QCBU&feature=player_embedded', u'Video van Simavi in Kenya', 161L]
[175L, u'E', u'http://www.simavi.nl/simavi/wandelenvoorwater.do', u'Wandelen voor Water op Simavi Website', 162L]
[176L, u'E', u'http://www.youtube.com/watch?v=wTx5V-8D55o&feature=player_embedded', u'Video van Simavi in Tanzania', 162L]
[177L, u'E', u'http://www.youtube.com/watch?v=of-_Ex1x5sM', u'Video: Water Situation in Asrada/Bheemanpalli', 163L]
[178L, u'E', u'http://www.zoa.nl/home/over-zoa/waar-werkt-zoa/Liberia/', u'Over ons project in Liberia ', 164L]
[179L, u'A', u'http://www.akvo.org/wiki/index.php/Siphon_filter', u'Siphon Filter', 165L]
[180L, u'E', u'http://liveearth.org/en/liveearthblog/extremely-affordable-gravity-powered-water-filters', u'About Siphon Filter on Live Earth Website', 165L]
[182L, u'E', u'http://www.espacioagua.org.ar/acciones/podra-beber.html', u'Project description in Spanish', 156L]
[183L, u'E', u'http://www.afrikaprojecten.org/', u'SAP what we do', 174L]
[184L, u'A', u'http://www.akvo.org/wiki/index.php/Treadle_pump', u'Treadle Pump', 175L]
[185L, u'A', u'http://www.akvo.org/wiki/index.php/Concrete_Biosand_Filter', u'Biosand Filter', 175L]
[186L, u'E', u'http://www.lagossaojoao.org.br/', u'Website CILSJ', 176L]
[187L, u'E', u'http://www.institutoe.org.br/', u'Website Instituto e', 176L]
[188L, u'E', u'http://www.akvo.org/blog/?p=942', u'Warhammer for Water blog', 50L]
[189L, u'E', u'http://www.youtube.com/watch?v=AsU9KATz7NQ', u'Filmpje WvW2010 Apeldoorn', 129L]
[190L, u'E', u'http://www.speg.nu/images/PDF/opbrengst.pdf', u'Totale Opbrengst  ', 152L]
[191L, u'E', u'http://blip.tv/file/3389295', u'Filmpje van kinderen tijdens de wandeling', 152L]
[192L, u'E', u'http://blip.tv/file/3389367', u'Film Interview met Agnes Ovington over WvW', 152L]
[193L, u'E', u'http://www.flickr.com/photos/charmermrk/sets/72157623689267742/', u"Foto's van de Wandeling", 152L]
[194L, u'E', u'http://blip.tv/file/3411502', u'Samenvattend Filmpje van de Wandeling in Eindhoven', 152L]
[195L, u'E', u'http://www.youtube.com/watch?v=GvnEc0plPQw', u'Movie Drink water supply Sorido fase I (Dutch)', 178L]
[196L, u'E', u'http://www.flickr.com/photos/rotaryapeldoorntloo/sets/72157623851960802/', u"Foto's van WvW2010 in Apeldoorn", 129L]
[197L, u'E', u'http://www.flickr.com/photos/rotaryapeldoorntloo/sets/72157623851960802/', u"Foto's van WvW2010 in Apeldoorn ", 143L]
[198L, u'E', u'http://www.youtube.com/watch?v=17vR0iMORo8', u'Filmpje van WvW2010 in Apeldoorn', 143L]
[199L, u'E', u'http://www.youtube.com/watch?v=17vR0iMORo8', u'2de filmpje van WvW2010 in Apeldoorn', 129L]
[200L, u'E', u'http://www.akvo.org/blog/?p=921', u'Le Connaisseur blog', 50L]
[201L, u'E', u'http://blip.tv/file/3548067', u'Video of Live Earth Hong Kong event', 120L]
[202L, u'E', u'http://www.dos-doetinchem.nl/', u'Bekijk de Nieuwsbrief', 180L]
[204L, u'E', u'http://blip.tv/file/3850642', u'Video Wandelen voor Water 2009', 57L]
[205L, u'E', u'http://blip.tv/file/3850661', u'Video van Special op Omroep Krijtland', 57L]
[206L, u'E', u'http://blip.tv/file/3850758', u'Video van Wandelen voor Water 2010', 145L]
[207L, u'E', u'http://www.cambodia-dutch.org/blog/', u'Blog op CDO website', 157L]
[208L, u'E', u'http://www.kansarmensrilanka.nl/video%20gezondheidsles.htm', u'Video on health lessons in schools (Dutch)', 149L]
[209L, u'E', u'http://www.rotary.nl/brummenengelenburg/Activiteiten/Fundraising%20Schoon%20Water/', u'Information', 186L]
[210L, u'E', u'http://karuna-shechen.org/', u'Goal Bamboo School', 186L]
[211L, u'E', u'http://www.malaowaters.com/', u'IDP project designing for Malao Waters ', 187L]
[212L, u'E', u'http://www.daryeel.eu/', u'Daryeel Foundation support partner   ', 187L]
]
