apiVersion: v1
kind: Service
metadata:
  name: rsr
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: backend-metrics
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: reports-metrics
  selector:
    run: rsr