#!/bin/bash

# Parameters:
# $1: init_script_name (for deployment to /etc/init.d)


SCRIPT_FILE_DIR="`dirname $0`"
SOURCE_REPOSITORY_ROOT="`cd $SCRIPT_FILE_DIR/../../..; pwd`"
INIT_SCRIPTS_DIR=$SOURCE_REPOSITORY_ROOT/setup/integration/scripts/init.d


function display_usage_and_exit
{
    echo "Usage: install_init_script <init_script_name>"
    echo "Specify a script from the init scripts directory for installation in /etc/init.d"
    exit -1
}

function verify_script_parameters
{
    # warn if extraneous parameters exist
    if [ -n "$2" ]; then
        echo ">> Unexpected number of parameters: $*"
        display_usage_and_exit
    fi

    # check whether the init_script_name parameter exists
    if [ -z "$1" ]; then
        echo ">> Missing init_script_name parameter"
        display_usage_and_exit
    fi

    # check whether the specified init script exists
    if [ ! -f "$INIT_SCRIPTS_DIR/$1" ]; then
        echo ">> Init script does not exist: $INIT_SCRIPTS_DIR/$1"
        exit -1
    fi
}

function install_script_link
{
    # Parameters:
    # $1: runlevel (integer from 0-6)
    # $2: kill_or_start (e.g. K99 or S99)
    # $3: script_name

    RUNLEVEL=$1
    KS=$2
    SCRIPT_NAME=$3
    RUN_LEVEL_SCRIPT_PATH="/etc/rc$RUNLEVEL.d/$KS$SCRIPT_NAME"

    if [ -L $RUN_LEVEL_SCRIPT_PATH ]; then
        rm $RUN_LEVEL_SCRIPT_PATH
    fi

    ln -s /etc/init.d/$SCRIPT_NAME $RUN_LEVEL_SCRIPT_PATH
}

function install_script
{
    SCRIPT_NAME="$1"

    cp -p $INIT_SCRIPTS_DIR/$SCRIPT_NAME /etc/init.d/$SCRIPT_NAME
    chmod 755 /etc/init.d/$SCRIPT_NAME
    chown root:root /etc/init.d/$SCRIPT_NAME

    install_script_link 0 "K99" $SCRIPT_NAME
    install_script_link 1 "K99" $SCRIPT_NAME
    install_script_link 2 "S99" $SCRIPT_NAME
    install_script_link 3 "S99" $SCRIPT_NAME
    install_script_link 6 "K99" $SCRIPT_NAME
}

verify_script_parameters $*
install_script "$1"
