#!/bin/bash

SCRIPT_FILE_DIR="`dirname $0`"
SOURCE_REPOSITORY_ROOT="`cd $SCRIPT_FILE_DIR/../../..; pwd`"
INTEGRATION_SCRIPTS_DIR=$SOURCE_REPOSITORY_ROOT/setup/integration/scripts

mkdir -p /usr/local/ci/scripts
mkdir -p /usr/local/ci/scripts/tools/selenium/1.0.3/rc-server

cp -p $SOURCE_REPOSITORY_ROOT/scripts/testing/start* /usr/local/ci/scripts
cp -p $SOURCE_REPOSITORY_ROOT/scripts/testing/stop* /usr/local/ci/scripts
cp -p $SOURCE_REPOSITORY_ROOT/scripts/testing/ensure* /usr/local/ci/scripts
cp -p -r $SOURCE_REPOSITORY_ROOT/scripts/testing/tools/selenium/1.0.3/rc-server/* /usr/local/ci/scripts/tools/selenium/1.0.3/rc-server

chown -R root:root /usr/local/ci/scripts/*

$INTEGRATION_SCRIPTS_DIR/install_init_script selenium_rc
