#!/bin/bash

# Parameters:
# $1: init_script_name (for deployment to /etc/init.d)


SCRIPT_FILE_DIR="`dirname $0`"
SOURCE_REPOSITORY_ROOT="`cd $SCRIPT_FILE_DIR/../../..; pwd`"
INIT_SCRIPTS_DIR=$SOURCE_REPOSITORY_ROOT/setup/integration/scripts/init.d


function display_usage_and_exit
{
    echo "Usage: install_init_script <init_script_name>"
    echo "Specify a script from the init scripts directory for installation in /etc/init.d"
    exit -1
}

function verify_script_parameters
{
    # warn if extraneous parameters exist
    if [ -n "$2" ]; then
        echo ">> Unexpected number of parameters: $*"
        display_usage_and_exit
    fi

    # check whether the init_script_name parameter exists
    if [ -z "$1" ]; then
        echo ">> Missing init_script_name parameter"
        display_usage_and_exit
    fi

    # check whether the specified init script exists
    if [ ! -f "$INIT_SCRIPTS_DIR/$1" ]; then
        echo ">> Init script does not exist: $INIT_SCRIPTS_DIR/$1"
        exit -1
    fi
}

verify_script_parameters $*

SCRIPT_NAME="$1"
INIT_D_SCRIPT_PATH="/etc/init.d/$SCRIPT_NAME"

function install_script_link
{
    RUNLEVEL=$1 # runlevel (integer from 0-6)
    KS_ID=$2    # kill_or_start ID (e.g. K99 or S99)

    RUN_LEVEL_SCRIPT_PATH="/etc/rc$RUNLEVEL.d/$KS_ID$SCRIPT_NAME"

    if [ -L $RUN_LEVEL_SCRIPT_PATH ]; then
        rm $RUN_LEVEL_SCRIPT_PATH
    fi

    ln -s $INIT_D_SCRIPT_PATH $RUN_LEVEL_SCRIPT_PATH
    echo "Added $RUN_LEVEL_SCRIPT_PATH link"
}

function install_script
{
    cp -p $INIT_SCRIPTS_DIR/$SCRIPT_NAME $INIT_D_SCRIPT_PATH
    chmod 755 $INIT_D_SCRIPT_PATH
    chown root:root $INIT_D_SCRIPT_PATH

    echo "Installed $INIT_D_SCRIPT_PATH script"

    install_script_link 0 "K99"
    install_script_link 1 "K99"
    install_script_link 2 "S99"
    install_script_link 3 "S99"
    install_script_link 6 "K99"
}

install_script "$1"
