#!/usr/bin/env bash
set -euo pipefail

if command -v docker-compose;
then
    echo "Running script in web container using docker-compose ..."
    exec docker-compose exec -d web ./scripts/devhelpers/restart-webpack "$@"
fi
FE_DIR=${1:-spa}
PID=$(pgrep -f "rsr/${FE_DIR}/node_modules") || true
kill "${PID}" || true
pushd "/var/akvo/rsr/code/akvo/rsr/${FE_DIR}"
echo "Starting webpackserver..."
npm start
popd
