#!/bin/bash

cd "`dirname $0`"

# check whether virtualenv_name parameter exists
if [ -z "$1" ]; then
    echo "Usage: rebuild_dev_env <virtualenv_name>"
    exit -1
fi

VIRTUALENV_NAME=$1

export ARCHFLAGS="-arch x86_64 -arch i386"
export CFLAGS="$ARCHFLAGS"
export CXXFLAGS="$ARCHFLAGS"
export LDFLAGS="$ARCHFLAGS"
export CC=/usr/bin/gcc-4.2
export MACOSX_DEPLOYMENT_TARGET=10.6

source virtualenv_paths.config

workon $VIRTUALENV_NAME

echo ">> Environment variables for compilation:"
printf ">> ARCHFLAGS                = %s\n" "$ARCHFLAGS"
printf ">> CC                       = %s\n" $CC
printf ">> MACOSX_DEPLOYMENT_TARGET = %s\n" $MACOSX_DEPLOYMENT_TARGET

printf "\n>> Virtualenv should be empty (i.e. wsgiref only)\n"
pip freeze

printf "\n>> Installing RSR modules\n"
pip install -M -U -r requirements/1_rsr.txt

printf "\n>> Installing further dev and testing modules\n"
pip install -M -U -r requirements/2_dev.txt

printf "\n>> Installed modules:\n"
pip freeze

deactivate
