#!/bin/bash

PIP_DIR="`cd dirname $0; pwd`"

cd "$PIP_DIR"

# exit if osx_system.config file does not exist
if [ ! -e osx_system.config ]; then
    printf "\n>> Expected osx_system.config file not found -- copy the osx_system.config.template file and edit as necessary\n"
    exit -1
fi

source osx_system.config
source osx_build_flags_env_64.config

function ensure_temp_dir_exists
{
    if [ ! -d "$PYTHON_TEMP_DIR" ]; then
        printf "\n>> Creating temp directory: %s\n" "$PYTHON_TEMP_DIR"
        mkdir -p "$PYTHON_TEMP_DIR"
    fi
}

function install_distribute_package
{
    # See installation notes at http://pypi.python.org/pypi/distribute#distribute-setup-py
    printf "\n>> Installing distribute package\n"
    cd "$PYTHON_TEMP_DIR"
    curl -O http://python-distribute.org/distribute_setup.py
    sudo python distribute_setup.py
}

function link_easy_install
{
    # This should ensure the installed easy_install is used rather than /usr/bin/easy_install
    # as long as the /usr/local/bin directory is before /usr/bin on the system path
    printf "\n>> Linking easy_install in /usr/local/bin\n"
    VERSIONED_EASY_INSTALL="easy_install-$PY_VERSION"
    cd /usr/local/bin
    sudo ln -s "$PY_BIN_PATH/$VERSIONED_EASY_INSTALL" $VERSIONED_EASY_INSTALL
    sudo ln -s $VERSIONED_EASY_INSTALL easy_install
}

function install_pip_package
{
    # See installation notes at http://www.pip-installer.org/en/latest/installing.html
    printf "\n>> Installing pip package\n"
    cd "$PYTHON_TEMP_DIR"
    curl -O https://github.com/pypa/pip/raw/master/contrib/get-pip.py
    sudo python get-pip.py
}

function install_system_packages
{
    cd "$PIP_DIR"
    printf "\n>> Current system packages:\n"
    pip freeze

    printf "\n>> Installing/upgrading system packages: (with 64-bit architecture)\n"
    sudo pip install -M -U -r requirements/0_system.txt

    printf "\n>> Installing/upgrading deployment packages: (with universal 32-bit & 64-bit architecture)\n"
    source osx_build_flags_env_intel.config
    sudo pip install -M -U -r requirements/1_deployment.txt

    printf "\n>> Installed system packages:\n"
    pip freeze
}

function build_system_environment
{
    ensure_temp_dir_exists
    install_distribute_package
    link_easy_install
    install_pip_package
    install_system_packages
}


build_system_environment
