#!/bin/bash
#
# Auto-start script for TeamCity build agent 1
#
# description: Starts the TeamCity build agent automatically on server startup
# processname: teamcity_agent1

TEAMCITY_AGENT_HOME=/home/tomcat/.BuildServer/agents/agent1


function start_agent
{
    su -s /bin/bash -l tomcat $TEAMCITY_AGENT_HOME/bin/agent.sh start
}

function stop_agent
{
    su -s /bin/bash -l tomcat $TEAMCITY_AGENT_HOME/bin/agent.sh stop
}

case $1 in
start)
        start_agent
        ;;
stop)
        stop_agent
        ;;
restart)
        stop_agent
        start_agent
        ;;
esac
exit 0
