export default {
  ADD: 'PE_ADD_LOCATION',
  REMOVE: 'PE_REMOVE_LOCATION',
  EDIT: 'PE_EDIT_LOCATION',
  EDIT_FIELD: 'PE_EDIT_FIELD_LOCATION',
  ADD_ADMINISTRATIVE: 'PE_LOCATION_ADMINISTRATIVE_ADD',
  REMOVE_ADMINISTRATIVE: 'PE_LOCATION_ADMINISTRATIVE_REMOVE',
  EDIT_FIELD_ADMINISTRATIVE: 'PE_LOCATION_ADMINISTRATIVE_EDIT_FIELD'
}
