#!/bin/bash

cd "`dirname $0`"

source /var/django/akvo/bin/activate

python verify_static_project_structure.py $1
echo "Validating Django models:"
python ../akvo/manage.py validate
echo "Running Django tests:"
python ../akvo/manage.py test --noinput rsr

deactivate
