# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityDateType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('description', models.TextField(verbose_name='description', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'activity date type',
                'verbose_name_plural': 'activity date types',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ActivityScope',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('description', models.TextField(verbose_name='description', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'activity scope',
                'verbose_name_plural': 'activity scopes',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ActivityStatus',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('description', models.TextField(verbose_name='description', blank=True)),
                ('language', models.CharField(max_length=2, verbose_name='language', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'activity status',
                'verbose_name_plural': 'activity statuses',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='AidType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('category', models.CharField(max_length=2, verbose_name='category', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('description', models.TextField(verbose_name='description', blank=True)),
                ('language', models.CharField(max_length=2, verbose_name='language', blank=True)),
                ('category_name', models.CharField(max_length=300, verbose_name='category name', blank=True)),
                ('category_description', models.TextField(verbose_name='category description', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'aid type',
                'verbose_name_plural': 'aid types',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='AidTypeCategory',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('description', models.TextField(verbose_name='description', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'aid type category',
                'verbose_name_plural': 'aid type categories',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='AidTypeFlag',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'aid type flag',
                'verbose_name_plural': 'aid type flags',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='BudgetIdentifier',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('category', models.CharField(max_length=100, verbose_name='category', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('sector', models.CharField(max_length=100, verbose_name='sector', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'budget identifier',
                'verbose_name_plural': 'budget identifiers',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='BudgetIdentifierSector',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('category', models.CharField(max_length=2, verbose_name='category', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'budget identifier sector',
                'verbose_name_plural': 'budget identifier sectors',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='BudgetIdentifierSectorCategory',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'budget identifier sector category',
                'verbose_name_plural': 'budget identifier sector categories',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='BudgetIdentifierVocabulary',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('description', models.TextField(verbose_name='description', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'budget identifier vocabulary',
                'verbose_name_plural': 'budget identifier vocabularies',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='BudgetStatus',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('description', models.TextField(verbose_name='description', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'budget status',
                'verbose_name_plural': 'budget statuses',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='BudgetType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('description', models.TextField(verbose_name='description', blank=True)),
                ('language', models.CharField(max_length=2, verbose_name='language', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'budget types',
                'verbose_name_plural': 'budget types',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CollaborationType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('description', models.TextField(verbose_name='description', blank=True)),
                ('language', models.CharField(max_length=2, verbose_name='language', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'collaboration type',
                'verbose_name_plural': 'collaboration types',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ConditionType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('description', models.TextField(verbose_name='description', blank=True)),
                ('language', models.CharField(max_length=2, verbose_name='language', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'condition type',
                'verbose_name_plural': 'condition types',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('description', models.TextField(verbose_name='description', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'contact type',
                'verbose_name_plural': 'contact types',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('language', models.CharField(max_length=2, verbose_name='language', blank=True)),
            ],
            options={
                'ordering': ('-version', 'name', 'code'),
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CRSAddOtherFlags',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('description', models.TextField(verbose_name='description', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'crs add other flag',
                'verbose_name_plural': 'crs add other flags',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CRSChannelCode',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'crs channel code',
                'verbose_name_plural': 'crs channel codes',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('language', models.CharField(max_length=2, verbose_name='language', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'currency',
                'verbose_name_plural': 'currencies',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='DescriptionType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('description', models.TextField(verbose_name='description', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'decription type',
                'verbose_name_plural': 'description types',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='DisbursementChannel',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('description', models.TextField(verbose_name='description', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'disbursement channel',
                'verbose_name_plural': 'disbursement channels',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('category', models.CharField(max_length=2, verbose_name='category', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('description', models.TextField(verbose_name='description', blank=True)),
                ('category_name', models.CharField(max_length=300, verbose_name='description name', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'document category',
                'verbose_name_plural': 'document categories',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='DocumentCategoryCategory',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('description', models.TextField(verbose_name='description', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'document category category',
                'verbose_name_plural': 'document category categories',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='FileFormat',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('category', models.CharField(max_length=20, verbose_name='category', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='category', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'file format',
                'verbose_name_plural': 'file formats',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='FinanceType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('category', models.CharField(max_length=3, verbose_name='category', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('category_name', models.CharField(max_length=300, verbose_name='category name', blank=True)),
                ('category_description', models.TextField(verbose_name='category description', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'finance type',
                'verbose_name_plural': 'finance types',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='FinanceTypeCategory',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('description', models.TextField(verbose_name='description', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'finance type category',
                'verbose_name_plural': 'finance type categories',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='FlowType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('description', models.TextField(verbose_name='description', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'flow type',
                'verbose_name_plural': 'flow types',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='GazetteerAgency',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'gazetteer agency',
                'verbose_name_plural': 'gazetteer agency',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='GeographicalPrecision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('description', models.TextField(verbose_name='description', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'geographical precision',
                'verbose_name_plural': 'geographical precisions',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='GeographicExactness',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('description', models.TextField(verbose_name='description', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'geographic exactness',
                'verbose_name_plural': 'geographic exactnesses',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='GeographicLocationClass',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('description', models.TextField(verbose_name='description', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'geographic location class',
                'verbose_name_plural': 'geographic location classes',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='GeographicLocationReach',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('description', models.TextField(verbose_name='description', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'geographic location reach',
                'verbose_name_plural': 'geographic location reach',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='GeographicVocabulary',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('url', models.URLField(verbose_name='url', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('description', models.TextField(verbose_name='description', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'geographic vocabulary',
                'verbose_name_plural': 'geographic vocabularies',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='HumanitarianScopeType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'humanitarian scope type',
                'verbose_name_plural': 'humanitarian scope types',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='HumanitarianScopeVocabulary',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('url', models.URLField(verbose_name='url', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'humanitarian scope vocabulary',
                'verbose_name_plural': 'humanitarian scope vocabularies',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='IndicatorMeasure',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('description', models.TextField(verbose_name='description', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'indicator measure',
                'verbose_name_plural': 'indicator measures',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='IndicatorVocabulary',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('url', models.URLField(verbose_name='url', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'indicator vocabulary',
                'verbose_name_plural': 'indicator vocabularies',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'language',
                'verbose_name_plural': 'languages',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='LoanRepaymentPeriod',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('description', models.TextField(verbose_name='description', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'loan repayment period',
                'verbose_name_plural': 'loan repayment periods',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='LoanRepaymentType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('description', models.TextField(verbose_name='description', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'loan repayment type',
                'verbose_name_plural': 'loan repayment types',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('category', models.CharField(max_length=2, verbose_name='category', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('description', models.TextField(verbose_name='description', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'location type',
                'verbose_name_plural': 'location types',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='LocationTypeCategory',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'location type category',
                'verbose_name_plural': 'location type categories',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='OrganisationIdentifier',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('abbreviation', models.CharField(max_length=100, verbose_name='abbreviation', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'organisation identifier',
                'verbose_name_plural': 'organisation identifiers',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='OrganisationRegistrationAgency',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('category', models.CharField(max_length=2, verbose_name='category', blank=True)),
                ('url', models.URLField(verbose_name='url', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('description', models.TextField(verbose_name='description', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'organisation registration agency',
                'verbose_name_plural': 'organisation registration agencies',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='OrganisationRole',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('description', models.TextField(verbose_name='description', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'organisation role',
                'verbose_name_plural': 'organisation role',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='OrganisationType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'organisation type',
                'verbose_name_plural': 'organisation types',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='OtherIdentifierType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('description', models.TextField(verbose_name='description', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'other identifier type',
                'verbose_name_plural': 'other identifier types',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PolicyMarker',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'policy marker',
                'verbose_name_plural': 'policy markers',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PolicyMarkerVocabulary',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('description', models.TextField(verbose_name='description', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'policy marker vocabulary',
                'verbose_name_plural': 'policy marker vocabularies',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PolicySignificance',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('description', models.TextField(verbose_name='description', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'policy significance',
                'verbose_name_plural': 'policy significances',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PublisherType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('description', models.TextField(verbose_name='description', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'publisher type',
                'verbose_name_plural': 'publisher types',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'region',
                'verbose_name_plural': 'regions',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='RegionVocabulary',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('description', models.TextField(verbose_name='description', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'region vocabulary',
                'verbose_name_plural': 'region vocabularies',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='RelatedActivityType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('description', models.TextField(verbose_name='description', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'related activity type',
                'verbose_name_plural': 'related activity types',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ResultType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('description', models.TextField(verbose_name='description', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'result type',
                'verbose_name_plural': 'result types',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('category', models.CharField(max_length=3, verbose_name='category', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('description', models.TextField(verbose_name='description', blank=True)),
                ('category_name', models.CharField(max_length=300, verbose_name='category name', blank=True)),
                ('category_description', models.TextField(verbose_name='category description', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'sector',
                'verbose_name_plural': 'sectors',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='SectorCategory',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('description', models.TextField(verbose_name='description', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'sector category',
                'verbose_name_plural': 'sector categories',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='SectorVocabulary',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('url', models.URLField(verbose_name='url', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('description', models.TextField(verbose_name='description', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'sector vocabulary',
                'verbose_name_plural': 'sector vocabulary',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='TiedStatus',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('description', models.TextField(verbose_name='description', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'tied status',
                'verbose_name_plural': 'tied statuses',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('description', models.TextField(verbose_name='description', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'transaction type',
                'verbose_name_plural': 'transaction types',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ValueType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('description', models.TextField(verbose_name='description', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'value type',
                'verbose_name_plural': 'value types',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='VerificationStatus',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('description', models.TextField(verbose_name='description', blank=True)),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'verification status',
                'verbose_name_plural': 'verification statuses',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(max_length=4, verbose_name='code')),
                ('url', models.URLField(verbose_name='url', blank=True)),
            ],
            options={
                'ordering': ('-code',),
                'verbose_name': 'version',
                'verbose_name_plural': 'versions',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('version', models.ForeignKey(verbose_name='version', to='codelists.Version')),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'vocabulary',
                'verbose_name_plural': 'vocabulary',
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='verificationstatus',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='valuetype',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='tiedstatus',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='sectorvocabulary',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='sectorcategory',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='sector',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='resulttype',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='relatedactivitytype',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='regionvocabulary',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='region',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='publishertype',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='policysignificance',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='policymarkervocabulary',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='policymarker',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='otheridentifiertype',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='organisationtype',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='organisationrole',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='organisationregistrationagency',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='organisationidentifier',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='locationtypecategory',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='locationtype',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='loanrepaymenttype',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='loanrepaymentperiod',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='language',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='indicatorvocabulary',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='indicatormeasure',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='humanitarianscopevocabulary',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='humanitarianscopetype',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='geographicvocabulary',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='geographiclocationreach',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='geographiclocationclass',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='geographicexactness',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='geographicalprecision',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='gazetteeragency',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='flowtype',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='financetypecategory',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='financetype',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='fileformat',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='documentcategorycategory',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='documentcategory',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='disbursementchannel',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='descriptiontype',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='currency',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='crschannelcode',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='crsaddotherflags',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='country',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='contacttype',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='conditiontype',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='collaborationtype',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='budgettype',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='budgetstatus',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='budgetidentifiervocabulary',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='budgetidentifiersectorcategory',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='budgetidentifiersector',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='budgetidentifier',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='aidtypeflag',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='aidtypecategory',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='aidtype',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='activitystatus',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='activityscope',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='activitydatetype',
            name='version',
            field=models.ForeignKey(verbose_name='version', to='codelists.Version'),
            preserve_default=True,
        ),
    ]
