# -*- coding: utf-8 -*-


from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codelists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetStatus',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('description', models.TextField(verbose_name='description', blank=True)),
                ('version', models.ForeignKey(verbose_name='version', to='codelists.Version')),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'budget status',
                'verbose_name_plural': 'budget statuses',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='CRSChannelCode',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('version', models.ForeignKey(verbose_name='version', to='codelists.Version')),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'crs channel code',
                'verbose_name_plural': 'crs channel codes',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='HumanitarianScopeType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('version', models.ForeignKey(verbose_name='version', to='codelists.Version')),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'humanitarian scope type',
                'verbose_name_plural': 'humanitarian scope types',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='HumanitarianScopeVocabulary',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('url', models.URLField(verbose_name='url', blank=True)),
                ('version', models.ForeignKey(verbose_name='version', to='codelists.Version')),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'humanitarian scope vocabulary',
                'verbose_name_plural': 'humanitarian scope vocabularies',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='IndicatorVocabulary',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True)),
                ('name', models.CharField(max_length=300, verbose_name='name', blank=True)),
                ('url', models.URLField(verbose_name='url', blank=True)),
                ('version', models.ForeignKey(verbose_name='version', to='codelists.Version')),
            ],
            options={
                'ordering': ('-version', 'code'),
                'verbose_name': 'indicator vocabulary',
                'verbose_name_plural': 'indicator vocabularies',
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='geographicvocabulary',
            name='description',
            field=models.TextField(verbose_name='description', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='activitydatetype',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='activityscope',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='activitystatus',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='aidtype',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='aidtypecategory',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='aidtypeflag',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='budgetidentifier',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='budgetidentifiersector',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='budgetidentifiersectorcategory',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='budgetidentifiervocabulary',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='budgettype',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='collaborationtype',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='conditiontype',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contacttype',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='crsaddotherflags',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='descriptiontype',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='disbursementchannel',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='documentcategory',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='documentcategorycategory',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='fileformat',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='financetype',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='financetypecategory',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='flowtype',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='gazetteeragency',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='geographicalprecision',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='geographicexactness',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='geographiclocationclass',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='geographiclocationreach',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='geographicvocabulary',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='indicatormeasure',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='loanrepaymentperiod',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='loanrepaymenttype',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='locationtype',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='locationtypecategory',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='organisationidentifier',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='organisationregistrationagency',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='organisationrole',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='organisationtype',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='otheridentifiertype',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='policymarker',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='policymarkervocabulary',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='policysignificance',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='publishertype',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='regionvocabulary',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='relatedactivitytype',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='resulttype',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='sector',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='sectorcategory',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='sectorvocabulary',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='tiedstatus',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='valuetype',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='verificationstatus',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='code', blank=True),
            preserve_default=True,
        ),
    ]
