# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-25 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codelists', '0004_auto_20160920_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crsaddotherflags',
            options={'ordering': ('pk',), 'verbose_name': 'crs add other flag', 'verbose_name_plural': 'crs add other flags'},
        ),
    ]
