# Generated by Django 3.2.10 on 2022-04-12 01:54

from akvo.codelists.store import codelists_v203
from django.db import migrations


def add_v203_codelists(apps, schema_editor):
    """
    Load the IATI v2.03 codelists in the database.
    """
    # Add new version first
    Version = apps.get_model('codelists', 'Version')
    v203, _ = Version.objects.get_or_create(code='2.03', url="http://iatistandard.org/203/")

    # Add all new codelists, linked to the v2.02 version
    for codelist in codelists_v203.codelist_list:
        if codelist != 'VERSION':
            codelist_tuples = getattr(codelists_v203, codelist, None)
            if codelist_tuples is not None:
                codelist_fields = codelist_tuples[0]
                for codelist_entry in codelist_tuples[1:]:
                    codelist_dict = {}
                    codelist_dict['version'] = v203
                    for index, field in enumerate(codelist_fields):
                        codelist_dict[field] = codelist_entry[index]
                    Model = apps.get_model('codelists', codelist.replace('_', ''))
                    Model.objects.get_or_create(**codelist_dict)


class Migration(migrations.Migration):

    dependencies = [
        ('codelists', '0006_auto_20220412_0148'),
    ]

    operations = [
        migrations.RunPython(
            add_v203_codelists
        ),
    ]
