#!/bin/bash

cd "`dirname $0`"
cd ../../tests/acceptance

ACCEPTANCE_TEST_ROOT_DIR=`pwd`

# check if PYTHONPATH exists
if [ -z "$PYTHONPATH" ]; then
    export PYTHONPATH=$ACCEPTANCE_TEST_ROOT_DIR
else
    export PYTHONPATH=$ACCEPTANCE_TEST_ROOT_DIR:$PYTHONPATH
fi

./all_test_suites.py
