#!/bin/bash

cd "`dirname $0`"

if [ -z "$1" ]; then
    printf "Usage: run_django_tests <virtualenv_path> [ci_mode]\n"
    exit -1
fi

VIRTUALENV_PATH=$1

if [ -r $VIRTUALENV_PATH ]; then
    source $VIRTUALENV_PATH/bin/activate
else
    printf ">> Akvo virtual environment [%s] not found\n" $VIRTUALENV_PATH
    exit -1
fi

python verify_static_project_structure.py $2

cd ../../akvo
echo "Validating Django models:"
python manage.py validate
echo "Running Django tests:"
python manage.py test --noinput rsr

deactivate
