apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsr-db-migration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rsr-db-migration
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rsr-db-migration
    spec:
      containers:
      - name: rsr-db-migration
        image: eu.gcr.io/akvo-lumen/rsr-backend:d32a6d182cabfc9cd24eb4da8f52f6119ebad7bc
        command: ["/bin/sh"]
        args: ["-c", "while true; do sleep 10;done"]
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "4000m"
        env:
      - name: cloudsql-proxy
        image: eu.gcr.io/cloudsql-docker/gce-proxy:1.16
        command: ["/cloud_sql_proxy",
                  "-instances=akvo-lumen:europe-west1:$(GOOGLE_SQL_DB_INSTANCE)=tcp:5432",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        securityContext:
          runAsUser: 2  # non-root user
          allowPrivilegeEscalation: false
        env:
          - name: GOOGLE_SQL_DB_INSTANCE
            value: rsr-prod-database
        volumeMounts:
          - name: "secret-config"
            mountPath: "/secrets/cloudsql/credentials.json"
            subPath: "cloud-database-service-account.json"
            readOnly: true
      volumes:
         - name: "secret-config"
           secret:
             secretName: "rsr-secret"
