export default {
  ADD_LOCATION: 'PE_ADD_LOCATION',
  REMOVE_LOCATION: 'PE_REMOVE_LOCATION',
  EDIT_LOCATION: 'PE_EDIT_LOCATION',
  ADD_COUNTRY: 'PE_ADD_COUNTRY',
  EDIT_COUNTRY: 'PE_EDIT_COUNTRY',
  REMOVE_COUNTRY: 'PE_REMOVE_COUNTRY'
}
